### ISSUE TITLE
Dashboard not showing on IMAT

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1034]
The Dashboard plugin is not starting on IMAT when ISISICP.exe is not running. This appears to be a null pointer exception when trying to load some XML for the periods.

{{{
Caused by: java.lang.NullPointerException
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.periods.XMLBackedPeriodSettings.initialiseFromXml(XMLBackedPeriodSettings.java:115)
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.periods.XMLBackedPeriodSettings.setXml(XMLBackedPeriodSettings.java:68)
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.periods.ObservingPeriodSettings$1.setFromText(ObservingPeriodSettings.java:36)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:35)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.BaseObserver.update(BaseObserver.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable.addObserver(ForwardingObservable.java:84)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway.<init>(SettingsGateway.java:61)
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.periods.ObservingPeriodSettings$1.<init>(ObservingPeriodSettings.java:33)
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.periods.ObservingPeriodSettings.<init>(ObservingPeriodSettings.java:33)
	at uk.ac.stfc.isis.ibex.dae.experimentsetup.ExperimentSetup.<init>(ExperimentSetup.java:54)
	at uk.ac.stfc.isis.ibex.dae.DaeModel.<init>(DaeModel.java:43)
	at uk.ac.stfc.isis.ibex.dae.Dae.<init>(Dae.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:167)
	... 106 more
}}}

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1036.  Created by whb43145 on 2016-01-18T11:07:17, last modified: 2016-01-26T15:24:50_
