### ISSUE TITLE
Github Repository manipulation scripts

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1144]
The GitHub API provides a way for manipulating repositories via scripts. I can see some tasks that would be helpful to be managed in this way as we have a lot of GitHub repositories in submodules, particularly related to keeping milestones and labels consistent across repositories. So:  
* Add a new sprint milestone (with a completion date) to a set / all repositories
* Add a new label to a set / all repositories

There may also be some searches that are better performed by this API, and we could also run some checks for "stale" branches, tickets in funny states or missing some relevant labels etc.
 
The official GitHub Octokit is available in Ruby and .NET, but other 3rd party language bindings exist  https://developer.github.com/libraries/  Maybe a quick evaluation of “keeping it official” v using a python binding?

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_utils (I have comited this to master by mistake but it is the first commit)

Test:

install (as per readme on repository) then run using a private repository
-o <your user name> -repo <name of private repository>
--dry-run could also be useful

**Comment by AdrianPotter** [comment]
Reviewing

**Comment by AdrianPotter** [comment]
Reviewing...

**Comment by AdrianPotter** [comment]
Testing now...

**Comment by AdrianPotter** [comment]
1. If I run change_repos.py --username AdrianPotter, I get the error "change_repos.py: error: argument -u/--username is required". Presumably I'm still lacking arguments, but username isn't one of them

**Comment by AdrianPotter** [comment]
I created a new repo AdrianPotter/ScriptTest and have successfully added a new milestone

**Comment by AdrianPotter** [comment]
Q3. There are 2 warnings that are emitted with genie_python at startup; SNIMissingWarning, InsecurePlatformWarning. They are to do with genie_python's packages being out of date. Should we suppress them as clutter?

A3 [Following discussion with John]: It doesn't affect functionality and serves as a reminder that it would be good at some point to update the genie_python packages. Leave them in

Q4. When I run the following (I forgot the --repo argument):

python change_repos.py -u AdrianPotter -o AdrianPotter --label-name Urgent --label-color #000000

I get the following crash:

Traceback (most recent call last):
  File "change_repos.py", line 200, in <module>
    main(_parse_command_line(), _get_user_token())
  File "change_repos.py", line 38, in main
    isis_repo_access.add_all_repos_for_org(settings.organisation)
AttributeError: 'Namespace' object has no attribute 'organisation'

It should presumably do something else, not sure what, in this case.

**Comment by AdrianPotter** [comment]
When I include the correct arguments, adding a label works as expected.

**Comment by AdrianPotter** [comment]
Q5. The line-colour argument accepts colour codes with hashes. When I created a label file, I included the hashes there too. In this case it interprets the line as a comment and says there are no labels in the file. The behaviour should be made consistent and the documentation/warnings extended to make it clear to the user not to put hashes in colour codes.

**Comment by AdrianPotter** [comment]
Tested that using a repos file in place of a repo works as expected. All good.

**Comment by AdrianPotter** [comment]
Thanks for the script John, it works great apart from the couple of points mentioned. Please could you respond to Qs 1,2,4 and 5. Cheers!

**Comment by John-Holt-Tessella** [comment]
Done see: https://github.com/ISISComputingGroup/ibex_utils/pull/2

**Comment by AdrianPotter** [comment]
All fixes test and confirmed. Thanks!
