### ISSUE TITLE
DAE Spectra plots not working on LARMOR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1175]
On LARMOR currently the spectra plots are not working, I had a look at the PVS e.g. IN:LARMOR:DAE:SPEC:1:1:X and IN:LARMOR:DAE:SPEC:1:1:Y and they are updating OK

**Comment by John-Holt-Tessella** [comment]
OK I will have another look at this tomorrow but I think it is because of the clear traces lines on update x and y (lines 115 and 125 of SpectrumPlot.java). I think instead of doing this we should set `traceDataProvider.setConcatenate_data(false);` at line 105

Is there anyway of seeing the graphs update or does the experiment have to be running?

**Comment by John-Holt-Tessella** [comment]
Plus on switch perspectives I see:

java.lang.NullPointerException
	at uk.ac.stfc.isis.ibex.ui.dae.DaeView$1.propertyChange(DaeView.java:73)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at uk.ac.stfc.isis.ibex.model.ModelObject.firePropertyChange(ModelObject.java:47)
	at uk.ac.stfc.isis.ibex.model.UpdatedValue.setValue(UpdatedValue.java:55)
	at uk.ac.stfc.isis.ibex.model.SettableUpdatedValue.setValue(SettableUpdatedValue.java:33)
	at uk.ac.stfc.isis.ibex.epics.adapters.UpdatedObservableAdapter.connectionChanged(UpdatedObservableAdapter.java:59)
	at uk.ac.stfc.isis.ibex.epics.adapters.UpdatedObservableAdapter$1.onConnectionStatus(UpdatedObservableAdapter.java:46)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onConnectionStatus(ForwardingObservable.java:42)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onConnectionStatus(TransformingObservable.java:47)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onConnectionStatus(ForwardingObservable.java:42)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable.setSource(ForwardingObservable.java:54)
	at uk.ac.stfc.isis.ibex.epics.switching.SwitchableObservable.setSource(SwitchableObservable.java:90)
	at uk.ac.stfc.isis.ibex.epics.switching.ObservablePrefixChangingSwitcher.switchInstrument(ObservablePrefixChangingSwitcher.java:53)
	at uk.ac.stfc.isis.ibex.epics.switching.InstrumentSwitchers.setInstrument(InstrumentSwitchers.java:93)
	at uk.ac.stfc.isis.ibex.epics.switching.SwitchInstrumentReceiver.setInstrument(SwitchInstrumentReceiver.java:34)
	at uk.ac.stfc.isis.ibex.instrument.Instrument.updateExtendingPlugins(Instrument.java:164)
	at uk.ac.stfc.isis.ibex.instrument.Instrument.setInstrument(Instrument.java:134)
	at uk.ac.stfc.isis.ibex.ui.mainmenu.instrument.InstrumentHandler.setInstrument(InstrumentHandler.java:115)
	at uk.ac.stfc.isis.ibex.ui.mainmenu.instrument.InstrumentHandler.execute(InstrumentHandler.java:74)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
	at org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:829)
	at org.eclipse.ui.menus.CommandContributionItem.access$19(CommandContributionItem.java:815)
	at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:805)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at uk.ac.stfc.isis.ibex.product.Application.start(Application.java:39)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
*2016-05-09 17:12:53.827 [main] ERROR org.eclipse.ui.workbench - null
	uk.ac.stfc.isis.ibex.ui.dae.DaeView$1.propertyChange(DaeView.java:73)
	java.beans.PropertyChangeSupport.fire(Unknown Source)
	java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	uk.ac.stfc.isis.ibex.model.ModelObject.firePropertyChange(ModelObject.java:47)
	uk.ac.stfc.isis.ibex.model.UpdatedValue.setValue(UpdatedValue.java:55)
	uk.ac.stfc.isis.ibex.model.SettableUpdatedValue.setValue(SettableUpdatedValue.java:33)
	uk.ac.stfc.isis.ibex.epics.adapters.UpdatedObservableAdapter.connectionChanged(UpdatedObservableAdapter.java:59)
	uk.ac.stfc.isis.ibex.epics.adapters.UpdatedObservableAdapter$1.onConnectionStatus(UpdatedObservableAdapter.java:46)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onConnectionStatus(ForwardingObservable.java:42)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onConnectionStatus(TransformingObservable.java:47)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setConnectionStatus(ClosableObservable.java:93)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onConnectionStatus(ForwardingObservable.java:42)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable.setSource(ForwardingObservable.java:54)
	uk.ac.stfc.isis.ibex.epics.switching.SwitchableObservable.setSource(SwitchableObservable.java:90)
	uk.ac.stfc.isis.ibex.epics.switching.ObservablePrefixChangingSwitcher.switchInstrument(ObservablePrefixChangingSwitcher.java:53)
	uk.ac.stfc.isis.ibex.epics.switching.InstrumentSwitchers.setInstrument(InstrumentSwitchers.java:93)
	uk.ac.stfc.isis.ibex.epics.switching.SwitchInstrumentReceiver.setInstrument(SwitchInstrumentReceiver.java:34)
	uk.ac.stfc.isis.ibex.instrument.Instrument.updateExtendingPlugins(Instrument.java:164)
	uk.ac.stfc.isis.ibex.instrument.Instrument.setInstrument(Instrument.java:134)
	uk.ac.stfc.isis.ibex.ui.mainmenu.instrument.InstrumentHandler.setInstrument(InstrumentHandler.java:115)
	uk.ac.stfc.isis.ibex.ui.mainmenu.instrument.InstrumentHandler.execute(InstrumentHandler.java:74)
	org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
	org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
	org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
	org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:829)
	org.eclipse.ui.menus.CommandContributionItem.access$19(CommandContributionItem.java:815)
	org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:805)
	org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	uk.ac.stfc.isis.ibex.product.Application.start(Application.java:39)
	org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by John-Holt-Tessella** [comment]
Reproducable crash (may be related):

1) open DAE
2) switch instrument (only changes name  nothing else)

**Comment by John-Holt-Tessella** [comment]
Change in graph behaviour possibly due to https://github.com/ISISComputingGroup/ibex_gui/commit/78e48281b2db68b9c4bfbcd992a9e83240d74476

**Comment by John-Holt-Tessella** [comment]
Acceptance Criteria:

1) With alarm event and flashing button close UI (no stack trace on exit)
2) With log event button flashing close the UI (no stack trace on exit)
3) With DAE panel open switch instrument (instrument switch complete)
4) With DAE panel open close UI (no stack trace)
5) Graphs are shown on DAE panel

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/220

**Comment by John-Holt-Tessella** [comment]
On IMAT when the instrument is running:

They don't seem to update when you start running, you just get what was in the DAE when you first started IBEX. Also the X scale is truncated, is there a limit to the number of points? IMAT currently has 6976 data points configured. Thanks, Freddie

The PV arrays currently have an 8000 limit, but that may get increased one day. "Time-of-flight (us)" would be good for X  "Counts /us" would be good for Y. Also it would be nice if the scales were "8000" not "8E3" where that was possible,  so printf "%g" rather than "%e" - i know it will need to use E eventually of course...
The "u" is a greek mu (for micro) if that's possible

**Comment by John-Holt-Tessella** [comment]
Can not do %g but have set it to decimal so no exponentials at all.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/224
