### ISSUE TITLE
genie:Unhandled exception in change_tcb_file()

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1337]
I called:

change_tcb_file(wiring="C:/Instrument/Settings/config/NDXDEMO/configurations/tables/wiring128.dat")

and got a stack strace:

Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\ipython-2.2.0-py2.7.egg\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-179-ebc4be151262>", line 1, in <module>
    change_tcb_file(wiring="C:/Instrument/Settings/config/NDXDEMO/configurations/tables/wiring128.dat")
TypeError: change_tcb_file() got an unexpected keyword argument 'wiring'

Admittedly sending genie a wiring table in place of a tcb_file was wrong, but exceptions should be handled appropriately.

**Comment by AdrianPotter** [comment]
But at least it recognises Windows file paths

**Comment by AdrianPotter** [comment]
This is standard Python behaviour. We don't catch everything at the top level
