### ISSUE TITLE
GUI: Exception on Beam Status Display

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1386]
When opening the beam status the following exception is thrown:

```
org.eclipse.ui.PartInitException: Could not create view: uk.ac.stfc.isis.ibex.ui.beamstatus.views.BeamStatusView
	at org.eclipse.ui.internal.ViewFactory.createView(ViewFactory.java:158)
	at org.eclipse.ui.internal.LayoutHelper.createView(LayoutHelper.java:162)
	at org.eclipse.ui.internal.PageLayout.createView(PageLayout.java:554)
	at org.eclipse.ui.internal.PageLayout.addView(PageLayout.java:416)
	at org.eclipse.ui.internal.PageLayout.addStandaloneView(PageLayout.java:905)
	at org.eclipse.ui.internal.registry.PerspectiveExtensionReader.processView(PerspectiveExtensionReader.java:295)
	at org.eclipse.ui.internal.registry.PerspectiveExtensionReader.processExtension(PerspectiveExtensionReader.java:118)
	at org.eclipse.ui.internal.registry.PerspectiveExtensionReader.readElement(PerspectiveExtensionReader.java:355)
	at org.eclipse.ui.internal.registry.RegistryReader.readElements(RegistryReader.java:144)
	at org.eclipse.ui.internal.registry.RegistryReader.readExtension(RegistryReader.java:155)
	at org.eclipse.ui.internal.registry.RegistryReader.readRegistry(RegistryReader.java:176)
	at org.eclipse.ui.internal.registry.PerspectiveExtensionReader.extendLayout(PerspectiveExtensionReader.java:82)
	at org.eclipse.ui.internal.Perspective.loadPredefinedPersp(Perspective.java:818)
	at org.eclipse.ui.internal.Perspective.createPresentation(Perspective.java:270)
	at org.eclipse.ui.internal.Perspective.<init>(Perspective.java:156)
	at org.eclipse.ui.internal.tweaklets.Workbench3xImplementation.createPerspective(Workbench3xImplementation.java:55)
	at org.eclipse.ui.internal.WorkbenchPage.createPerspective(WorkbenchPage.java:1761)
	at org.eclipse.ui.internal.WorkbenchPage.busySetPerspective(WorkbenchPage.java:1117)
	at org.eclipse.ui.internal.WorkbenchPage.access$16(WorkbenchPage.java:1108)
	at org.eclipse.ui.internal.WorkbenchPage$19.run(WorkbenchPage.java:3827)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3825)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:2875)
	at uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$2.run(PerspectiveSwitcher.java:74)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	at uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$3.run(PerspectiveSwitcher.java:86)
	at uk.ac.stfc.isis.ibex.ui.UI$1.run(UI.java:59)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	at uk.ac.stfc.isis.ibex.ui.UI.switchPerspective(UI.java:52)
	at uk.ac.stfc.isis.ibex.ui.perspectives.switcher.PerspectiveButton$1.mouseDown(PerspectiveButton.java:73)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at uk.ac.stfc.isis.ibex.product.Application.start(Application.java:39)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
!SUBENTRY 1 org.eclipse.ui 4 0 2016-07-06 14:34:36.170
!MESSAGE Could not create view: uk.ac.stfc.isis.ibex.ui.beamstatus.views.BeamStatusView
*2016-07-06 14:34:36.170 [main] ERROR org.eclipse.ui.workbench - Could not create view: uk.ac.stfc.isis.ibex.ui.beamstatus.views.BeamStatusView
	org.eclipse.ui.internal.ViewFactory.createView(ViewFactory.java:158)
	org.eclipse.ui.internal.LayoutHelper.createView(LayoutHelper.java:162)
	org.eclipse.ui.internal.PageLayout.createView(PageLayout.java:554)
	org.eclipse.ui.internal.PageLayout.addView(PageLayout.java:416)
	org.eclipse.ui.internal.PageLayout.addStandaloneView(PageLayout.java:905)
	org.eclipse.ui.internal.registry.PerspectiveExtensionReader.processView(PerspectiveExtensionReader.java:295)
	org.eclipse.ui.internal.registry.PerspectiveExtensionReader.processExtension(PerspectiveExtensionReader.java:118)
	org.eclipse.ui.internal.registry.PerspectiveExtensionReader.readElement(PerspectiveExtensionReader.java:355)
	org.eclipse.ui.internal.registry.RegistryReader.readElements(RegistryReader.java:144)
	org.eclipse.ui.internal.registry.RegistryReader.readExtension(RegistryReader.java:155)
	org.eclipse.ui.internal.registry.RegistryReader.readRegistry(RegistryReader.java:176)
	org.eclipse.ui.internal.registry.PerspectiveExtensionReader.extendLayout(PerspectiveExtensionReader.java:82)
	org.eclipse.ui.internal.Perspective.loadPredefinedPersp(Perspective.java:818)
	org.eclipse.ui.internal.Perspective.createPresentation(Perspective.java:270)
	org.eclipse.ui.internal.Perspective.<init>(Perspective.java:156)
	org.eclipse.ui.internal.tweaklets.Workbench3xImplementation.createPerspective(Workbench3xImplementation.java:55)
	org.eclipse.ui.internal.WorkbenchPage.createPerspective(WorkbenchPage.java:1761)
	org.eclipse.ui.internal.WorkbenchPage.busySetPerspective(WorkbenchPage.java:1117)
	org.eclipse.ui.internal.WorkbenchPage.access$16(WorkbenchPage.java:1108)
	org.eclipse.ui.internal.WorkbenchPage$19.run(WorkbenchPage.java:3827)
	org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3825)
	org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:2875)
	uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$2.run(PerspectiveSwitcher.java:74)
	org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$3.run(PerspectiveSwitcher.java:86)
	uk.ac.stfc.isis.ibex.ui.UI$1.run(UI.java:59)
	org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	uk.ac.stfc.isis.ibex.ui.UI.switchPerspective(UI.java:52)
	uk.ac.stfc.isis.ibex.ui.perspectives.switcher.PerspectiveButton$1.mouseDown(PerspectiveButton.java:73)
	org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	uk.ac.stfc.isis.ibex.product.Application.start(Application.java:39)
	org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.eclipse.ui 4 4 2016-07-06 14:34:36.172
!MESSAGE Referenced part does not exist yet: uk.ac.stfc.isis.ibex.ui.beamstatus.views.BeamStatusView.
*2016-07-06 14:34:36.172 [main] ERROR org.eclipse.ui.workbench - Referenced part does not exist yet: uk.ac.stfc.isis.ibex.ui.beamstatus.views.BeamStatusView.
```

Reproduce:

1. Open IBEX
1. Click Beam Status

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/314
