### ISSUE TITLE
BlockServer: Appears to crash on restart

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1770]
Block server appears to restart twice after manual restart. I am not sure whether this is an issue but I think it probably is. I have lots of synoptics and configurations and a branch which should be being push to. I am not sure where or why it is crashing:

```
@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 13676. Normal exit status = 1
@@@ Current time: Wed Nov  2 11:16:54 2016
@@@ Child process is shutting down, a new one will be restarted shortly
@@@ ^R or ^X restarts the child, ^Q quits the server
@@@ Restarting child "BLOCKSVR"
@@@    (as C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\start_blockserver_c
md.bat)
@@@ The PID of new child "BLOCKSVR" is: 16576
@@@ @@@ @@@ @@@ @@@

C:\Instrument\Apps\EPICS>REM @echo off

C:\Instrument\Apps\EPICS>set MYDIRBLOCK=C:\Instrument\Apps\EPICS\ISIS\inst_serve
rs\master\

C:\Instrument\Apps\EPICS>call C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\
..\..\..\config_env_base.bat
### $Id$ ###
INFO: FACILITY = ISIS
INFO: BLOCK GATEWAY PREFIX = NDW1407:HGV27692:CS:GATEWAY:BLOCKSERVER:
INFO: CONFIGURATION DIRECTORROOT_DIR C:\Instrument\Settings\config\NDW1407\confi
gurations
INFO: SCHEMA DIRECTORY = C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\schem
a
INFO: ARCHIVE UPLOADER = C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\set_b
lock_config.bat
INFO: ARCHIVE SETTINGS = C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\block
_config.xml
INFO: BLOCKSERVER PREFIX = NDW1407:HGV27692:CS:
cas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 53941,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
INFO: Adding PV BLOCKSERVER:BLOCK_RULES
INFO: Adding PV BLOCKSERVER:GROUP_RULES
INFO: Adding PV BLOCKSERVER:CONF_DESC_RULES
INFO: Attempting to remove: C:\Instrument\Settings\config\NDW1407\.git\index.loc
k
NDW1407:HGV27692:
INFO: Adding PV BLOCKSERVER:JULABO:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:JULABO:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:LARMOR:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:LARMOR:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:SIMPLE:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:SIMPLE:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:_BASE:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:_BASE:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:ADDED_:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:ADDE01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:BLAH_N:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:CAN_NO:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DEFAUL:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DEMOAU:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DFGDFG:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:EUROTH:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LARMOR:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:LARM01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LARM02:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LOTS_O:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:PLAY:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:PLAY_I:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:RCPTT_:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:RCPT01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:SAD:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:STARTU:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:TEST_A:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:WITH_M:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Serving HTTP on port 8008 ...
INFO: Adding PV BLOCKSERVER:GET_RC_OUT
INFO: Adding PV BLOCKSERVER:GET_RC_PARS
RUNCONTROL SETTINGS FILE: C:/Instrument/Settings/config/NDW1407/configurations\r
c_settings.cmd
RUNCONTROL AUTOSAVE DIRECTORY: C:/Instrument/Var\autosave\RUNCTRL_01
INFO: Starting IOC RUNCTRL_01
INFO: Waiting for runcontrol IOC to start
INFO: Runcontrol IOC started
INFO: Runcontrol IOC started
INFO: Adding PV SYNOPTICS:NAMES

@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 16576. The process was killed by signal 11
@@@ Current time: Wed Nov  2 11:17:00 2016
@@@ Child process is shutting down, a new one will be restarted shortly
@@@ ^R or ^X restarts the child, ^Q quits the server
@@@ Restarting child "BLOCKSVR"
@@@    (as C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\start_blockserver_c
md.bat)
@@@ The PID of new child "BLOCKSVR" is: 17224
@@@ @@@ @@@ @@@ @@@

C:\Instrument\Apps\EPICS>REM @echo off

C:\Instrument\Apps\EPICS>set MYDIRBLOCK=C:\Instrument\Apps\EPICS\ISIS\inst_serve
rs\master\

C:\Instrument\Apps\EPICS>call C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\
..\..\..\config_env_base.bat
### $Id$ ###
INFO: FACILITY = ISIS
INFO: BLOCK GATEWAY PREFIX = NDW1407:HGV27692:CS:GATEWAY:BLOCKSERVER:
INFO: CONFIGURATION DIRECTORROOT_DIR C:\Instrument\Settings\config\NDW1407\confi
gurations
INFO: SCHEMA DIRECTORY = C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\schem
a
INFO: ARCHIVE UPLOADER = C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\set_b
lock_config.bat
INFO: ARCHIVE SETTINGS = C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\block
_config.xml
INFO: BLOCKSERVER PREFIX = NDW1407:HGV27692:CS:
cas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 53998,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
INFO: Adding PV BLOCKSERVER:BLOCK_RULES
INFO: Adding PV BLOCKSERVER:GROUP_RULES
INFO: Adding PV BLOCKSERVER:CONF_DESC_RULES
INFO: Attempting to remove: C:\Instrument\Settings\config\NDW1407\.git\index.loc
k
NDW1407:HGV27692:
INFO: Adding PV BLOCKSERVER:JULABO:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:JULABO:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:LARMOR:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:LARMOR:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:SIMPLE:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:SIMPLE:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:_BASE:GET_COMPONENT_DETAILS
INFO: Adding PV BLOCKSERVER:_BASE:DEPENDENCIES
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:ADDED_:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:ADDE01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:BLAH_N:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:CAN_NO:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DEFAUL:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DEMOAU:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:DFGDFG:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:EUROTH:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LARMOR:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:LARM01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LARM02:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
MINOR: Error in loading config: Element 'blocks': No matching global declaration
 available for the validation root.
INFO: Adding PV BLOCKSERVER:LOTS_O:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:PLAY:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:PLAY_I:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:RCPTT_:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:RCPT01:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:SAD:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:STARTU:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:TEST_A:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:WITH_M:GET_CONFIG_DETAILS
UPDATING CONFIG LIST MONITORS
INFO: Serving HTTP on port 8008 ...
INFO: Adding PV BLOCKSERVER:GET_RC_OUT
INFO: Adding PV BLOCKSERVER:GET_RC_PARS
RUNCONTROL SETTINGS FILE: C:/Instrument/Settings/config/NDW1407/configurations\r
c_settings.cmd
RUNCONTROL AUTOSAVE DIRECTORY: C:/Instrument/Var\autosave\RUNCTRL_01
INFO: Starting IOC RUNCTRL_01
INFO: Waiting for runcontrol IOC to start
INFO: Runcontrol IOC started
INFO: Runcontrol IOC started
INFO: Adding PV SYNOPTICS:NAMES
INFO: Adding PV SYNOPTICS:GET_DEFAULT
INFO: Adding PV SYNOPTICS:__BLANK__:GET
INFO: Adding PV SYNOPTICS:SET_DETAILS
INFO: Adding PV SYNOPTICS:DELETE
INFO: Adding PV SYNOPTICS:SCHEMA
INFO: Adding PV SYNOPTICS:DANFYS:GET
INFO: Adding PV SYNOPTICS:DEMOAD:GET
INFO: Adding PV SYNOPTICS:DEMOBA:GET
INFO: Adding PV SYNOPTICS:DEMO_A:GET
INFO: Adding PV SYNOPTICS:DEMO_E:GET
INFO: Adding PV SYNOPTICS:DEMO_M:GET
INFO: Adding PV SYNOPTICS:DEMO01:GET
INFO: Adding PV SYNOPTICS:DEMO_P:GET
INFO: Adding PV SYNOPTICS:DEMO_S:GET
INFO: Adding PV SYNOPTICS:JOHN:GET
INFO: Adding PV SYNOPTICS:LARMOR:GET
INFO: Adding PV SYNOPTICS:LARM01:GET
INFO: Adding PV SYNOPTICS:MONTIO:GET
INFO: Adding PV SYNOPTICS:MONT01:GET
INFO: Adding PV SYNOPTICS:MUON_F:GET
INFO: Adding PV SYNOPTICS:MUON01:GET
INFO: Adding PV SYNOPTICS:NUON_F:GET
INFO: Adding PV SYNOPTICS:TEST_S:GET
INFO: Adding PV BLOCKSERVER:GET_SCREENS
INFO: Adding PV BLOCKSERVER:SET_SCREENS
INFO: Adding PV BLOCKSERVER:SCREENS_SCHEMA
INFO: Found gateway
INFO: Trying to load last_configuration Eurotherm
INFO: Loaded last configuration: Eurotherm
CAS Request: hgv27692 on NDW1407: cmd=2 cid=12 typ=18 cnt=16000 psz=0 avail=4b7
CAS: bad resource id in "..\..\..\..\src\cas\generic\casStrmClient.cc" at line 2
207
filename="..\..\..\..\src\cas\generic\st\casStreamOS.cc" line number=605
Bad resource identifier - unexpected problem with client's input - forcing disco
nnect
CA exception in thread w/o CA ctx: status=User specified timeout on IO operation
 expired file=src/_ca314.cpp line=1612:
py_pend_ioUnable to find PV NDW1407:HGV27692:CS:IOCS
INFO: Setting IOC INSTETC_01's auto-restart to True
INFO: Auto-restart for IOC INSTETC_01 unchanged as value has not changed
INFO: Setting IOC ISISDAE_01's auto-restart to True
INFO: Auto-restart for IOC ISISDAE_01 unchanged as value has not changed
Creating block: fNEW_BLOCK_5 for dfg
Creating block: NEW_BLOCK_4 for ghj
Creating block: NEW_BLOCK_3 for ghjg
Creating block: NEW_BLOCK_2 for DAE:MONITORCOUNTS
Creating block: NEW_BLOCK_1 for DAE:MONITORSPECTRUM
Creating block: NEW_BLOCK for DAE:COUNTRATE
Creating block: sp1_sprbv for EUROTHERM1:A01:TEMP:SP:RBV
Creating block: sp1_temp for EUROTHERM1:A01:TEMP
INFO: Reloading gateway
INFO: Gateway reloaded
UPDATING CONFIG LIST MONITORS
INFO: Generating archiver configuration file: C:\Instrument\Apps\EPICS\CSS\maste
r\ArchiveEngine\block_config.xml
INFO: Running archiver settings uploader: C:\Instrument\Apps\EPICS\CSS\master\Ar
chiveEngine\set_block_config.bat
INFO: Reusing the existing run-control autosave files
INFO: Restarting IOC RUNCTRL_01
INFO: Waiting for runcontrol IOC to start
INFO: Runcontrol IOC started
Unexpected problem with CA circuit to server "NDW1407.isis.cclrc.ac.uk:53912" wa
s "An existing connection was forcibly closed by the remote host. " - disconnect
ing
CA.Client.Diagnostic.................................
    Warning: "Virtual circuit disconnect"
Source File: ..\cac.cpp Line Number: 1215
.....................................................
CA exception in thread w/o CA ctx: status=User specified timeout on IO operation
 expired file=src/_ca314.cpp line=1612:
py_pend_ioUnable to find PV NDW1407:HGV27692:CS:SB:NEW_BLOCK_4:RC:HIGH
INFO: Problem with setting runcontrol for NEW_BLOCK_4: Unable to find PV NDW1407
:HGV27692:CS:SB:NEW_BLOCK_4:RC:HIGH
UPDATING SYNOPTIC MONITORS
UPDATING DEVICES MONITORS
INFO: Restarting block cache...
INFO: Restarting IOC BLOCKCACHE
INFO: Auto-restart for IOC BLOCKCACHE unchanged as value has not changed
```

**Comment by KathrynBaker** [comment]
Added proposal ticket as it was agreed in sprint review to look at this (especialyl as it may be the problem for the system tests.

Adding the following code:
```
    print '-' * 60
    traceback.print_exc(file=sys.stdout)
    print '-' * 60
```
to print_and_log in inst_servers\master\server_common\utilities.py gave a flavour of some errors that can appear, although it is plausible that the same error is being repeated as this is a semi-random location to print the information from.

A fraction of the reported information with the traceback added bracketing that same type of restart as detailed above follows. Please note that this is an example only, and there is no guarantee that it is part of the error, especially as the system this was run on is out of date.

'''
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:TEST2:GET_CONFIG_DETAILS
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", l
ine 141, in _import_configs
    config = self.load_config(config_name)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", l
ine 161, in load_config
    config.load_inactive(name, is_component)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\inactive_config_holder.py"
, line 57, in load_inactive
    config = super(InactiveConfigHolder, self).load_configuration(name, is_component, False)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 46
0, in load_configuration
    return self._filemanager.load_config(name, self._macros, False)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 1
45, in load_config
    " (%s)" % ','.join(list(config_files_missing)))
ConfigurationIncompleteException: 'Files missing in synoptics (blocks.xml,groups.xml,iocs.xml,compon
ents.xml,meta.xml)'
------------------------------------------------------------
UPDATING CONFIG LIST MONITORS
INFO: Adding PV BLOCKSERVER:THIS_I:GET_CONFIG_DETAILS
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", l
ine 141, in _import_configs
    config = self.load_config(config_name)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", l
ine 161, in load_config
    config.load_inactive(name, is_component)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\inactive_config_holder.py"
, line 57, in load_inactive
    config = super(InactiveConfigHolder, self).load_configuration(name, is_component, False)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 46
0, in load_configuration
    return self._filemanager.load_config(name, self._macros, False)
  File "C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 1
45, in load_config
    " (%s)" % ','.join(list(config_files_missing)))
ConfigurationIncompleteException: 'Files missing in synoptics (blocks.xml,groups.xml,iocs.xml,compon
ents.xml,meta.xml)'
------------------------------------------------------------
UPDATING CONFIG LIST MONITORS
INFO: Serving HTTP on port 8008 ...
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV BLOCKSERVER:GET_RC_OUT
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV BLOCKSERVER:GET_RC_PARS
------------------------------------------------------------
None
------------------------------------------------------------
RUNCONTROL SETTINGS FILE: C:/Instrument/Settings/config/NDW1032/configurations\rc_settings.cmd
RUNCONTROL AUTOSAVE DIRECTORY: C:/Instrument/Var\autosave\RUNCTRL_01
INFO: Starting IOC RUNCTRL_01
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Waiting for runcontrol IOC to start
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Runcontrol IOC started
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Runcontrol IOC started
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV SYNOPTICS:NAMES
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV SYNOPTICS:GET_DEFAULT
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV SYNOPTICS:__BLANK__:GET
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV SYNOPTICS:SET_DETAILS
------------------------------------------------------------
None
------------------------------------------------------------
INFO: Adding PV SYNOPTICS:DELETE
---------------------------
@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 14572. The process was killed by signal 11
@@@ Current time: Wed Nov  2 13:15:22 2016
@@@ Child process is shutting down, a new one will be restarted shortly
@@@ ^R or ^X restarts the child, ^Q quits the server
@@@ Restarting child "BLOCKSVR"
@@@    (as c:\Instrument\Dev\EPICS\ISIS\inst_servers\master\start_blockserver_cmd.bat)
@@@ The PID of new child "BLOCKSVR" is: 9220
@@@ @@@ @@@ @@@ @@@

C:\Instrument\Dev\EPICS>REM @echo off

C:\Instrument\Dev\EPICS>set MYDIRBLOCK=C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\

C:\Instrument\Dev\EPICS>call C:\Instrument\Dev\EPICS\ISIS\inst_servers\master\..\..\..\config_env_ba
se.bat
### $Id$ ###
INFO: FACILITY = ISIS
------------------------------------------------------------
None
------------------------------------------------------------
'''

**Comment by mattclarke** [comment]
Moving back into rework as Freddie has commented on the solution.
