### ISSUE TITLE
XML parser exception on DEMO and RENO

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#1944]
When connecting to DEMO, and when the system tests run on RENO, the following exception is generated in the console when the GUI starts up:

```
*2017-01-04 15:50:38.250 [PVMgr Worker 4] INFO  uk.ac.stfc.isis.ibex.ui.synoptic.SynopticPresenter - Displaying target: -- NONE --
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at javax.xml.validation.SchemaFactory.newSchema(Unknown Source)
	at uk.ac.stfc.isis.ibex.devicescreens.xml.XMLUtil.setSchema(XMLUtil.java:107)
	at uk.ac.stfc.isis.ibex.devicescreens.ObservingSchemaHandler$1.onValue(ObservingSchemaHandler.java:41)
	at uk.ac.stfc.isis.ibex.devicescreens.ObservingSchemaHandler$1.onValue(ObservingSchemaHandler.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVReaderDirector$1.run(PVReaderDirector.java:309)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVReaderDirector.notifyPv(PVReaderDirector.java:280)
	at org.epics.pvmanager.PVReaderDirector$2.run(PVReaderDirector.java:335)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
*2017-01-04 15:50:38.622 [main] INFO  uk.ac.stfc.isis.ibex.configserver.Configurations - Current config connected: false
*2017-01-04 15:50:38.622 [main] INFO  uk.ac.stfc.isis.ibex.configserver.Configurations - Server status connected: false
```

This is caused by the schema file not being set properly, and should be fixed.

**Comment by Tom-Willemsen** [comment]
Thoughts from @John-Holt-Tessella and @FreddieAkeroyd :

- Where is the schema file being pulled from?
- If the schema file is stored locally as a configuration, it needs to be updated in https://github.com/ISISComputingGroup/ibex_system_tests/tree/master/RCPTT_Tests/cleanIBEXServer/rcptt_blank as this is the repository that the build server uses to do system tests.
- If the schema file is pulled from the block server, investigate why this isn't correct for DEMO and RENO

**Comment by FreddieAkeroyd** [comment]
For info, I get the error if I connect my GUI to DEMO but not if I connect it to IMAT

**Comment by mattclarke** [comment]
This was caused by the commit to VC in the device screens (on the block server) throwing an exception when a git lock is present.

**Comment by mattclarke** [comment]
Refactored how exception handling works for version control. It is clearer and more consistent now, not perfect but is heading in the right direction hopefully.
