### ISSUE TITLE
Issue with instrument list?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1946]
I sometimes see the following during system tests:

```
!ENTRY org.eclipse.osgi 2 0 2017-01-04 19:27:15.821
!MESSAGE While loading class "uk.ac.stfc.isis.ibex.instrument.list.InstrumentListUtils", thread "Thread[PVMgr Worker 1,5,main]" timed out waiting (5006ms) for thread "Thread[main,6,main]" to finish starting bundle "uk.ac.stfc.isis.ibex.instrument_1.0.0.668 [352]". To avoid deadlock, thread "Thread[PVMgr Worker 1,5,main]" is proceeding but "uk.ac.stfc.isis.ibex.instrument.list.InstrumentListUtils" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: State change in progress for bundle "reference:file:/C:/Jenkins/workspace/System_Tests_All_Tests/ibex_gui/Client/plugins/uk.ac.stfc.isis.ibex.instrument_1.0.0.668.jar" by thread "main".
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.getValidInstruments(InstrumentListObservable.java:103)
	at uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.setValue(InstrumentListObservable.java:76)
	at uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.setValue(InstrumentListObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)

	
*2017-01-04 19:27:15.827 [PVMgr Worker 1] ERROR org.eclipse.osgi - State change in progress for bundle "reference:file:/C:/Jenkins/workspace/System_Tests_All_Tests/ibex_gui/Client/plugins/uk.ac.stfc.isis.ibex.instrument_1.0.0.668.jar" by thread "main".
	org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
	org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
	org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.getValidInstruments(InstrumentListObservable.java:103)
	uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.setValue(InstrumentListObservable.java:76)
	uk.ac.stfc.isis.ibex.instrument.list.InstrumentListObservable.setValue(InstrumentListObservable.java:1)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
```

**Comment by kjwoodsISIS** [comment]
Could be complicated to fix.  We've estimated 2 story points, but it could be more.
Start by trying to reproduce and then re-assess.

**Comment by DominicOram** [comment]
There is also the following issue which may or may not be related:

*2017-01-30 17:32:42.571 [main] ERROR Instrument - Error whilst reading instrument list
    Channel CS:INSTLIST uses the default data source but one was never set.

**Comment by Tom-Willemsen** [comment]
I've found these exceptions in a development environment too - but not in the standard console. They're written to this log file in Eclipse's workspace directory:

```
C:\Instrument\Dev\Eclipse_v4\workspace\.metadata\.plugins\org.eclipse.pde.core\uk.ac.stfc.isis.ibex.product-0.0.0-SNAPSHOT.jar
```

**Comment by Tom-Willemsen** [comment]
I wonder if this stack trace from RCPTT's `ReportHelper` is related or not... have you seen this one before @FreddieAkeroyd ?

```
!ENTRY org.eclipse.osgi 2 0 2017-03-02 13:11:39.712
!MESSAGE While loading class "org.eclipse.rcptt.reporting.core.ReportHelper", thread "Thread[Worker-3,5,main]" timed out waiting (5004ms) for thread "Thread[Worker-2,5,main]" to finish starting bundle "org.eclipse.rcptt.reporting_2.1.0.201512011236 [227]". To avoid deadlock, thread "Thread[Worker-3,5,main]" is proceeding but "org.eclipse.rcptt.reporting.core.ReportHelper" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: State change in progress for bundle "reference:file:/C:/Instrument/Dev/Eclipse_v4/workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.rcptt.reporting_2.1.0.201512011236.jar" by thread "Worker-2".
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePackage.java:35)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobUpdate(JobsInfoSupport.java:83)
	at org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobChangeStatus(JobsInfoSupport.java:39)
	at org.eclipse.rcptt.sherlock.aspects.jobs.JobsAspect.ajc$before$org_eclipse_rcptt_sherlock_aspects_jobs_JobsAspect$3$cb92b286(JobsAspect.aj:60)
	at org.eclipse.core.internal.jobs.JobManager.changeState(JobManager.java:343)
	at org.eclipse.core.internal.jobs.JobManager.nextJob(JobManager.java:980)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1478)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:221)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:50)
Caused by: org.eclipse.osgi.framework.internal.core.AbstractBundle$BundleStatusException
	... 22 more
Root exception:
org.eclipse.osgi.framework.internal.core.AbstractBundle$BundleStatusException
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePackage.java:35)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobUpdate(JobsInfoSupport.java:83)
	at org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobChangeStatus(JobsInfoSupport.java:39)
	at org.eclipse.rcptt.sherlock.aspects.jobs.JobsAspect.ajc$before$org_eclipse_rcptt_sherlock_aspects_jobs_JobsAspect$3$cb92b286(JobsAspect.aj:60)
	at org.eclipse.core.internal.jobs.JobManager.changeState(JobManager.java:343)
	at org.eclipse.core.internal.jobs.JobManager.nextJob(JobManager.java:980)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1478)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:221)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:50)
*2017-03-02 13:11:39.755 [Worker-3] ERROR org.eclipse.osgi - State change in progress for bundle "reference:file:/C:/Instrument/Dev/Eclipse_v4/workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.rcptt.reporting_2.1.0.201512011236.jar" by thread "Worker-2".
	org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
	org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePackage.java:35)
	org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	java.lang.ClassLoader.loadClass(Unknown Source)
	org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobUpdate(JobsInfoSupport.java:83)
	org.eclipse.rcptt.tesla.swt.logging.JobsInfoSupport.jobChangeStatus(JobsInfoSupport.java:39)
	org.eclipse.rcptt.sherlock.aspects.jobs.JobsAspect.ajc$before$org_eclipse_rcptt_sherlock_aspects_jobs_JobsAspect$3$cb92b286(JobsAspect.aj:60)
	org.eclipse.core.internal.jobs.JobManager.changeState(JobManager.java:343)
	org.eclipse.core.internal.jobs.JobManager.nextJob(JobManager.java:980)
	org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1478)
	org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:221)
	org.eclipse.core.internal.jobs.Worker.run(Worker.java:50)
```
