### ISSUE TITLE
GUI: Opening the experiment details search screen generates an error

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1954]
The following is produced on loading the RB search screen (a few times), initial guess is that there is an attempted search on the name (which is initially blank) as the same error is produced on typing a space into the name field. This should probably be avoided on startup at least.

```
!ENTRY org.eclipse.core.databinding 2 0 2017-01-06 16:07:41.611
!MESSAGE Could not read value of uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupViewModel@393ae7a0.nameSearch
!STACK 0
java.lang.IllegalArgumentException: nameSearch property does not have a read method.
	at org.eclipse.core.internal.databinding.beans.BeanPropertyHelper.readProperty(BeanPropertyHelper.java:94)
	at org.eclipse.core.internal.databinding.beans.BeanValueProperty.doGetValue(BeanValueProperty.java:47)
	at org.eclipse.core.databinding.property.value.ValueProperty.getValue(ValueProperty.java:57)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue$3.run(SimplePropertyObservableValue.java:80)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:148)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:152)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:170)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue.firstListenerAdded(SimplePropertyObservableValue.java:78)
	at org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.addValueChangeListener(AbstractObservableValue.java:46)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.firstListenerAdded(DecoratingObservableValue.java:71)
	at org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.addValueChangeListener(DecoratingObservableValue.java:44)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.firstListenerAdded(DecoratingObservableValue.java:71)
	at org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.addValueChangeListener(DecoratingObservableValue.java:44)
	at org.eclipse.core.databinding.ValueBinding.<init>(ValueBinding.java:79)
	at org.eclipse.core.databinding.DataBindingContext.bindValue(DataBindingContext.java:164)
	at org.eclipse.core.databinding.DataBindingContext.bindValue(DataBindingContext.java:130)
	at uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupPanel.setModel(RBLookupPanel.java:97)
	at uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupDialog.setModel(RBLookupDialog.java:76)
	at uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupDialog.create(RBLookupDialog.java:67)
	at org.eclipse.jface.window.Window.open(Window.java:790)
	at uk.ac.stfc.isis.ibex.ui.experimentdetails.ExperimentDetailsPanel$1.widgetSelected(ExperimentDetailsPanel.java:93)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at uk.ac.stfc.isis.ibex.product.Application.start(Application.java:40)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
*2017-01-06 16:07:41.612 [main] ERROR org.eclipse.core.databinding - nameSearch property does not have a read method.
	org.eclipse.core.internal.databinding.beans.BeanPropertyHelper.readProperty(BeanPropertyHelper.java:94)
	org.eclipse.core.internal.databinding.beans.BeanValueProperty.doGetValue(BeanValueProperty.java:47)
	org.eclipse.core.databinding.property.value.ValueProperty.getValue(ValueProperty.java:57)
	org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue$3.run(SimplePropertyObservableValue.java:80)
	org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:148)
	org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:152)
	org.eclipse.core.databinding.observable.Realm.exec(Realm.java:170)
	org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue.firstListenerAdded(SimplePropertyObservableValue.java:78)
	org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	org.eclipse.core.databinding.observable.value.AbstractObservableValue.addValueChangeListener(AbstractObservableValue.java:46)
	org.eclipse.core.databinding.observable.value.DecoratingObservableValue.firstListenerAdded(DecoratingObservableValue.java:71)
	org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	org.eclipse.core.databinding.observable.value.DecoratingObservableValue.addValueChangeListener(DecoratingObservableValue.java:44)
	org.eclipse.core.databinding.observable.value.DecoratingObservableValue.firstListenerAdded(DecoratingObservableValue.java:71)
	org.eclipse.core.databinding.observable.ChangeManager.addListener(ChangeManager.java:70)
	org.eclipse.core.databinding.observable.value.DecoratingObservableValue.addValueChangeListener(DecoratingObservableValue.java:44)
	org.eclipse.core.databinding.ValueBinding.<init>(ValueBinding.java:79)
	org.eclipse.core.databinding.DataBindingContext.bindValue(DataBindingContext.java:164)
	org.eclipse.core.databinding.DataBindingContext.bindValue(DataBindingContext.java:130)
	uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupPanel.setModel(RBLookupPanel.java:97)
	uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupDialog.setModel(RBLookupDialog.java:76)
	uk.ac.stfc.isis.ibex.ui.experimentdetails.rblookup.RBLookupDialog.create(RBLookupDialog.java:67)
	org.eclipse.jface.window.Window.open(Window.java:790)
	uk.ac.stfc.isis.ibex.ui.experimentdetails.ExperimentDetailsPanel$1.widgetSelected(ExperimentDetailsPanel.java:93)
	org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	uk.ac.stfc.isis.ibex.product.Application.start(Application.java:40)
	org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

**Comment by KathrynBaker** [comment]
The method of acquiring this data has changed since this was created, closing
