### ISSUE TITLE
JMS Shutdown error

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#1962]
Sometimes when closing the GUI I get the following exception:
```
Jan 10, 2017 1:38:03 PM org.csstudio.alarm.beast.JMSCommunicationThread disconnect
WARNING: JMS shutdown error
java.lang.NullPointerException
	at org.csstudio.alarm.beast.ui.clientmodel.AlarmClientCommunicator.closeProducersAndConsumers(AlarmClientCommunicator.java:182)
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:277)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)

Exception in thread "JMS Communicator" java.lang.NullPointerException
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:285)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)

!ENTRY org.eclipse.core.jobs 2 Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: uk.ac.stfc.isis.ibex.log.LogModel$1
2 2017-01-10 13:38:04.207
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: uk.ac.stfc.isis.ibex.log.LogModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-01-10 13:38:04.208
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob

!ENTRY org.eclipse.core.jobs 2 2 2017-01-10 13:38:04.209
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
```

Steps to reproduce:
- Open the GUI pointing at local instrument.
- Close the GUI. Approximately half the time this exception will be generated.

Potentially a similar problem to #1806 ??

**Comment by Tom-Willemsen** [comment]
Sometimes when closing the GUI I get the following exception:
```
Jan 10, 2017 1:38:03 PM org.csstudio.alarm.beast.JMSCommunicationThread disconnect
WARNING: JMS shutdown error
java.lang.NullPointerException
	at org.csstudio.alarm.beast.ui.clientmodel.AlarmClientCommunicator.closeProducersAndConsumers(AlarmClientCommunicator.java:182)
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:277)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)

Exception in thread "JMS Communicator" java.lang.NullPointerException
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:285)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)

!ENTRY org.eclipse.core.jobs 2 Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: uk.ac.stfc.isis.ibex.log.LogModel$1
2 2017-01-10 13:38:04.207
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: uk.ac.stfc.isis.ibex.log.LogModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-01-10 13:38:04.208
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob

!ENTRY org.eclipse.core.jobs 2 2 2017-01-10 13:38:04.209
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
```

Steps to reproduce:
- Open the GUI pointing at local instrument.
- Close the GUI. Approximately half the time this exception will be generated.

**Comment by Tom-Willemsen** [comment]
This also happens occasionally when starting the GUI or when switching instrument

**Comment by Tom-Willemsen** [comment]
Not seen recently. Re-open/recreate new issue if it recurs.
