### ISSUE TITLE
GUI: DAE perspective crashing if the DAE is not running

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2023]
If the DAE is not running then the DAE perspective crashes with the following:

```
java.lang.NullPointerException
	at uk.ac.stfc.isis.ibex.ui.dae.experimentsetup.periods.PeriodsViewModel.getPeriodType(PeriodsViewModel.java:132)
	at uk.ac.stfc.isis.ibex.ui.dae.experimentsetup.periods.PeriodsPanel.setModel(PeriodsPanel.java:327)
	at uk.ac.stfc.isis.ibex.ui.dae.experimentsetup.ExperimentSetup.bind(ExperimentSetup.java:132)
	at uk.ac.stfc.isis.ibex.ui.dae.DaeView.setModel(DaeView.java:94)
	at uk.ac.stfc.isis.ibex.ui.dae.DaeView.createPartControl(DaeView.java:214)
	at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:386)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:240)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
	at org.eclipse.ui.internal.PartPane.setVisible(PartPane.java:315)
	at org.eclipse.ui.internal.ViewPane.setVisible(ViewPane.java:534)
	at org.eclipse.ui.internal.presentations.PresentablePart.setVisible(PresentablePart.java:180)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(PresentablePartFolder.java:270)
	at org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRightTabOrder.java:65)
	at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(TabbedStackPresentation.java:473)
	at org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:1245)
	at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1198)
	at org.eclipse.ui.internal.PartStack.showPart(PartStack.java:1597)
	at org.eclipse.ui.internal.PartStack.createControl(PartStack.java:643)
	at org.eclipse.ui.internal.PartStack.createControl(PartStack.java:570)
	at org.eclipse.ui.internal.PartSashContainer.createControl(PartSashContainer.java:568)
	at org.eclipse.ui.internal.PerspectiveHelper.activate(PerspectiveHelper.java:272)
	at org.eclipse.ui.internal.Perspective.onActivate(Perspective.java:981)
	at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3726)
	at org.eclipse.ui.internal.WorkbenchPage.busySetPerspective(WorkbenchPage.java:1124)
	at org.eclipse.ui.internal.WorkbenchPage.access$16(WorkbenchPage.java:1108)
	at org.eclipse.ui.internal.WorkbenchPage$19.run(WorkbenchPage.java:3827)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3825)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:2875)
	at uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$2.run(PerspectiveSwitcher.java:74)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	at uk.ac.stfc.isis.ibex.ui.PerspectiveSwitcher$3.run(PerspectiveSwitcher.java:86)
	at uk.ac.stfc.isis.ibex.ui.UI$1.run(UI.java:61)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
	at uk.ac.stfc.isis.ibex.ui.UI.switchPerspective(UI.java:54)
	at uk.ac.stfc.isis.ibex.ui.perspectives.switcher.PerspectiveButton$1.mouseDown(PerspectiveButton.java:71)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at uk.ac.stfc.isis.ibex.product.Application.start(Application.java:40)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

**Comment by kjwoodsISIS** [comment]
Actually, this crash is probably caused by ICP not running.

**Comment by Tom-Willemsen** [comment]
Cannot reproduce this with a simulated DAE.

Tried crashing the DAE IOC and the ISISICP but neither of those reproduced the stack trace/behaviour shown above.

Test this on a real DAE which is switched off (out of cycle)
