### ISSUE TITLE
OPIs: Illegal argument exception

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2080]
With the new version of CS-Studio, we get exceptions from some OPIs if we don't set macros.

The following exception is from a Lakeshore 218 (no macros set):

```
Feb 15, 2017 10:20:53 AM org.csstudio.opibuilder.util.ErrorHandlerUtil handleError
WARNING: Error from pv connection layer: 
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
	at org.epics.pvmanager.util.FunctionParser.parseFunctionWithScalarOrArrayArguments(FunctionParser.java:48)
	at org.epics.pvmanager.loc.LocalDataSource.parseName(LocalDataSource.java:68)
	at org.epics.pvmanager.loc.LocalDataSource.channelHandlerLookupName(LocalDataSource.java:88)
	at org.epics.pvmanager.DataSource.channel(DataSource.java:66)
	at org.epics.pvmanager.DataSource.disconnectRead(DataSource.java:207)
	at org.epics.pvmanager.CompositeDataSource.disconnectRead(CompositeDataSource.java:174)
	at org.epics.pvmanager.PVDirector.disconnectReadExpression(PVDirector.java:177)
	at org.epics.pvmanager.PVDirector.disconnect(PVDirector.java:198)
	at org.epics.pvmanager.PVDirector.close(PVDirector.java:188)
	at org.epics.pvmanager.PVReaderImpl.close(PVReaderImpl.java:241)
	at org.csstudio.simplepv.pvmanager.PVManagerPV.stop(PVManagerPV.java:383)
	at org.csstudio.opibuilder.editparts.PVWidgetEditpartDelegate.doDeActivate(PVWidgetEditpartDelegate.java:201)
	at org.csstudio.opibuilder.editparts.AbstractPVWidgetEditPart.doDeActivate(AbstractPVWidgetEditPart.java:71)
	at org.csstudio.opibuilder.editparts.AbstractBaseEditPart.deactivate(AbstractBaseEditPart.java:292)
	at org.eclipse.gef.editparts.AbstractEditPart.deactivate(AbstractEditPart.java:293)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.deactivate(AbstractGraphicalEditPart.java:354)
	at org.csstudio.opibuilder.editparts.AbstractBaseEditPart.deactivate(AbstractBaseEditPart.java:293)
	at org.csstudio.opibuilder.editparts.AbstractContainerEditpart.deactivate(AbstractContainerEditpart.java:288)
	at org.eclipse.gef.editparts.AbstractEditPart.deactivate(AbstractEditPart.java:293)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.deactivate(AbstractGraphicalEditPart.java:354)
	at org.csstudio.opibuilder.editparts.AbstractBaseEditPart.deactivate(AbstractBaseEditPart.java:293)
	at org.csstudio.opibuilder.editparts.AbstractContainerEditpart.deactivate(AbstractContainerEditpart.java:288)
	at org.csstudio.opibuilder.editparts.DisplayEditpart.deactivate(DisplayEditpart.java:180)
	at org.eclipse.gef.editparts.AbstractEditPart.deactivate(AbstractEditPart.java:293)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.deactivate(AbstractGraphicalEditPart.java:354)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.unhookControl(AbstractEditPartViewer.java:768)
	at org.eclipse.gef.ui.parts.GraphicalViewerImpl.unhookControl(GraphicalViewerImpl.java:432)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setControl(AbstractEditPartViewer.java:634)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.handleDispose(AbstractEditPartViewer.java:222)
	at org.eclipse.gef.ui.parts.GraphicalViewerImpl.handleDispose(GraphicalViewerImpl.java:109)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer$2.widgetDisposed(AbstractEditPartViewer.java:436)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1077)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1058)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:808)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:873)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:811)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:873)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:446)
	at org.eclipse.ui.internal.PartPane.dispose(PartPane.java:182)
	at org.eclipse.ui.internal.ViewPane.dispose(ViewPane.java:204)
	at org.eclipse.ui.internal.WorkbenchPartReference.dispose(WorkbenchPartReference.java:681)
	at org.eclipse.ui.internal.WorkbenchPage.disposePart(WorkbenchPage.java:1810)
	at org.eclipse.ui.internal.WorkbenchPage.partRemoved(WorkbenchPage.java:1802)
	at org.eclipse.ui.internal.ViewFactory.releaseView(ViewFactory.java:257)
	at org.eclipse.ui.internal.Perspective.hideView(Perspective.java:606)
	at org.eclipse.ui.internal.WorkbenchPage.hideView(WorkbenchPage.java:2482)
	at org.eclipse.ui.internal.WorkbenchPage.hideView(WorkbenchPage.java:2496)
	at uk.ac.stfc.isis.ibex.ui.targets.OpiTargetView$1.run(OpiTargetView.java:133)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4144)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at uk.ac.stfc.isis.ibex.product.Application.start(Application.java:40)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

```

In the GUI, this will show up in the BOY console as:

```
...
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
2017-02-15 10:20:31 ERROR: Error from pv connection layer: 
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
2017-02-15 10:20:31 ERROR: Error from pv connection layer: 
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
2017-02-15 10:20:31 ERROR: Error from pv connection layer: 
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
2017-02-15 10:20:31 ERROR: Error from pv connection layer: 
java.lang.IllegalArgumentException: Syntax for local channel must be either name, name(Double) or name(String) (e.g "foo", "foo(2.0)" or "foo("bar")
2017-02-15 10:20:31 ERROR: Error from pv connection layer: 
...
```

This is not user friendly. This exception should be caught and a more helpful error message given.

**Comment by Tom-Willemsen** [comment]
boy console was disabled some time ago, so substantive part of this issue is complete
