### ISSUE TITLE
Synoptics: SAX parse exception

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2090]
This was seen on vesuvio, at the same time as #2089 

![image](https://cloud.githubusercontent.com/assets/24375813/23030002/49e94bc2-f464-11e6-9adf-22a6498a4486.png)

This might be an issue with the GUI being started when the instrument hasn't been fully initialized...?

The issue occured when trying to save a new synoptic. Existing synoptics hadn't loaded properly, which is probably related.

**Comment by mattclarke** [comment]
It would be nice to get to the root of the following message which sometimes occurs on start up:

```
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at com.sun.org.apache.xerces.internal.jaxp.validation.Util.toSAXException(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at javax.xml.validation.SchemaFactory.newSchema(Unknown Source)
	at uk.ac.stfc.isis.ibex.synoptic.xml.XMLUtil.setSchema(XMLUtil.java:104)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:68)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVReaderDirector$1.run(PVReaderDirector.java:309)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVReaderDirector.notifyPv(PVReaderDirector.java:280)
	at org.epics.pvmanager.PVReaderDirector$2.run(PVReaderDirector.java:335)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Feb 17, 2017 12:03:06 PM org.csstudio.alarm.beast.ui.clientmodel.AlarmClientModel readConfiguration
```

**Comment by AdrianPotter** [comment]
This issue has been reproduced locally and flagged by the automated system tests
