### ISSUE TITLE
PV reader garbage collected before being closed

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2131]
### Description

Once #2017 is merged, there will be occasional stack traces in the console log (see below).

These don't affect any functionality from a user's perspective, but as developers, it would be nice to eliminate these.

The previous solution to this problem was to keep references to all the PV readers in a big `List`, which used a lot of memory when many configurations had been edited. This ticket should find a way of tracking all the PV readers which are in use and closing them appropriately when they're finished with, then eliminating all references to them so that they can be garbage collected.

While doing this ticket it is important to ensure that there is no regression of issue #2017 (check using the java visual VM: further instructions [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Debugging-memory-leaks-in-the-IBEX-GUI))

Note that these exceptions only occur once in a while, not consistently, so this will require a good amount of time to test and fix.

### Acceptance criteria
- [ ] There are never any of the stack traces shown below
- [ ] There is no regression of the issue seen in #2017 (check using java visual VM that memory usage is stable when adding/deleting at least 30 blank configurations)

### Stack trace showing problem

```
Feb 21, 2017 11:17:22 AM org.epics.pvmanager.PVDirector isActive
WARNING: PVReader wasn't properly closed and it was garbage collected. Closing the associated connections...
java.lang.Exception: PV was never closed (stack trace for creation)
	at org.epics.pvmanager.PVDirector.<init>(PVDirector.java:52)
	at org.epics.pvmanager.PVReaderConfiguration.prepareDirector(PVReaderConfiguration.java:140)
	at org.epics.pvmanager.PVReaderConfiguration.maxRate(PVReaderConfiguration.java:128)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.<init>(PVManagerObservable.java:73)
	at uk.ac.stfc.isis.ibex.epics.pv.Channels.convertObservablePV(Channels.java:205)
	at uk.ac.stfc.isis.ibex.epics.pv.Channels.access$0(Channels.java:204)
	at uk.ac.stfc.isis.ibex.epics.pv.Channels$Strings.reader(Channels.java:75)
	at uk.ac.stfc.isis.ibex.instrument.channels.StringChannel.reader(StringChannel.java:29)
	at uk.ac.stfc.isis.ibex.epics.switching.ObservableFactory.getPVObservable(ObservableFactory.java:93)
	at uk.ac.stfc.isis.ibex.epics.switching.ObservableFactory.getForwardingObservable(ObservableFactory.java:88)
	at uk.ac.stfc.isis.ibex.configserver.ConfigServerVariables.iocDescription(ConfigServerVariables.java:222)
	at uk.ac.stfc.isis.ibex.configserver.ConfigServer.iocDescription(ConfigServer.java:167)
	at uk.ac.stfc.isis.ibex.configserver.editing.ObservableEditableConfiguration.getDescription(ObservableEditableConfiguration.java:69)
	at uk.ac.stfc.isis.ibex.configserver.editing.EditableConfiguration.setIocDescriptions(EditableConfiguration.java:615)
	at uk.ac.stfc.isis.ibex.configserver.editing.EditableConfiguration.<init>(EditableConfiguration.java:178)
	at uk.ac.stfc.isis.ibex.configserver.editing.ObservableEditableConfiguration.transform(ObservableEditableConfiguration.java:59)
	at uk.ac.stfc.isis.ibex.configserver.editing.ObservableEditableConfiguration.transform(ObservableEditableConfiguration.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:37)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:36)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:36)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by AdrianPotter** [comment]
The change that caused this issue has been removed
