### ISSUE TITLE
Circular definitions detected for synoptic components

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2142]
Very infrequently I get the following error in the GUI as it starts up:

Looks like the schema is incorrect... `A schema cannot contain two global components with the same name` looks very suspicious!

```
org.xml.sax.SAXParseException; lineNumber: 28; columnNumber: 84; ct-props-correct.3: Circular definitions detected for complex type 'tns:components'. This means that 'tns:components' is contained in its own type hierarchy, which is an error.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseLocal(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseLocalElements(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at javax.xml.validation.SchemaFactory.newSchema(Unknown Source)
	at uk.ac.stfc.isis.ibex.synoptic.xml.XMLUtil.setSchema(XMLUtil.java:104)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:68)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
org.xml.sax.SAXParseException; lineNumber: 28; columnNumber: 84; sch-props-correct.2: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'http://www.isis.stfc.ac.uk//instrument,instrument'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.checkForDuplicateNames(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.buildGlobalNameRegistries(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at javax.xml.validation.SchemaFactory.newSchema(Unknown Source)
	at uk.ac.stfc.isis.ibex.synoptic.xml.XMLUtil.setSchema(XMLUtil.java:104)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:68)
	at uk.ac.stfc.isis.ibex.synoptic.ObservingSynopticModel$2.onValue(ObservingSynopticModel.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
Mar 01, 2017 11:45:11 AM org.csstudio.alarm.beast.ui.clientmodel.AlarmClientModel readConfiguration
INFO: Read 116 alarm tree items, 101 PVs in 0.21 seconds: 543.4 items/sec, 473.1 PVs/sec

	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by KathrynBaker** [comment]
This may not be fixed but it has shown limited issues in the last 7 years, we can reopen or create a new ticket should we find this is still occurring.
