### ISSUE TITLE
xpath expression exception in DAE

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2160]
This was seen in the eclipse console when starting my Instrument and GUI at similar times.

I think it might be because the DAE wasn't fully initialized...?

```
java.lang.NullPointerException
	at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getLocalName(Unknown Source)
	at com.sun.org.apache.xpath.internal.patterns.NodeTest.execute(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.acceptNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.AxesWalker.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.WalkingIterator.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.runTo(Unknown Source)
	at com.sun.org.apache.xml.internal.dtm.ref.DTMNodeList.<init>(Unknown Source)
	at com.sun.org.apache.xpath.internal.objects.XNodeSet.nodelist(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.getResultAsType(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(Unknown Source)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.getNode(XmlBackedDaeSettings.java:375)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.updateNodes(XmlBackedDaeSettings.java:319)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.setXml(XmlBackedDaeSettings.java:94)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.ObservingDaeSettings$1.setFromText(ObservingDaeSettings.java:36)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:35)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: java.lang.NullPointerException
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(Unknown Source)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.getNode(XmlBackedDaeSettings.java:375)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.updateNodes(XmlBackedDaeSettings.java:319)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.setXml(XmlBackedDaeSettings.java:94)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.ObservingDaeSettings$1.setFromText(ObservingDaeSettings.java:36)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:35)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getLocalName(Unknown Source)
	at com.sun.org.apache.xpath.internal.patterns.NodeTest.execute(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.acceptNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.AxesWalker.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.WalkingIterator.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.runTo(Unknown Source)
	at com.sun.org.apache.xml.internal.dtm.ref.DTMNodeList.<init>(Unknown Source)
	at com.sun.org.apache.xpath.internal.objects.XNodeSet.nodelist(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.getResultAsType(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(Unknown Source)
	... 32 more
java.lang.NullPointerException
	at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getLocalName(Unknown Source)
	at com.sun.org.apache.xpath.internal.patterns.NodeTest.execute(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.acceptNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.AxesWalker.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.WalkingIterator.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.runTo(Unknown Source)
	at com.sun.org.apache.xml.internal.dtm.ref.DTMNodeList.<init>(Unknown Source)
	at com.sun.org.apache.xpath.internal.objects.XNodeSet.nodelist(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.getResultAsType(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(Unknown Source)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.getNode(XmlBackedDaeSettings.java:375)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.updateNodes(XmlBackedDaeSettings.java:319)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.setXml(XmlBackedDaeSettings.java:94)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.ObservingDaeSettings$1.setFromText(ObservingDaeSettings.java:36)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:35)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: java.lang.NullPointerException
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(Unknown Source)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.getNode(XmlBackedDaeSettings.java:375)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.updateNodes(XmlBackedDaeSettings.java:319)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.XmlBackedDaeSettings.setXml(XmlBackedDaeSettings.java:94)
	at uk.ac.stfc.isis.ibex.dae.dataacquisition.ObservingDaeSettings$1.setFromText(ObservingDaeSettings.java:36)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:35)
	at uk.ac.stfc.isis.ibex.dae.internal.SettingsGateway$1.onValue(SettingsGateway.java:1)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.ForwardingObservable$1.onValue(ForwardingObservable.java:34)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.observing.TransformingObservable$1.onValue(TransformingObservable.java:38)
	at uk.ac.stfc.isis.ibex.epics.observing.ClosableObservable.setValue(ClosableObservable.java:83)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable.access$3(PVManagerObservable.java:1)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.PVManagerObservable$1.pvChanged(PVManagerObservable.java:61)
	at org.epics.pvmanager.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.epics.pvmanager.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.epics.pvmanager.PVDirector$4.run(PVDirector.java:340)
	at uk.ac.stfc.isis.ibex.epics.pvmanager.CurrentThreadExecutor.execute(CurrentThreadExecutor.java:26)
	at org.epics.pvmanager.PVDirector.notifyPv(PVDirector.java:311)
	at org.epics.pvmanager.PVDirector.access$500(PVDirector.java:37)
	at org.epics.pvmanager.PVDirector$6.desiredRateEvent(PVDirector.java:385)
	at org.epics.pvmanager.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:160)
	at org.epics.pvmanager.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getLocalName(Unknown Source)
	at com.sun.org.apache.xpath.internal.patterns.NodeTest.execute(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.acceptNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.AxesWalker.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.WalkingIterator.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.nextNode(Unknown Source)
	at com.sun.org.apache.xpath.internal.axes.NodeSequence.runTo(Unknown Source)
	at com.sun.org.apache.xml.internal.dtm.ref.DTMNodeList.<init>(Unknown Source)
	at com.sun.org.apache.xpath.internal.objects.XNodeSet.nodelist(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.getResultAsType(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(Unknown Source)
	... 30 more
```

**Comment by Tom-Willemsen** [comment]
Not seen this one recently. Create new issue if it recurs.
