### ISSUE TITLE
GUI: Exception on exit

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2243]
The GUI is emitting the following exception consistently on exit:

```
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob
Exception in thread "JMS Communicator" java.lang.NullPointerException
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:285)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "JMS Communicator" java.lang.NullPointerException
	at org.csstudio.alarm.beast.JMSCommunicationThread.disconnect(JMSCommunicationThread.java:285)
	at org.csstudio.alarm.beast.JMSCommunicationThread.thread_run(JMSCommunicationThread.java:212)
	at org.csstudio.alarm.beast.JMSCommunicationThread.access$0(JMSCommunicationThread.java:184)
	at org.csstudio.alarm.beast.JMSCommunicationThread$1.run(JMSCommunicationThread.java:67)
	at java.lang.Thread.run(Unknown Source)
```

Notably my server isn't currently running.

**Comment by GRyall** [comment]
This has not been reported since and sufficient development has been done that this bug report is stale. If the issue reoccurs we can reopen the ticket.
