### ISSUE TITLE
DbUnitChecker: handle malformed input better 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2561]
It would be useful to know what "text" was
```
Traceback (most recent call last):
  File "db_checker.py", line 333, in <module>
    set_up(args.input_dir)
  File "db_checker.py", line 308, in set_up
    dbs = dbs.parse_files()
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\loader.py", line 69, in parse_files
    return [parse_db(db) for db in self.dbs]
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 79, in parse_db
    fields = _get_props("field", field_text)
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 37, in _get_props
    val = _check_string(text)
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 16, in _check_string
    return re.split('[,)]', text)[1]
IndexError: list index out of range
ERROR: Tests failed DbUnitChecker\master\run_tests.py
```

**Comment by Tom-Willemsen** [comment]
I was able to reproduce this with a record of the form:

```
record(bi, "$(P)SOMETHING")
{
    field(VAL
}
```

In this case, the error message (with the modifications in this ticket) is
```
Traceback (most recent call last):
  File "db_checker.py", line 333, in <module>
    set_up(args.input_dir)
  File "db_checker.py", line 308, in set_up
    dbs = dbs.parse_files()
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\loader.py", line 69, in parse_files
    return [parse_db(db) for db in self.dbs]
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 82, in parse_db
    fields = _get_props("field", field_text)
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 40, in _get_props
    val = _check_string(text)
  File "C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\db_parser.py", line 18, in _check_string
    raise ValueError("Cannot parse " + text)
ValueError: Cannot parse d(VAL
```
which still isn't terribly useful - many, many records have a VAL field so the information provided doesn't really help me at all.

Could you:
- Add this test case to the existing test cases in `C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\test`.
- Try to make the error message a bit more useful, as it stands I still wouldn't be able to debug this issue. You could see if it's possible to print the record name and name of the DB file where this error occurred.

**Comment by FreddieAkeroyd** [comment]
Thanks - your additional changes merged, also added in a print of duplicate field names
