### ISSUE TITLE
Archive engine fails if block name is too long

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2773]
As an ibex user, I would like the ibex system to alert me if my block name is too long or otherwise invalid.

Currently we allow arbitrarily long block names but the archive engine falls over if the block is beyond a certain length (~100 characters).

This ticket should:
- Document what "allowable" block names are in terms of what all of our system components can handle
- Implement that limit in the GUI so that a user is alerted if their block name is not valid

From ARBLOCK logs (code around these locations might help to see where a limit is defined):

```
[2017-11-13 12:02:12] 2017-11-13 12:02:12.402 WARNING [Thread 29] org.csstudio.archive.engine.server.Servlet (doGet) - HTTP Server exception
[2017-11-13 12:02:12] java.lang.IllegalStateException: STREAM

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.Response.getWriter(Response.java:693)

[2017-11-13 12:02:12] 	at org.csstudio.archive.engine.server.json.JSONRoot.<init>(JSONRoot.java:29)

[2017-11-13 12:02:12] 	at org.csstudio.archive.engine.server.json.JSONGroupResponse.fillResponse(JSONGroupResponse.java:35)

[2017-11-13 12:02:12] 	at org.csstudio.archive.engine.server.Servlet.doGet(Servlet.java:60)

[2017-11-13 12:02:12] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)

[2017-11-13 12:02:12] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)

[2017-11-13 12:02:12] 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)

[2017-11-13 12:02:12] 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)

[2017-11-13 12:02:12] 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)

[2017-11-13 12:02:12] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)

[2017-11-13 12:02:12] 	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:360)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.Server.handle(Server.java:370)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

[2017-11-13 12:02:12] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

[2017-11-13 12:02:12] 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by FreddieAkeroyd** [comment]
Interesting limit - for DBs it is 60, but this is a gateway alias and so doesn't necessarily follow that rule. There is supposed to be no limit within channel access itself, so is this an issue in caj, the archive engine, or the gateway? Can you still caget and display in IBEX, but it is just the archive engine that objects?

**Comment by KathrynBaker** [comment]
Block names are limited in length, so we are not hitting this issue, and the archiver is likely to be changed in the next few years, this ticket feels redundant.
