### ISSUE TITLE
Genie_python: Scipy does not work

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2932]
A Larmor instrument scientist can not run:

    from scipy.optimize import curve_fit

It fails with:

```
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-0a5ca04133a7>", line 1, in <module>
    from scipy.optimize import curve_fit
  File "C:\Instrument\Apps\Client\plugins\org.python.pydev_4.5.1.201601132212\pysrc\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Instrument\Apps\Python\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy._distributor_init import NUMPY_MKL  # requires numpy+mkl
ImportError: cannot import name NUMPY_MKL
```

Fix this and write a test. Make sure it works from python 3

**Comment by John-Holt-Tessella** [comment]
I have temporarily fixed this by getting Rob to run `C:\Instrument\Apps\Python\python C:\Instrument\Apps\Python\Scripts\pip.exe install ...\CompGroup\ICP\genie_python_dependencies\numpy-1.13.3+mkl-cp27-cp27m-win_amd64.whl` after copying the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy 

Document this.
