### ISSUE TITLE
BLOCKSRV: Git can stop working within the block server

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3093]
Git fell over with:

```
[Sat Apr  7 06:16:09 2018] Exception in thread Thread-5:

[Sat Apr  7 06:16:09 2018] Traceback (most recent call last):

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\Python\lib\threading.py", line 801, in __bootstrap_inner

[Sat Apr  7 06:16:09 2018]     self.run()

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\Python\lib\threading.py", line 754, in run

[Sat Apr  7 06:16:09 2018]     self.__target(*self.__args, **self.__kwargs)

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\ConfigVersionControl\git_version_control.py", line 134, in _commit_and_push

[Sat Apr  7 06:16:09 2018]     self._add_all_files()

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\ConfigVersionControl\git_version_control.py", line 157, in _add_all_files

[Sat Apr  7 06:16:09 2018]     self.repo.git.add(A=True)

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\Python\lib\site-packages\git\cmd.py", line 425, in <lambda>

[Sat Apr  7 06:16:09 2018]     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\Python\lib\site-packages\git\cmd.py", line 877, in _call_process

[Sat Apr  7 06:16:09 2018]     return self.execute(call, **exec_kwargs)

[Sat Apr  7 06:16:09 2018]   File "C:\Instrument\Apps\Python\lib\site-packages\git\cmd.py", line 602, in execute

[Sat Apr  7 06:16:09 2018]     raise GitCommandNotFound(command, err)

[Sat Apr  7 06:16:09 2018] GitCommandNotFound: Cmd('git') not found due to: WindowsError('[Error 1455] The paging file is too small for this operation to complete')

[Sat Apr  7 06:16:09 2018]   cmdline: git add -A
```

This should not bring down the git part of the block server.

I made a change which should have been committed but it was not. All exceptions in this part of the code should be caught and logged.

**Comment by KathrynBaker** [comment]
If this is still an issue then we can re-open this ticket or create a new one, but a lot of time has passed since this ticket was created.
