### ISSUE TITLE
E4: HVCAEN OPI: channel maintenance does not work

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3333]
As a user of the HVCAEN IOC, I would like the OPI in eclipse 4 to maintain the same level of functionality as eclipse 3.

**Acceptance criteria**
- The HVCAEN OPI works similarly (from a user's perspective) in eclipse 4 and eclipse 3.

**Notes**
- The following exception is thrown in the E4 gui

```
!ENTRY org.eclipse.ui 4 0 2018-07-05 18:12:45.367
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.ArrayIndexOutOfBoundsException: 0)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at uk.ac.stfc.isis.ibex.e4.product.Application.start(Application.java:40)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.csstudio.simplepv.VTypeHelper.formatObjectArray(VTypeHelper.java:431)
	at org.csstudio.simplepv.VTypeHelper.formatValue(VTypeHelper.java:94)
	at org.csstudio.opibuilder.widgets.editparts.TextUpdateEditPart.formatValue(TextUpdateEditPart.java:370)
	at org.csstudio.opibuilder.widgets.editparts.TextUpdateEditPart$8.handleChange(TextUpdateEditPart.java:245)
	at org.csstudio.opibuilder.properties.WidgetPropertyChangeListener$1.run(WidgetPropertyChangeListener.java:55)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 24 more
*2018-07-05 18:12:45.368 [main] ERROR org.eclipse.ui.workbench - Failed to execute runnable (java.lang.ArrayIndexOutOfBoundsException: 0)
	org.eclipse.swt.SWT.error(SWT.java:4533)
	org.eclipse.swt.SWT.error(SWT.java:4448)
	org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	uk.ac.stfc.isis.ibex.e4.product.Application.start(Application.java:40)
	org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	org.eclipse.equinox.launcher.Main.main(Main.java:1492)

```

**Comment by RichardTysonIsis** [comment]
This stack trace wasn't reproducible.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/743
