### ISSUE TITLE
Genie: load script in folder in scripts

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3974]
As a SANDLAS instrument scientist I would like to load a script within a subfolder in scripts without specifying the full path. i.e. 

```
g.load(cycle18_4/sample_changer_calibration_loop.py)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-1eeff8b27310>", line 1, in <module>
    g.load(cycle18_4/sample_changer_calibration_loop.py)
NameError: name 'cycle18_4' is not defined
g.load(cycle18_4/sample_changer_calibration_loop.py)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-1eeff8b27310>", line 1, in <module>
    g.load(cycle18_4/sample_changer_calibration_loop.py)
NameError: name 'cycle18_4' is not defined
g.load(C:\scripts\cycle18_4\sample_changer_calibration_loop.py)
  File "<ipython-input-10-89a77640dd3b>", line 1
    g.load(C:\scripts\cycle18_4\sample_changer_calibration_loop.py)
            ^
SyntaxError: invalid syntax

g.load(C:/scripts/cycle18_4/sample_changer_calibration_loop.py)
  File "<ipython-input-11-6c57f453764f>", line 1
    g.load(C:/scripts/cycle18_4/sample_changer_calibration_loop.py)
            ^
SyntaxError: invalid syntax

g.load(.\cycle18_4\sample_changer_calibration_loop.py)
  File "<ipython-input-12-2c979dc0dc02>", line 1
    g.load(.\cycle18_4\sample_changer_calibration_loop.py)
           ^
SyntaxError: invalid syntax

g.load("cycle18_4\sample_changer_calibration_loop.py")
This function does not load a script; you probably wanted g.load_script("cycle18_4/sample_changer_calibration_loop.py").If you wanted numpy load please call it directly with import numpy as numpy; numpy.load("cycle18_4/sample_changer_calibration_loop.py")
g.load_script("cycle18_4\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
g.load_script(".\cycle18_4\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (./cycle18_4/sample_changer_calibration_loop.py)
g.load_script("cycle18_4\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
reload(sandals)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-74a92acf54b8>", line 1, in <module>
    reload(sandals)
NameError: name 'sandals' is not defined
g.load_script("templates\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (templates/sample_changer_calibration_loop.py)
g.load_script("templates\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (templates/sample_changer_calibration_loop.py)
g.load_script("cycle18_4\sample_changer_calibration_loop.py)
  File "<ipython-input-20-575038a61b2d>", line 1
    g.load_script("cycle18_4\sample_changer_calibration_loop.py)
                                                               ^
SyntaxError: EOL while scanning string literal

g.load_script("cycle18_4\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
g.load_script("cycle18_4/sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
g.load_script("cycle18_4//sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
g.load_script(""C:\scripts\cycle18_4\sample_changer_calibration_loop.py")
  File "<ipython-input-24-c96e0181bf52>", line 1
    g.load_script(""C:\scripts\cycle18_4\sample_changer_calibration_loop.py")
                    ^
SyntaxError: invalid syntax

g.load_script("C:\scripts\cycle18_4\sample_changer_calibration_loop.py")
Loaded the following script(s): sample_changer_calibration_loop
From: C:\scripts\cycle18_4\sample_changer_calibration_loop.py
File last modified: 2019-02-04 10:48:12
g.load_script("cycle18_4\sample_changer_calibration_loop.py")
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1208, in load_script
    raise Exception("Script file was not found (%s)" % get_correct_path(name))
Exception: Script file was not found (cycle18_4/sample_changer_calibration_loop.py)
reload(inst)
Out[27]: <module 'inst' from 'C:\Instrument\Settings\config\NDXSANDALS\Python\inst\__init__.pyc'>
g.load_script("C:\scripts\cycle18_4\sample_changer_calibration_loop.py")
Loaded the following script(s): sample_changer_calibration_loop
From: C:\scripts\cycle18_4\sample_changer_calibration_loop.py
File last modified: 2019-02-04 10:48:12
```

**Comment by kjwoodsISIS** [comment]
How many points?
