### ISSUE TITLE
g.cset(block=value) broken

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4152]
As a user I need the `g.cset(blockname=value)` syntax to work.

As of https://github.com/ISISComputingGroup/genie_python/pull/153/files , attempting to set a block using the keyword argument syntax fails with the following stack trace:

```
g.cset(a=4)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 2144, in check_alarms
    return __api.check_alarms(blocks)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 553, in check_alarms
    alarm_states = self._get_fields_from_blocks(blocks, "SEVR", "alarm state")
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 575, in _get_fields_from_blocks
    if self.block_exists(b):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 318, in block_exists
    if name.lower() in blks:
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 174, in cset
    _warn_if_block_alarm(block)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 281, in _warn_if_block_alarm
    minor, major, invalid = check_alarms(block)
TypeError: 'NoneType' object is not iterable
```

Trying the same `cset` command with the `g.cset("blockname", value)` syntax works as expected:

```
g.cset("a", 10)
g.cget("a")["value"]
Out[16]: 10.0
```

Note: this was not in last release so is not on any instrument machines yet, however many instruments do use this syntax so this ticket must be done before next release.

**Comment by FreddieAkeroyd** [comment]
I guess we are not testing cset with keyword arguments, or is the test broken?

**Comment by davidkeymer** [comment]
Pull Request: https://github.com/ISISComputingGroup/genie_python/pull/158
