### ISSUE TITLE
Astrium chopper: crashes entirely on comms loss

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4270]
As a user of the astrium choppers, I don't want them to crash entirely when they are disconnected. Instead, I want them to raise a comms alarm.

The stack trace when the IOC crashes is:

```
[2019-04-18 00:33:28] Unhandled Exception: System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

[2019-04-18 00:33:28] 

[2019-04-18 00:33:28] Server stack trace: 

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

[2019-04-18 00:33:28] 

[2019-04-18 00:33:28] Exception rethrown at [0]: 

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

[2019-04-18 00:33:28]    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

[2019-04-18 00:33:28]    at Astrium.RemotingInterface.GetStatus(Int32 chopper)

[2019-04-18 00:33:28]    at AstriumComms.RemotingClient.GetStatus(Int32 chopper)

[2019-04-18 00:33:28]    at AstriumComms.Chopper.GetStatus(Int32 chopper)

[2019-04-18 00:33:28]    at Wrapper.GetStatusProxy(gcroot<Wrapper::IChopper ^>* This, UInt32 channel)

[2019-04-18 00:33:28]    at boost._bi.bind_t<System::String ^,System::String ^ (__clrcall*)(gcroot<Wrapper::IChopper ^>,unsigned int),boost::_bi::list2<boost::_bi::value<gcroot<Wrapper::IChopper ^> >,boost::_bi::value<unsigned int> > >.()(bind_t<System::String ^\,System::String ^ (__clrcall\*)(gcroot<Wrapper::IChopper ^>\,unsigned int)\,boost::_bi::list2<boost::_bi::value<gcroot<Wrapper::IChopper ^> >\,boost::_bi::value<unsigned int> > >* )

[2019-04-18 00:33:28]    at boost.function0<System::String ^>.()(function0<System::String ^>* )

[2019-04-18 00:33:28]    at AstriumBridgeLib.AstriumChopper.sendCommand(function0<System::String ^>* func, SByte* result, Int32 size)

[2019-04-18 00:33:28]    at AstriumBridgeLib.AstriumChopper.GetStatus(UInt32 channel, SByte* result, Int32 size)
```

This then kills the whole IOC. Procserv does restart it successfully but this is not desirable behaviour.

**Comment by FreddieAkeroyd** [comment]
Note: Atrium is due to be replaced in long shutdown,

**Comment by KathrynBaker** [comment]
No longer needed as item not in use
