### ISSUE TITLE
genie_python: begin throws exception if RBNUMBER is unavailable 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4360]
Seen on system tests - the begin command prints out the RB number for info, it looks like if this is not available begin will fail. BEGIN should not fail in these circumstances. 

Acceptance criteria: 
- absence of RB number pv does not cause begin to throw exception and so terminate script

** Beginning Run 00000493 at 04:49:31 19/05/19 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 743, in begin
    __api.dae.begin_run(period, meas_id, meas_type, meas_subid, sample_id, delayed, quiet, paused)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 125, in _wrapper
    return func(self, *args, **kwargs)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 283, in begin_run
    print(("*  Proposal Number: {}".format(self.get_rb_number())))
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 664, in get_rb_number
    return self._get_pv_value(self._get_dae_pv_name("rbnum"))
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 185, in _get_pv_value
    return self.api.get_pv_value(name, to_string)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 264, in get_pv_value
    raise UnableToConnectToPVException(name, 'does not exist')
UnableToConnectToPVException: Unable to connect to PV TE:NDWRENO:ED:RBNUMBER: does not exist

**Comment by FreddieAkeroyd** [comment]
this may be because

        set_genie_python_raises_exceptions(True)

is enabled in the system tests

**Comment by John-Holt-Tessella** [comment]
It is unclear what this should do. Should the exception be handled internally and begin retried, should a message be printed? We should define the behaviour because genie_python does not have a standard way of dealing with these sorts of errors.
