### ISSUE TITLE
Reflectometry: TopHatFail

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4424]
Fix scan:

```
x=0;scan("S4HEIGHT", x-15, x+15, count=21, frames=100, detector=specific_spectra(1,3), fit=TopHat)
** Beginning Run 00103685 at 14:52:47 13/06/19 
*  Proposal Number: 0
*  Experiment Team: 
frame count: 0
Measuring
Waiting for 1.0 seconds 
** Resuming Run 00103685 at 14:53:05 13/06/19 
Waiting for 100 frames 
** Pausing Run 00103685 at 14:53:08 13/06/19 
Waiting for 1.0 seconds 
det/mon: 0.10000000149/7298.10000176
... finished measuring
frame count: 114
Measuring
Waiting for 1.0 seconds 
** Resuming Run 00103685 at 14:53:17 13/06/19 
Waiting for 214 frames 
** Pausing Run 00103685 at 14:53:20 13/06/19 
Waiting for 1.0 seconds 
det/mon: 0.150000002235/7369.30001498
... finished measuring
frame count: 229
Measuring
Waiting for 1.0 seconds 
** Resuming Run 00103685 at 14:53:28 13/06/19 
Waiting for 329 frames 
** Pausing Run 00103685 at 14:53:31 13/06/19 
Waiting for 1.0 seconds 
det/mon: 0.20000000298/7292.19998768
... finished measuring
frame count: 343
Measuring
Waiting for 1.0 seconds 
** Resuming Run 00103685 at 14:53:40 13/06/19 
Waiting for 443 frames 
** Pausing Run 00103685 at 14:53:43 13/06/19 
Waiting for 1.0 seconds 
det/mon: 0.30000000447/7347.25000324
... finished measuring
frame count: 458
Measuring
Waiting for 1.0 seconds 
** Resuming Run 00103685 at 14:53:52 13/06/19 
Waiting for 558 frames 
** Pausing Run 00103685 at 14:53:55 13/06/19 
Waiting for 1.0 seconds 
det/mon: 100.750001747/8641.25000154
... finished measuring
** Aborting Run 00103685 at 14:53:59 13/06/19 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-47-9239b8ac51c9>", line 1, in <module>
    x=0;scan("S4HEIGHT", x-15, x+15, count=21, frames=100, detector=specific_spectra(1,3), fit=TopHat)
  File "C:\Instrument\scripts\general\scans\util.py", line 106, in inner
    return getattr(obj, method)(*args, **kwargs)
  File "C:\Instrument\scripts\general\scans\defaults.py", line 152, in scan
    return scn.fit(**kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 232, in fit
    result = self.plot(action=fit.fit_plot_action(), **kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 196, in plot
    axis, action_remainder)
  File "C:\Instrument\scripts\general\scans\fit.py", line 122, in action
    chi_sq = self.fit_quality(x, values, errs, params)
  File "C:\Instrument\scripts\general\scans\fit.py", line 56, in fit_quality
    return np.mean(((self.get_y(x, params)-y) / err)**2)
  File "C:\Instrument\scripts\general\scans\fit.py", line 290, in get_y
    return self._model(x, *fit)
  File "C:\Instrument\scripts\general\scans\fit.py", line 447, in _model
    ys[np.abs(xs-cen) < width/2] = height
TypeError: only integer scalar arrays can be converted to a scalar index

```

**Comment by ThomasLohnert** [comment]
Fixed https://github.com/ISISComputingGroup/IBEX/issues/5795
