### ISSUE TITLE
GUI: scripting window stops responding on SANDALS

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4450]
Had support call from SANDALS - scripting window hung after load_script issued at around 21:30 Friday 21st. Contents of window as follows: 
```
Waiting for 120.0 seconds 
247.36
** Beginning Run 66449 at 14:39:42 21/06/19 
*  Proposal Number: 1910234
*  Experiment Team: <snip>
Waiting for 250 uamps 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-734af3654798>", line 1, in <module>
    karolina1(250., steps=2)
  File "C:\scripts\cycle19_1\karolina1.py", line 33, in karolina1
    raise KeyboardInterrupt("This is not an error. The script has been manually interrupted. Don't forget to manually end the run if needed.")
KeyboardInterrupt: This is not an error. The script has been manually interrupted. Don't forget to manually end the run if needed.
>>> karolina1(200., steps=3)
>>> karolina1(200., steps=3)
>>> g.load_script("cycle19_1\karolina1.py")


```
python still seemed to still be running in background and was doing I/O. Closed and restarted console window.

**Comment by GRyall** [comment]
Issue resolved at time. No plausible further action for this ticket.
