### ISSUE TITLE
Support: Json bourne appeared to crash

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4544]
Surf stopped updating. Error in log was:

```
019-07-17 16:19:35,167 URL not found or json not understood: http://NDXSURF:4813/group?name=BLOCKS&format=json
2019-07-17 16:19:35,183 Failed to read blocks: No JSON object could be decoded
2019-07-17 16:19:35,198 Failed to get data from instrument: SURF at NDXSURF error was: No JSON object could be decoded - Stack (1 line) Traceback (most recent call last):
  File "C:\JSON_Bourne\external_webpage\instrument_scapper.py", line 74, in run
    temp_data = web_page_scraper.collate()
  File "C:\JSON_Bourne\external_webpage\instrument_information_collator.py", line 217, in collate
    raise e
ValueError: No JSON object could be decoded
:

**Comment by John-Holt-Tessella** [comment]
Restarted

**Comment by GRyall** [comment]
Given the time that has passed, this ticket does not serve a useful purpose.
