### ISSUE TITLE
LARMOR: unable to set dae into simulation mode

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4613]
Reported by Rob: The DAE was switched off, IBEX was started but in "unknow" state, he was unable to set DAE into simulation mode using genie_python but was able to by manually editing icp_config.xml

Check what genie python command to set simulation mode does, it only needs to edit the file but may check the state of other things?

**Comment by Tom-Willemsen** [comment]
The function is set to only work if the DAE status is either `SETUP` (normal DAE on) or `PROCESSING` (the usual state with DAE off). What state was Larmor's DAE in?

**Comment by kjwoodsISIS** [comment]
Perhaps the command should print an error if the DAE is not in the state it expects it to be in?

**Comment by FreddieAkeroyd** [comment]
Rob did not say what state it was in, he had started ibex up and the dae was switched off and he was unable to use the genie python command. We log the runstate pv in the archive so that may tell us. What does it do if the PV does not exist?

**Comment by John-Holt-Tessella** [comment]
We should probably allow the DAE to be set in simulation mode if it is in `unknown` state (i.e. switched off), possibly with a warning. I think it does print an error message, certainly when it is running it prints:

```
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 2241, in set_dae_simulation_mode
    return __api.dae.set_simulation_mode(mode)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 126, in _wrapper
    raise ValueError(e_string)
ValueError: set_simulation_mode can only be run in the following runstates: SETUP, PROCESSING
```

and I assume there is a similar one for is the dae is off. I do get a weird errror if it can not read the run state, which might be true if the DAE ioc is restarting.

**Comment by Tom-Willemsen** [comment]
add unknown to the list of states this is allowed in

consider whitelist vs blacklist

**Comment by mihai-stfc** [comment]
I and @John-Holt-Tessella had a look at this ticket and, although adding 'UNKNOWN' to the allowed states is simple and may fix the issue, we would still need to make tests before pushing the code, making the ticket more complicated than initially anticipated. 
Allowing `g.set_dae_simulation_mode` to run even while in 'UNKNOWN' may lead to unexpected issues, which is why thorough testing should be implemented. 
For the time being, to bypass this issue, the `set_dae_simulation_mode` function already has a `skip_required_runstates` parameter (default False, should be used with caution).
