### ISSUE TITLE
OPI error

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4705]
As a scientist on nimrod I don't want the following error to pop up in a BOY console, potentially obscuring my python console. This caused a support call.

```
2019-09-06 15:19:51 ERROR: Error in spectra_plots_script.py on Spectra plot.
Traceback (most recent call last):
  File "<script>", line 37, in <module>
  File "<script>", line 26, in main
	at java.util.Objects.requireNonNull(Objects.java:290)
	at org.csstudio.opibuilder.scriptUtil.PVUtil.checkPVValue(PVUtil.java:118)
	at org.csstudio.opibuilder.scriptUtil.PVUtil.getString(PVUtil.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NullPointerException: java.lang.NullPointerException: PV loc://_LOCAL:SPEC:MODE0 has no value.

2019-09-06 15:19:51 ERROR: Error in spectra_plots_script.py on Spectra plot.
Traceback (most recent call last):
  File "<script>", line 37, in <module>
  File "<script>", line 26, in main
	at java.util.Objects.requireNonNull(Objects.java:290)
	at org.csstudio.opibuilder.scriptUtil.PVUtil.checkPVValue(PVUtil.java:118)
	at org.csstudio.opibuilder.scriptUtil.PVUtil.getString(PVUtil.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NullPointerException: java.lang.NullPointerException: PV loc://_LOCAL:SPEC:MODE0 has no value.
```

**Comment by Tom-Willemsen** [comment]
+1 same stack trace from EMU.

We believe that on EMU, this might be reproducible by changing the DAE to use >2 periods, point a spectrum plot at period 2, and then switch DAE modes back to a single period.

**Comment by ThomasLohnert** [comment]
is this fixed by https://github.com/ISISComputingGroup/IBEX/issues/5302 ?

**Comment by Tom-Willemsen** [comment]
> I don't want the following error to pop up in a BOY console, potentially obscuring my python console

Yes, this is fixed by 5302.
