### ISSUE TITLE
VESUVIO: errors when pausing

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4746]
From Giovanni on Vesuvio:

> I am experiencing a certain number of unexpected warning messages in the Scripting window of Ibex on VESUVIO. These have to do with exceptions with the pausing and resuming of runs when we use our inst.runtime script. However, I was not having such warnings over the past days, and they started yesterday evening. I am attaching below some lines from the Scripting window when these messages first appeared...

> It does not look like this is causing problems with the data acquisition, but it is certainly confusing and could be synthom of something wrong elsewere... Just to mention, althoug probably uncorrelated, we had some problems with connecting to the DAE last week.

```
inst.runtime(number_of_periods = 6, iterations_per_run = 3, number_of_runs = 100) Beginning run 1 of 100
** Beginning Run 00038898 at 16:53:48 16/09/19
*  Proposal Number: 1930012
*  Experiment Team: Romanelli
** Pausing Run 00038898 at 16:54:26 16/09/19 Position A0
** Resuming Run 00038898 at 16:54:31 16/09/19 Waiting for 15.0 uamps
** Pausing Run 00038898 at 17:00:46 16/09/19 Position A1
** Resuming Run 00038898 at 17:00:54 16/09/19 Waiting for 30.0 uamps
** Pausing Run 00038898 at 17:07:15 16/09/19 Position B0
** Resuming Run 00038898 at 17:07:57 16/09/19 Waiting for 45.0 uamps
** Pausing Run 00038898 at 17:14:18 16/09/19 Position B1
** Resuming Run 00038898 at 17:14:30 16/09/19 Waiting for 60.0 uamps
** Pausing Run 00038898 at 17:20:50 16/09/19 Position C0
** Resuming Run 00038898 at 17:21:32 16/09/19 Waiting for 75.0 uamps
** Pausing Run 00038898 at 17:27:53 16/09/19 Position C1
** Resuming Run 00038898 at 17:28:01 16/09/19 Waiting for 90.0 uamps
** Pausing Run 00038898 at 17:34:21 16/09/19 Position A0
** Resuming Run 00038898 at 17:35:42 16/09/19 Waiting for 105.0 uamps
** Pausing Run 00038898 at 17:42:03 16/09/19 Position A1
** Resuming Run 00038898 at 17:42:11 16/09/19 Waiting for 120.0 uamps
** Pausing Run 00038898 at 17:48:32 16/09/19 Position B0
** Resuming Run 00038898 at 17:49:14 16/09/19 Waiting for 135.0 uamps
** Pausing Run 00038898 at 17:55:35 16/09/19 Position B1
** Resuming Run 00038898 at 17:55:48 16/09/19 Waiting for 150.0 uamps
** Pausing Run 00038898 at 18:02:09 16/09/19 Position C0
** Resuming Run 00038898 at 18:02:50 16/09/19 Waiting for 165.0 uamps
** Pausing Run 00038898 at 18:09:12 16/09/19 Position C1
** Resuming Run 00038898 at 18:09:19 16/09/19 Waiting for 180.0 uamps
** Pausing Run 00038898 at 18:15:41 16/09/19 Position A0
** Resuming Run 00038898 at 18:17:02 16/09/19 Waiting for 195.0 uamps
** Pausing Run 00038898 at 18:23:22 16/09/19 Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 798, in pause
    __api.dae.post_pause_check(verbose)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 466, in post_pause_check
    self._check_for_runstate_error(self._get_dae_pv_name("pauserun"), "PAUSE")
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 217, in _check_for_runstate_error
    self._get_pv_value(self._get_dae_pv_name("errormessage"), to_string=True)))
Exception: PAUSE Cannot execute command "PAUSERUN" when in state "PAUSED"
Position A1
** Resuming Run 00038898 at 18:23:30 16/09/19 Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 818, in resume
    __api.dae.post_resume_check(verbose)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 485, in post_resume_check
    self._check_for_runstate_error(self._get_dae_pv_name("resumerun"), "RESUME")
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 217, in _check_for_runstate_error
    self._get_pv_value(self._get_dae_pv_name("errormessage"), to_string=True)))
Exception: RESUME Cannot execute command "RESUMERUN" when in state "RUNNING"
Waiting for 210.0 uamps
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 796, in pause
    __api.dae.pause_run()
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 126, in _wrapper
    raise ValueError(e_string)
ValueError: pause_run can only be run in the following runstates: RUNNING, VETOING, WAITING Position B0
** Resuming Run 00038898 at 18:30:32 16/09/19 Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 818, in resume
    __api.dae.post_resume_check(verbose)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 485, in post_resume_check
    self._check_for_runstate_error(self._get_dae_pv_name("resumerun"), "RESUME")
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 217, in _check_for_runstate_error
    self._get_pv_value(self._get_dae_pv_name("errormessage"), to_string=True)))
Exception: RESUME Cannot execute command "RESUMERUN" when in state "RUNNING"
Waiting for 225.0 uamps
** Pausing Run 00038898 at 18:36:54 16/09/19 Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 798, in pause
    __api.dae.post_pause_check(verbose)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 466, in post_pause_check
    self._check_for_runstate_error(self._get_dae_pv_name("pauserun"), "PAUSE")
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 217, in _check_for_runstate_error
    self._get_pv_value(self._get_dae_pv_name("errormessage"), to_string=True)))
Exception: PAUSE Cannot execute command "PAUSERUN" when in state "PAUSED"
Position B1

```

**Comment by FreddieAkeroyd** [comment]
Looks to be due to a second python process (35384) coming into play
```
2019-09-16T18:17:01       (CMD)   (38272) change_period {'period': 1}
2019-09-16T18:17:01       (CMD)   (38272) set_pv_value IN:VESUVIO:DAE:PERIOD:SP 1
2019-09-16T18:17:01       (CMD)   (38272) resume {'verbose': False}
2019-09-16T18:17:02       (CMD)   (38272) set_pv_value IN:VESUVIO:DAE:RESUMERUN 1
2019-09-16T18:17:02       (CMD)   (38272) waitfor_runstate {'state': 'PAUSED', 'maxwaitsecs': 3600, 'onexit': True}
2019-09-16T18:17:02       (CMD)   (38272) WAITFOR_RUNSTATE ONEXIT STATE EXITED
2019-09-16T18:23:22       (CMD)   (38272) WAITFOR EXITED NORMALLY
2019-09-16T18:23:22       (CMD)   (38272) pause {'verbose': False}
2019-09-16T18:23:22       (CMD)   (35384) WAITFOR EXITED NORMALLY
2019-09-16T18:23:22       (CMD)   (35384) pause {'verbose': False}
2019-09-16T18:23:22       (CMD)   (38272) set_pv_value IN:VESUVIO:DAE:PAUSERUN 1
2019-09-16T18:23:22       (CMD)   (35384) set_pv_value IN:VESUVIO:DAE:PAUSERUN 1
2019-09-16T18:23:22       (CMD)   (38272) waitfor_runstate {'state': 'PAUSED', 'maxwaitsecs': 3600, 'onexit': False}
2019-09-16T18:23:22       (CMD)   (35384) waitfor_runstate {'state': 'PAUSED', 'maxwaitsecs': 3600, 'onexit': False}
2019-09-16T18:23:23       (CMD)   (38272) WAITFOR_RUNSTATE STATE REACHED
2019-09-16T18:23:23       (CMD)   (35384) WAITFOR_RUNSTATE STATE REACHED
2019-09-16T18:23:23       (CMD)   (38272) cset {'args': ('BackFoil', 232.5), 'kwargs': {'runcontrol': False, 'lowlimit': 232.25, 'highlimit': 232.75}}
2019-09-16T18:23:23       (CMD)   (35384) cset {'args': ('BackFoil', 232.5), 'kwargs': {'runcontrol': False, 'lowlimit': 232.25, 'highlimit': 232.75}}
```
