### ISSUE TITLE
SUPPORT: ALARM View is broken on multiple instruments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4776]
Problems with at least:

ALF, EMMA, ENGINX, GEM, LARMOR probably others too (all showing same error)

LARMOR and maybe other instruments has an issue with their alarm server. It is failing with the following error:

```
[2019-09-19 16:08:46] java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '9' for key 'PRIMARY'

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1114)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1062)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1383)

[2019-09-19 16:08:46] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1047)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfiguration.addPV(AlarmConfiguration.java:462)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.loadPV(AlarmConfigurationLoader.java:171)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.loadComponent(AlarmConfigurationLoader.java:127)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.loadChildComponents(AlarmConfigurationLoader.java:91)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.loadComponent(AlarmConfigurationLoader.java:120)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.loadChildComponents(AlarmConfigurationLoader.java:91)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.load(AlarmConfigurationLoader.java:76)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.client.AlarmConfigurationLoader.load(AlarmConfigurationLoader.java:51)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.configtool.Application.importExport(Application.java:361)

[2019-09-19 16:08:46] 	at org.csstudio.alarm.beast.configtool.Application.start(Application.java:218)

[2019-09-19 16:08:46] 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

[2019-09-19 16:08:46] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

[2019-09-19 16:08:46] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

[2019-09-19 16:08:46] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)

[2019-09-19 16:08:46] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)

[2019-09-19 16:08:46] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-09-19 16:08:46] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-09-19 16:08:46] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-09-19 16:08:46] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2019-09-19 16:08:46] 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)

[2019-09-19 16:08:46] 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)

[2019-09-19 16:08:46] 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

Sympton is that there are fewer alarms than their should be in the database.

I think that the rows in the table `alarm.pv` have not been deleted correctly. It can not then inserted the needed data in here. I think that this was caused during the database update where we imported that data but not the `alarm_tree` data.

Plan

1. Get data from larmor and reproduce the issue
1. Try deleting the data and make sure that it now works.
1. Find machines with this problem and fix.

### Acceptance Criteria

- Cause is understood
- Upgrade script fixes problem

**Comment by John-Holt-Tessella** [comment]
This was found during investigating new gui problems.

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:
https://github.com/ISISComputingGroup/ibex_utils/pull/67
