### ISSUE TITLE
BLOCKSERVER: Macros which are too long mean that configs can not be loaded

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4934]
If a macro in a block server is longer than 60 characters then the configuration can no longer be loaded. This is needed for long paths for instance in the twin cat IOC. Reproduce:

1. Create a new config
1. Add an IOC (twin cat is good)
1. Set a macro to something longer than 60 characters
1. Save
1. Say yes to switch to config

Config does not load.

### Acceptance Criteria

1. The maximum length for a macro is established
1. Macros of that length characters can be saved and loaded in the GUI
1. Error is displayed in the GUI if the macro is too long

### Notes

It looks like the neither the schema nor the immediate load code has been altered recently. The path to this code may have been.

Stack trace:

```
[Thu Nov  7 09:38:27 2019] [1573119507.14] MAJOR: Exception while loading configuration 'long_macro': Element '{http://epics.isis.rl.ac.uk/schema/iocs/1.0}macro', attribute 'value': [facet 'maxLength'] The value 'c:\a1234567890123456789012345678921345678912345678912345678912345678912345789123456789' has a length of '86'; this exceeds the allowed maximum length of '60'., line 5
[Thu Nov  7 09:38:27 2019] Traceback (most recent call last):

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\\block_server.py", line 398, in load_config

[Thu Nov  7 09:38:27 2019]     self._active_configserver.load_active(config)

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\active_config_holder.py", line 140, in load_active

[Thu Nov  7 09:38:27 2019]     self.set_config(self.load_configuration(name))

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 413, in load_configuration

[Thu Nov  7 09:38:27 2019]     return self._filemanager.load_config(name, self._macros, False)

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 113, in load_config

[Thu Nov  7 09:38:27 2019]     self._check_againgst_schema(correct_xml, FILENAME_IOCS)

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 162, in _check_againgst_schema

[Thu Nov  7 09:38:27 2019]     ConfigurationSchemaChecker.check_xml_data_matches_schema(schema_path, xml)

[Thu Nov  7 09:38:27 2019]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\schema_checker.py", line 72, in check_xml_data_matches_schema

[Thu Nov  7 09:38:27 2019]     raise ConfigurationInvalidUnderSchema(err.message)
```

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/1019
https://github.com/ISISComputingGroup/EPICS-ioc/pull/462
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/267
