### ISSUE TITLE
ZOOM: IBEX hung during a "Scan" command (locked ICP commands out)

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4961]
Scan command being run by SK, did four scan points and then stuck and script did not return.  After Ctrl-C it was not possible to resume or abort the run. This functionality appeared locked up.  Connected remotely from DEMO client and noticed that only the first Five digits of the run number were showing on the dashboard i.e. `Run: 00009`.  Client was restarted on ZOOM but there was still no control of DAE available (all buttons grayed out in client).  Loaded y axis plot into log plotter, brought up sample stack y axis OPI, values looked OK in this.  Buttons appeared enabled in DAE OPI at this point and full run number appeared in remote client.  ried a scan command, gave errors.  Typed command "populate()" .  After a long pause this returned and the scan command then appeared to start normally and re-do the scan which failed previously.  Time of attempted scan which failed was ~21:42 see 
![image](https://user-images.githubusercontent.com/3035405/69015697-80da0800-098e-11ea-9208-083eb3a5ea89.png)

needs some investigation could possibly be waitformove failure (bug without notification) hanging?

**Comment by John-Holt-Tessella** [comment]
genie python log:

```
<normal>
2019-11-17T21:30:46	(CMD)	(24888)	waitfor {'raw_frames': None, 'wait_all': False, 'maxwait': None, 'seconds': None, 'uamps': None, 'highlimit': None, 'value': None, 'hours': None, 'lowlimit': None, 'pars': {}, 'time': None, 'frames': 830, 'early_exit': <function <lambda> at 0x000000001BE7C358>, 'minutes': None, 'block': None}
2019-11-17T21:31:06	(CMD)	(24888)	WAITFOR EXITED NORMALLY
2019-11-17T21:31:06	(CMD)	(24888)	pause {'verbose': False}
2019-11-17T21:31:06	(CMD)	(24888)	set_pv_value IN:ZOOM:DAE:PAUSERUN 1
2019-11-17T21:31:07	(CMD)	(24888)	waitfor_runstate {'state': 'PAUSED', 'maxwaitsecs': 3600, 'onexit': False}
2019-11-17T21:31:08	(CMD)	(24888)	WAITFOR_RUNSTATE STATE REACHED
2019-11-17T21:31:08	(CMD)	(24888)	get_period {}
2019-11-17T21:31:08	(CMD)	(24888)	get_period {}
2019-11-17T21:31:09	(CMD)	(24888)	get_period {}
2019-11-17T21:31:09	(CMD)	(24888)	get_period {}
2019-11-17T21:31:09	(CMD)	(24888)	change_period {'period': 2}
2019-11-17T21:31:09	(CMD)	(24888)	set_pv_value IN:ZOOM:DAE:PERIOD:SP 2
2019-11-17T21:31:10	(CMD)	(24888)	cset {'args': (u'SampleStack_Y', -110.0), 'kwargs': {}}
2019-11-17T21:31:10	(CMD)	(24888)	set_pv_value IN:ZOOM:CS:SB:SampleStack_Y:SP -110.0
2019-11-17T21:31:10	(CMD)	(24888)	check_alarms {'blocks': (u'SampleStack_Y',)}
2019-11-17T21:31:10	(CMD)	(24888)	waitfor_move {'blocks': (), 'kwargs': {}}
2019-11-17T21:31:12	(CMD)	(24888)	WAITFOR_MOVE START TIMED OUT
2019-11-17T21:31:13	(CMD)	(24888)	WAITFOR_MOVE MOVE FINISHED
2019-11-17T21:31:13	(CMD)	(24888)	cget {'block': u'SampleStack_Y'}
2019-11-17T21:31:13	(CMD)	(24888)	check_alarms {'blocks': (u'SampleStack_Y',)}
2019-11-17T21:31:13	(CMD)	(24888)	get_frames {'period': False}
2019-11-17T21:31:13	(CMD)	(24888)	resume {'verbose': False}
2019-11-17T21:31:14	(CMD)	(24888)	set_pv_value IN:ZOOM:DAE:RESUMERUN 1
2019-11-17T21:31:14	(CMD)	(24888)	waitfor_runstate {'state': 'PAUSED', 'maxwaitsecs': 3600, 'onexit': True}
2019-11-17T21:31:14	(CMD)	(24888)	WAITFOR_RUNSTATE ONEXIT STATE EXITED
2019-11-17T21:31:14	(CMD)	(24888)	waitfor {'raw_frames': None, 'wait_all': False, 'maxwait': None, 'seconds': None, 'uamps': None, 'highlimit': None, 'value': None, 'hours': None, 'lowlimit': None, 'pars': {}, 'time': None, 'frames': 1042, 'early_exit': <function <lambda> at 0x000000001BE7C358>, 'minutes': None, 'block': None}
2019-11-17T21:31:35	(CMD)	(24888)	WAITFOR EXITED NORMALLY
2019-11-17T21:31:35	(CMD)	(24888)	pause {'verbose': False}
2019-11-17T21:31:35	(CMD)	(24888)	set_pv_value IN:ZOOM:DAE:PAUSERUN 1
<fail is here>
2019-11-17T21:42:23	(CMD)	(24888)	abort {'verbose': False}
```

ISIS ICP Log:

```
2019-11-17 21:31:14  Resuming run 9936
2019-11-17 21:31:14  (0) EventStoreCard: [Information] (EventStoreCard<class DAE3DetCardPolicy>::setOutputFileName) Source 0: Using info file c:\data\events\run_9936\dc_0.info words 0 LF=4294967295 GF=0
2019-11-17 21:31:14  (0) EventStoreCard: [Information] (EventStoreCard<class DAE3DetCardPolicy>::setOutputFileName) Source 1: Using info file c:\data\events\run_9936\dc_1.info words 25848 LF=841 GF=842
2019-11-17 21:31:14  (0) EventStoreCard: [Information] (EventStoreCard<class DAE3DetCardPolicy>::setOutputFileName) Source 2: Using info file c:\data\events\run_9936\dc_2.info words 25392 LF=841 GF=842
2019-11-17 21:31:14  *** Timing information for EventStore::setOutputFileName: real(0.041989) thread(kernel=0, user=0.015625) process(kernel=0, user=0.015625)
2019-11-17 21:31:14  Previous DAE time drift (icp - dae) = 2.847500 ms
2019-11-17 21:31:14  Time sync delay = 0.311240 ms
2019-11-17 21:31:14  DAE time drift (icp - dae) = 0.652600 ms
2019-11-17 21:31:14  *** Timing information for Time to compute and set new DAE time values: real(0.002929) thread(kernel=0, user=0) process(kernel=0, user=0)
2019-11-17 21:31:14  Setting new DAE time to 2019-11-17T21:31:14.221
2019-11-17 21:31:14  *** Timing information for refreshCachedValues: real(0.011718) thread(kernel=0, user=0) process(kernel=0, user=0)
2019-11-17 21:31:14  *** Timing information for RESUME: real(0.105462) thread(kernel=0, user=0.0625) process(kernel=0.015625, user=0.078125)
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::fixFrameHeader) Source 2: Fixing frame header (0 -> 892) and for subsequent frames this run
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: Event header invalid: marker0=0x0. marker1=0x0. header_length field: 0 != 16. 
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Frame header invalid: marker0=0x0. marker1=0x0. header_length field: 0 != 16. 
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Frame 892
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Num events 0
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Time 1601-01-01T00:00:00.0
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: Cannot find header in buffer
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: buffer not fully used - remaining words = 112
2019-11-17 21:31:19  (11) DetectorCard: [Warning] (DetectorCard<class DAE3DetCardPolicy>::updateDAEEventLastRead) (card 2 on ISISDAE0) Memory nearly full only: bytes free=448, last read=108032, last written=107584

<repeated until 2019-11-17 21:49:09>
```

Diagnosis is DAE 3 hardware failure,

**Comment by smk78** [comment]
A little more detail.

We had at this point run almost 30 motion axis scans, and 40 data collection runs, over the course of ~50 hours without incident.

The scan command that hung (after 4 steps) was:

```
scan(SampleStack_Y,-108,-121,-0.5,200,detector=monitor5)
```

When I noticed, I Ctrl-C'd to get the >>> prompt. ZOOM was Paused at this point. I tried typing abort() and resume() to no effect:

```
abort()
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 756, in abort
    __api.dae.abort_run()
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 126, in _wrapper
    raise ValueError(e_string)
ValueError: abort_run can only be run in the following runstates: RUNNING, VETOING, WAITING, PAUSED
resume()
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 816, in resume
    __api.dae.resume_run()
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 126, in _wrapper
    raise ValueError(e_string)
ValueError: resume_run can only be run in the following runstates: PAUSED
```

I then went to the DAE view but all the buttons were greyed out. So then I exited the Ibex client and restarted it. But it came back in the same state.

It was bout this point that I got to talk to CMM.

**Comment by smk78** [comment]
Here are screenshots I took:

![IMG_3149](https://user-images.githubusercontent.com/10938679/69050192-61c49000-09f9-11ea-87dc-855a77dc15f3.jpg)
![IMG_3150](https://user-images.githubusercontent.com/10938679/69050200-65f0ad80-09f9-11ea-9b2b-37745e12e6cd.jpg)

**Comment by FreddieAkeroyd** [comment]
From the logs it looks like the run did eventually pause, is that correct? 
```
2019-11-17 21:49:10  *** Timing information for PAUSE: real(1055.14) thread(kernel=0.09375, user=0.140625) process(kernel=190.969, user=91.6563)
2019-11-17 22:16:18  Resuming run 9936
```
This may have been too long for genie python command to wait? It seems that the DAE returned invalid data after a resume (frame number reset to zero).
```
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Frame header invalid: marker0=0x0. marker1=0x0. header_length field: 0 != 16. 
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Frame 892
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Num events 0
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] Time 1601-01-01T00:00:00.0
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: Cannot find header in buffer
2019-11-17 21:31:19  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: buffer not fully used - remaining words = 112
2019-11-17 21:31:19  (11) DetectorCard: [Warning] (DetectorCard<class DAE3DetCardPolicy>::updateDAEEventLastRead) (card 2 on ISISDAE0) Memory nearly full only: bytes free=448, last read=108032, last written=107584
```
 The control program then started to search memory for valid data which it eventually found
```
2019-11-17 21:47:52  (16) EventStoreCard: [Warning] (EventStoreCard<class DAE3DetCardPolicy>::checkAndHistogramEvents) Source 2: Skipped 8361576 words and found header at offset 8361592
```
However  this took 15 minutes. The "memory full" error occurs when the "last computer read" and "last dae written" values get very close together.  However there had just been a resume so there would not have been time for this to really happen, which suggests the register values were returned incorrectly. As it is a circular buffer, if "last dae written" is less than "last computer write", the program would search from current location to end of memory and then back to start of memory, which would take a long time. I'd need to look at the ICP recovery method on the case of invalid DAE data, it may be it accidentally searched too far and this then resulted in it searching more of memory than intended for valid data.

**Comment by FreddieAkeroyd** [comment]
Note: ibex server/isisicp were not restarted during this sequence

**Comment by smk78** [comment]
I'd never considered this before: so is **NDXZOOM is Pausing** the same as, or different, to a Paused state?

But certainly frames, uamps, etc were not incrementing on the screen.

**Comment by FreddieAkeroyd** [comment]
PAUSING is a transition state - it means a PAUSE has been requested, but the pause hasn't completed yet. Normally a pause is very quick, but in event mode it does wait for the few remaining events to be read from the DAE. Due to the invalid data that was read, it ended up searching all of memory for valid data and this caused the PAUSING state to exist for longer than usual. These transition states did not exist in SECI - seci would have been "running" until pause was completed, I added reporting transition states in ibex so you know that the request has been received and is being actioned.

**Comment by smk78** [comment]
Following a meeting this morning between @John-Holt-Tessella , @rprospero , @smk78 & DAV it is highly likely that this issue arose because scans were being performed on ZOOM with the DAE configured in SANS mode instead of TRANS mode. See https://github.com/ISISComputingGroup/IBEX/issues/4964

scan() uses periods, and so if the DAE is not first configured for transmissions there is a real possibility (depending on the number of steps requested in the scan) that there will be insufficient memory. Due to a bug in the ZOOM scan configuration (and oversight by the Local Contact), scan() was _not_ being used in transmission mode.

The DAE memory installed on ZOOM allows for 20 periods in SANS mode. The scan commend used:

```
scan(SampleStack_Y,-108,-121,-0.5,200,detector=monitor5)
```

required [(-121 - -108)/-0.5] - 1 = 25 periods.

**Comment by ChrisM-S** [comment]
A good error fed back to the console on the overallocation of resources would seem to be the highest priority here.

**Comment by KathrynBaker** [comment]
#4992 should provide the necessary messages/behaviour to resolve this issue more appropriately - as such I am calling this ticket reviewed and complete
