### ISSUE TITLE
genie_script_checker: falls over with dictionary assignment

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5209]
As a user on MARI I would like to be able to use the following (valid) python syntax in my scripts:

```python
a = {}
a["b"] = 1
```

The script checker currently falls over with an error like the following:

```
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 1291, in load_script
    errs = sc.check_script(full_name, instrument_full_name, warnings_as_error=warnings_as_error)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_script_checker.py", line 110, in check_script
    functions = self.get_inst_attributes(inst_scripts_file_path)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_script_checker.py", line 170, in get_inst_attributes
    attributes += self.get_all_attributes(tree)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_script_checker.py", line 182, in get_all_attributes
    attributes = self.get_names_of_functions_classes_global_variables(tree.body)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_script_checker.py", line 202, in get_names_of_functions_classes_global_variables
    attributes += "inst.{},".format(item.targets[0].id)
AttributeError: 'Subscript' object has no attribute 'id'

```

I have given MARI a hotfix, but we need to think about cases like this more carefully and write tests for each one

Acceptance criteria:
- "Obvious" cases similar to this are caught properly. Look at Python Parser
- Unit tests for these

**Comment by Tom-Willemsen** [comment]
Hotfix at https://github.com/ISISComputingGroup/genie_python/pull/222 in case other instruments also need this. 

Before being merged it needs additional thought about similar cases, and unit tests which prove that the behaviour is correct in all the cases we can think of.
