### ISSUE TITLE
system test failure: missing asyncio

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5376]
System test failing with missing asyncio
* are we missing a python 2.* backport
* or should the test only run in python3

```Traceback (most recent call last):
  File "C:\Jenkins\workspace\System_Tests\test_plotting.py", line 34, in setUpClass
    import matplotlib.pyplot as pyplot
  File "C:\Instrument\Apps\Python\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Instrument\Apps\Python\lib\site-packages\matplotlib\backends\__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\matplotlib_backend\ibex_web_backend.py", line 13, in <module>
    import asyncio
ImportError: No module named asyncio
```

**Comment by John-Holt-Tessella** [comment]
These tests use genie_python to run so should now be in 3

**Comment by Tom-Willemsen** [comment]
As of https://github.com/ISISComputingGroup/IBEX/issues/5175 everything that uses matplotlib should be using Py3 I believe.

**Comment by John-Holt-Tessella** [comment]
pull request:

- https://github.com/ISISComputingGroup/system_tests/pull/39
