### ISSUE TITLE
system tests: failing to report error

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5479]
It appears the main tests did not run at all, but this was not reported as failure
```
15:46:54  WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
15:46:54  You should consider upgrading via the 'python -m pip install --upgrade pip' command.
15:49:00  ERROR: IPython does not exist, auto complete not installed
15:49:00  
15:49:00  genie_python version 0.0.0.qualifier
15:49:00  Traceback (most recent call last):
15:49:00    File "C:\Jenkins\workspace\System_Tests_debug\run_tests.py", line 80, in <module>
15:49:00      shutil.copytree(file_or_dir_src, file_or_dir_dest)
15:49:00    File "C:\Instrument\Apps\Python3\lib\shutil.py", line 548, in copytree
15:49:00      return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
15:49:00    File "C:\Instrument\Apps\Python3\lib\shutil.py", line 449, in _copytree
15:49:00      os.makedirs(dst, exist_ok=dirs_exist_ok)
15:49:00    File "C:\Instrument\Apps\Python3\lib\os.py", line 221, in makedirs
15:49:00      mkdir(name, mode)
15:49:00  FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/Instrument/Settings/config/NDHSPARE70/configurations\\configurations\\rcptt_simple'
15:49:00  "running base tests failed."
15:49:00  Skipping config_env - already run previously
15:49:00  If you need to rerun config_env you must start a new EPICS terminal
15:49:00  
15:49:00  Running tests...
15:49:00  ----------------------------------------------------------------------
15:49:00  sss
15:49:00  ----------------------------------------------------------------------
15:49:00  Ran 3 tests in 0.003s
15:49:00  
15:49:00  OK (skipped=3)
15:49:00  
```

**Comment by John-Holt-Tessella** [comment]
Which build was this?

**Comment by FreddieAkeroyd** [comment]
Both http://epics-jenkins.isis.rl.ac.uk/job/System_Tests_debug/136/ and http://epics-jenkins.isis.rl.ac.uk/job/System_Tests_debug/134/

**Comment by FreddieAkeroyd** [comment]
The current logic checks the xml unit test output for errors, but if it fails to run any tests this is not picked up as there is no xml to parse
