### ISSUE TITLE
VHDs: jenkins build error leaves MySQL missing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5619]
The VHDs build failed with the following error resulting in the Instrument/Apps/MySQL directory not being restored and subsequent system test jenkins jobs failing as there was no MySQL service running   

## Acceptance Criteria

- When the VHDs job fails, it correctly restores the previous system (Apps) state
 
```
12:11:33  Request VHDs to be dismounted ...
12:11:33  Waiting for file at C:\Instrument\ibex_vhd_deployment_dismount_vhds.txt to be deleted...
12:12:11  ... Done
12:12:11  Copy VHDs to local area ...
12:12:16  ... Done
12:12:16  Request VHDs to be mounted ...
12:12:16  Waiting for file at C:\Instrument\ibex_vhd_deployment_mount_vhds.txt to be deleted...
12:17:23  Error in task 'Request VHDs to be mounted'
12:17:23  Traceback (most recent call last):
12:17:23    File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\task.py", line 12, in _run_task_to_completion
12:17:23      func(self_decorated_method, *args, **kwargs)
12:17:23    File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 75, in request_mount_vhds
12:17:23      self._create_file_and_wait_for_it_to_be_deleted(FILE_TO_REQUEST_VHD_MOUNTING, VHD_MOUNT_DISMOUNT_TIMEOUT)
12:17:23    File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 71, in _create_file_and_wait_for_it_to_be_deleted
12:17:23      .format(filename, timeout))
12:17:23  IOError: File at C:\Instrument\ibex_vhd_deployment_mount_vhds.txt still existed after 300s, check VHD scheduled task is running correctly
12:17:23  Do you want to R: restart task, S: skip and continue with next task, A: abort script:  : A
12:17:23  Error in upgrade: Task aborted
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Office365connector] Matched status 'FAILURE' for webhook with name 'Office 365'.
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by FreddieAkeroyd** [comment]
A  cleanup item in the Jenkinsfile post section may be a good place to add something, this should get called if the job is aborted too

**Comment by DominicOram** [comment]
Is this related to https://github.com/ISISComputingGroup/IBEX/issues/6110? Can they be done together?
