### ISSUE TITLE
Static Build: Failed to import ca

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5682]
As a developer I would like the builds to work.

The windows 7 static clean build was failing python 3 unit tests with:
```
 ImportError: Failed to import test module: BlockServerToKafka.test_modules.test_block_server_monitor
03:41:00  Traceback (most recent call last):
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\CaChannel\ca.py", line 10, in <module>
03:41:00      from ._ca import *
03:41:00  ImportError: DLL load failed while importing _ca: The specified module could not be found.
03:41:00  
03:41:00  During handling of the above exception, another exception occurred:
03:41:00  
03:41:00  Traceback (most recent call last):
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\unittest\loader.py", line 436, in _find_test_path
03:41:00      module = self._get_module_from_name(name)
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\unittest\loader.py", line 377, in _get_module_from_name
03:41:00      __import__(name)
03:41:00    File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServerToKafka\test_modules\test_block_server_monitor.py", line 19, in <module>
03:41:00      from BlockServerToKafka.block_server_monitor import BlockServerMonitor
03:41:00    File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServerToKafka\block_server_monitor.py", line 16, in <module>
03:41:00      from CaChannel import CaChannel
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\CaChannel\__init__.py", line 3, in <module>
03:41:00      from .CaChannel import CaChannel, CaChannelException
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\CaChannel\CaChannel.py", line 21, in <module>
03:41:00      from . import ca
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\CaChannel\ca.py", line 13, in <module>
03:41:00      from caffi.ca import *
03:41:00  ModuleNotFoundError: No module named 'caffi'
03:41:00  
03:41:00  
03:41:00  ======================================================================
03:41:00  ERROR [0.002s]: DatabaseServer.test_modules.test_database_server (unittest.loader._FailedTest)
03:41:00  ----------------------------------------------------------------------
03:41:00  ImportError: Failed to import test module: DatabaseServer.test_modules.test_database_server
03:41:00  Traceback (most recent call last):
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\unittest\loader.py", line 436, in _find_test_path
03:41:00      module = self._get_module_from_name(name)
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\unittest\loader.py", line 377, in _get_module_from_name
03:41:00      __import__(name)
03:41:00    File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\DatabaseServer\test_modules\test_database_server.py", line 26, in <module>
03:41:00      from DatabaseServer.database_server import DatabaseServer
03:41:00    File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\DatabaseServer\database_server.py", line 29, in <module>
03:41:00      from pcaspy import Driver
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\pcaspy\__init__.py", line 1, in <module>
03:41:00      from .driver import Driver, SimpleServer, PVInfo, SimplePV
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\pcaspy\driver.py", line 1, in <module>
03:41:00      from . import cas
03:41:00    File "C:\Instrument\Apps\EPICS\Python3\lib\site-packages\pcaspy\cas.py", line 13, in <module>
03:41:00      from . import _cas
03:41:00  ImportError: DLL load failed while importing _cas: The specified module could not be found.
```

This was due to failing to load `cas.dll` from Python. It was fixed by running a dependency walker (https://dependencywalker.com/) on `cas.dll` and finding that it required the visual studio resdit that had not been installed on the machine.

**Comment by DominicOram** [comment]
To test fix worked confirm build is now green.

**Comment by Alexandru-Dascalu** [comment]
The pipeline is still failing, but with different error messages. It complains about being able to checkout from origin, but then it seems to check out each EPICS submodule fine, then seems to fail because it cannot access some dlls within Python because those are used by another process.

**Comment by DominicOram** [comment]
Apologies, I left some stuff open on the build server. Looks healthier now.
