### ISSUE TITLE
Reflectometry: Stack trace during scan

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5726]
```
** Aborting Run 00031624 at 12:19:57 16/09/20 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-e59fe0aa4783>", line 1, in <module>
    x=30;scan(b.FOFFSET,x-0.5,x+0.5,21,frames=80,monitor_number=2,detector_number=280,fit=Erf)
  File "C:\Instrument\scripts\instrument\polref\scans.py", line 87, in scan
    return super().scan(motion, start=start, stop=stop, count=count, frames=frames, detector_number=detector_number,
  File "C:\Instrument\scripts\general\scans\defaults.py", line 199, in scan
    return scn.fit(**kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 246, in fit
    result = self.plot(action=fit.fit_plot_action(), **kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 211, in plot
    plt.draw()
  File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\pyplot.py", line 717, in draw
    gcf().canvas.draw_idle()
  File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 156, in draw_idle
    self.send_event("draw")
  File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 347, in send_event
    self.manager._send_event(event_type, **kwargs)
  File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 490, in _send_event
    s.send_json(payload)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\matplotlib_backend\ibex_web_backend.py", line 67, in wrapper
    return func(*a, **kw)
  File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg.py", line 152, in send_json
    self.write_message(json.dumps(content))
  File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\websocket.py", line 342, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\websocket.py", line 1098, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\websocket.py", line 1075, in _write_frame
    return self.stream.write(frame)
  File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\iostream.py", line 559, in write
    self._handle_write()
  File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\iostream.py", line 1009, in _handle_write
    self._write_futures.popleft()
IndexError: pop from an empty deque
```

Error function fit on FOM OFFSET scan 16/09/2020 12:23 POLREF

### Acceptance Criteria

- error is understood
- plot will not crash fit

**Comment by ThomasLohnert** [comment]
Outdated issue, closing
