### ISSUE TITLE
EMU: error setting cycle with ITC503

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5782]
```
r.settemp(100)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_api_setup.py", line 288, in log_command_and_handle_exception
    return _func_name_unlikely_to_be_reused(*args, **kwargs)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie.py", line 595, in set_pv
    _genie_api.set_pv_value(name, value, wait, is_local=is_local)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_epics_api.py", line 257, in set_pv_value
    raise e
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_epics_api.py", line 251, in set_pv_value
    Wrapper.set_pv_value(name, value, wait=wait)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 142, in set_pv_value
    chan = CaChannelWrapper.get_chan(name)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 195, in get_chan
    CaChannelWrapper.connect_to_pv(chan)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 308, in connect_to_pv
    raise UnableToConnectToPVException(ca_channel.name(), "Connection timeout")
genie_python.channel_access_exceptions.UnableToConnectToPVException: Unable to connect to PV IN:EMU:CS:SB:cycle:SP: Connection timeout
```

**Comment by FreddieAkeroyd** [comment]
`cycle` block is set to `itc501_01:heaterv:max` - i will add a :SP alias, but I thought we hid the above error message?

**Comment by John-Holt-Tessella** [comment]
Above the vmax value there is a big warning saying:

```
#
# This should not be exposed as a user-facing option on the OPI, nor made "interesting".	# This should not be exposed as a user-facing option on the OPI, nor made "interesting".
#	#
# There is potential for damaging cryostats if this is set incorrectly. A voltage which	# There is potential for damaging cryostats if this is set incorrectly. A voltage which
# is too high can burn out the heater, which is a lengthy repair.	# is too high can burn out the heater, which is a lengthy repair.
# 	# 
```

Did we really want this to be a block?

**Comment by Tom-Willemsen** [comment]
@John-Holt-Tessella does the justification in https://github.com/ISISComputingGroup/IBEX/issues/5125 clear this up?
