### ISSUE TITLE
Error in upgrade script

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5913]
Got the following during an install
```
ERROR: Cannot find JAVAC in "\bin" - please check installation
Microsoft ATL not found - drivers needing this, such as LVDCOM ones, will not be built
INFO: C/C++ CL.EXE compiler not found, you will be unable to build EPICS
INFO: PERL.EXE not found, you will be unable to build EPICS
Found PYTHON.EXE for Python 2.x as "C:\INSTRU~1\Apps\Python\python.exe"
Found PYTHON.EXE for Python 3.x as "C:\Instrument\Apps\EPICS\..\Python3\python.exe"
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1070\Python\\lib\site.py", line 178
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
Error in task 'Upgrading instrument configuration'
Traceback (most recent call last):
  File "\\isis\shares\ISIS_Experiment_Controls_Public\ibex_utils\installation_and_upgrade\ibex_install_utils\task.py", line 12, in _run_task_to_completion
    func(self_decorated_method, *args, **kwargs)
  File "\\isis\shares\ISIS_Experiment_Controls_Public\ibex_utils\installation_and_upgrade\ibex_install_utils\tasks\server_tasks.py", line 173, in upgrade_instrument_configuration
    RunProcess(CONFIG_UPGRADE_SCRIPT_DIR, "upgrade.bat", capture_pipes=False).run()
  File "\\isis\shares\ISIS_Experiment_Controls_Public\ibex_utils\installation_and_upgrade\ibex_install_utils\run_process.py", line 67, in run
    raise ErrorInRun(f"Command failed with error code: {error_code}")
ibex_install_utils.exceptions.ErrorInRun: Command failed with error code: 1s
```

**Comment by FreddieAkeroyd** [comment]
Also on SCIDEMO
