### ISSUE TITLE
vhd build: failed job leaves directories in incorrect state

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6110]
The vhd job failed with
```
[2021-01-16T16:35:28.145Z] output from scheduled task: powershell -command "echo :\\ | out-file -filepath C:\Users\ADMINI~1\AppData\Local\Temp\Var_driveletter.txt -Encoding ASCII -Append -NoNewline"
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: if %errorlevel% neq 0 exit /B 1
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: powershell -command "&cmd /c mklink /J /D C:\Instrument\var @(cat C:\Users\ADMINI~1\AppData\Local\Temp\Var_driveletter.txt)"
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: if %errorlevel% neq 0 exit /B 1
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: exit /B 0
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Running command: 'cmd /c C:\Instrument\temp.bat' as administrator
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Error in task 'Mount VHDs'
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Traceback (most recent call last):
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\task.py", line 12, in _run_task_to_completion
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     func(self_decorated_method, *args, **kwargs)
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 129, in mount_vhds
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     admin_commands.run_all()
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\admin_runner.py", line 62, in run_all
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     AdminRunner.run_command("cmd", f"/c {filename}")
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\admin_runner.py", line 33, in run_command
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     raise IOError(f"Process returned {ret} (expected {expected_return_val})")
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: OSError: Process returned 1 (expected 0)
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Do you want to R: restart task, S: skip and continue with next task, A: abort script:  : A
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Traceback (most recent call last):
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\task.py", line 12, in _run_task_to_completion
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     func(self_decorated_method, *args, **kwargs)
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 129, in mount_vhds
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     admin_commands.run_all()
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\admin_runner.py", line 62, in run_all
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     AdminRunner.run_command("cmd", f"/c {filename}")
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\admin_runner.py", line 33, in run_command
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     raise IOError(f"Process returned {ret} (expected {expected_return_val})")
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: OSError: Process returned 1 (expected 0)
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: During handling of the above exception, another exception occurred:
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: Traceback (most recent call last):
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\vhd_scheduled_task.py", line 17, in <module>
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     upgrade_instrument.mount_vhds()
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\install_tasks.py", line 256, in mount_vhds
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     self._vhd_tasks.mount_vhds()
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\task.py", line 47, in _wrapper
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     if _run_task_to_completion(task_name, prompt, self_of_decorated_method, func, args, kwargs):
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:   File "C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade\ibex_install_utils\task.py", line 30, in _run_task_to_completion
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task:     raise ErrorInTask("Task aborted")
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: ibex_install_utils.exceptions.ErrorInTask: Task aborted
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] output from scheduled task: C:\Users\Administrator\Documents\ibex_utils\installation_and_upgrade>IF 1 NEQ 0 EXIT /b 1 
[2021-01-16T16:35:28.145Z] 
[2021-01-16T16:35:28.145Z] ---
[2021-01-16T16:35:28.145Z] --- end scheduled task output ---
[2021-01-16T16:35:28.145Z] ---
[2021-01-16T16:35:28.145Z] Error in task 'Request VHDs to be mounted'
[2021-01-16T16:35:28.145Z] Traceback (most recent call last):
[2021-01-16T16:35:28.145Z]   File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\task.py", line 12, in _run_task_to_completion
[2021-01-16T16:35:28.145Z]     func(self_decorated_method, *args, **kwargs)
[2021-01-16T16:35:28.145Z]   File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 84, in request_mount_vhds
[2021-01-16T16:35:28.145Z]     self._create_file_and_wait_for_it_to_be_deleted(FILE_TO_REQUEST_VHD_MOUNTING, VHD_MOUNT_DISMOUNT_TIMEOUT)
[2021-01-16T16:35:28.145Z]   File "C:\Jenkins\workspace\Create_VHD\installation_and_upgrade\ibex_install_utils\tasks\vhd_tasks.py", line 79, in _create_file_and_wait_for_it_to_be_deleted
[2021-01-16T16:35:28.145Z]     raise IOError(f"File at {filename} still existed after {timeout}s, check VHD scheduled task is running "
[2021-01-16T16:35:28.145Z] OSError: File at C:\Instrument\ibex_vhd_deployment_mount_vhds.txt still existed after 300s, check VHD scheduled task is running correctly 
[2021-01-16T16:35:28.145Z] Do you want to R: restart task, S: skip and continue with next task, A: abort script:  : A
[2021-01-16T16:35:28.145Z] Error in upgrade: Task aborted
```

The settings directory was left with `config -> E:` and the original directory as `config_backup`. Similarly, the origin `Apps` directory was `Apps_backup`. In addition there is currently a  `C:\Instrument\Apps_backup\Apps_backup\Apps_backup\Apps_backup\Apps_backup\Apps_backup\Apps_backup\Client_E4`  etc. each directory level contains a client, python etc - it seems each job failure creates an ever deeper structure. The original `MySQL` directory was at the bottom of this tree
  

## Acceptance criteria

* When vhd job exits, it restores all directories to original state and MYSQL restarted.

**Comment by Tom-Willemsen** [comment]
Once reviewer is happy with this, re-enable the `create_vhd` job in jenkins
