### ISSUE TITLE
Blockserver: Exception when loading default synoptic for configuration

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6162]
When loading the default synoptic for a configuration after a restart of the blockserver on musr, this happened: 

```
[2021-02-01 15:59:19.189484] INFO: Finish restoring config settings
[2021-02-01 15:59:19.190460] INFO: Updating synoptic monitors
[2021-02-01 15:59:19.191436] MAJOR: Could not load last configuration. Message was: Non-str argument passed to compress_and_hex, may
be Python 2/3 compatibility issue
Argument was type bytes with value b'<?xml version="1.0" ?>\n<instrument xmlns="http://www.isis.stfc.ac.uk//instrument">\n\t<name>Be
ast_ITC503</name>\n\t<components>\n\t\t<component>\n\t\t\t<name>Steering</name>\n\t\t\t<type>UNKNOWN</type>\n\t\t\t<target>\n\t\t\t\
t<name>NONE</name>\n\t\t\t\t<type>OPI</type>\n\t\t\t\t<properties/>\n\t\t\t</target>\n\t\t\t<pvs/>\n\t\t\t<components>\n\t\t\t\t<com
ponent>\n\t\t\t\t\t<name>Vertical</name>\n\t\t\t\t\t<type>KEPCO</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<name>Kepco</name>\n\t\t\t\t
\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>KEPCO</key>\n\t\t\t\t\t\t\t\t<value>K
EPCO_05</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/
>\n\t\t\t\t</component>\n\t\t\t\t<component>\n\t\t\t\t\t<name>Horizontal</name>\n\t\t\t\t\t<type>KEPCO</type>\n\t\t\t\t\t<target>\n\
t\t\t\t\t\t<name>Kepco</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<ke
y>KEPCO</key>\n\t\t\t\t\t\t\t\t<value>KEPCO_04</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\
t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t</component>\n\t\t\t</components>\n\t\t</component>\n\t\t<component>\n\t\t\t<name>
Slits</name>\n\t\t\t<type>JAWS</type>\n\t\t\t<target>\n\t\t\t\t<name>Muon Jaws</name>\n\t\t\t\t<type>OPI</type>\n\t\t\t\t<properties
>\n\t\t\t\t\t<property>\n\t\t\t\t\t\t<key>MUONJAWS</key>\n\t\t\t\t\t\t<value>MUONJAWS_01</value>\n\t\t\t\t\t</property>\n\t\t\t\t</p
roperties>\n\t\t\t</target>\n\t\t\t<pvs/>\n\t\t\t<components/>\n\t\t</component>\n\t\t<component>\n\t\t\t<name>Magnets</name>\n\t\t\
t<type>UNKNOWN</type>\n\t\t\t<target>\n\t\t\t\t<name>NONE</name>\n\t\t\t\t<type>OPI</type>\n\t\t\t\t<properties/>\n\t\t\t</target>\n
\t\t\t<pvs/>\n\t\t\t<components>\n\t\t\t\t<component>\n\t\t\t\t\t<name>Zero Field Controller</name>\n\t\t\t\t\t<type>ZERO_FIELD</typ
e>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<name>Zero field controller</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties/>\n\t\
t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t</component>\n\t\t\t\t<component>\n\t\t\t\t\t<name>Transverse F
ield</name>\n\t\t\t\t\t<type>POWER_SUPPLY</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<name>TTIEX355P</name>\n\t\t\t\t\t\t<type>OPI</typ
e>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>TTIEX355P</key>\n\t\t\t\t\t\t\t\t<value>TTIEX355P_01</v
alue>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\
t</component>\n\t\t\t\t<component>\n\t\t\t\t\t<name>Longitudinal Field</name>\n\t\t\t\t\t<type>DANFYSIK</type>\n\t\t\t\t\t<target>\n
\t\t\t\t\t\t<name>Danfysik</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\
t<key>DFKPS</key>\n\t\t\t\t\t\t\t\t<value>DFKPS_01</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target
>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t</component>\n\t\t\t</components>\n\t\t</component>\n\t\t<component>\n\t\t\t<n
ame>Temperature</name>\n\t\t\t<type>UNKNOWN</type>\n\t\t\t<target>\n\t\t\t\t<name>NONE</name>\n\t\t\t\t<type>OPI</type>\n\t\t\t\t<pr
operties/>\n\t\t\t</target>\n\t\t\t<pvs/>\n\t\t\t<components>\n\t\t\t\t<component>\n\t\t\t\t\t<name>ITC503</name>\n\t\t\t\t\t<type>E
UROTHERM</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<name>ITC503</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t
\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>ITC503</key>\n\t\t\t\t\t\t\t\t<value>ITC503_01</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t
\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t</component>\n\t\t\t\t<component>\n\t\t\t
\t\t<name>ILM200</name>\n\t\t\t\t\t<type>CRYO_LEVEL_GAUGE</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<name>ILM200</name>\n\t\t\t\t\t\t<
type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>ILM200</key>\n\t\t\t\t\t\t\t\t<value>ILM20
0_01</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n
\t\t\t\t</component>\n\t\t\t</components>\n\t\t</component>\n\t\t<component>\n\t\t\t<name>Detector</name>\n\t\t\t<type>UNKNOWN</type
>\n\t\t\t<target>\n\t\t\t\t<name>NONE</name>\n\t\t\t\t<type>OPI</type>\n\t\t\t\t<properties/>\n\t\t\t</target>\n\t\t\t<pvs/>\n\t\t\t
<components>\n\t\t\t\t<component>\n\t\t\t\t\t<name>CAEN HV</name>\n\t\t\t\t\t<type>CAEN</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t<nam
e>Caen HV</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>MAX_CRATES<
/key>\n\t\t\t\t\t\t\t\t<value/>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>MAX_SLOTS</key>\n\t\t\t\t
\t\t\t\t<value/>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>MAX_CHANNELS</key>\n\t\t\t\t\t\t\t\t<val
ue/>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t
</component>\n\t\t\t\t<component>\n\t\t\t\t\t<name>CAENV895</name>\n\t\t\t\t\t<type>MONITOR</type>\n\t\t\t\t\t<target>\n\t\t\t\t\t\t
<name>CAENV895</name>\n\t\t\t\t\t\t<type>OPI</type>\n\t\t\t\t\t\t<properties>\n\t\t\t\t\t\t\t<property>\n\t\t\t\t\t\t\t\t<key>CAEN</
key>\n\t\t\t\t\t\t\t\t<value>CAENV895_01</value>\n\t\t\t\t\t\t\t</property>\n\t\t\t\t\t\t</properties>\n\t\t\t\t\t</target>\n\t\t\t\
t\t<pvs/>\n\t\t\t\t\t<components/>\n\t\t\t\t</component>\n\t\t\t</components>\n\t\t</component>\n\t</components>\n</instrument>\n'
[2021-02-01 15:59:19.191436] INFO: Updating config list monitors
[2021-02-01 15:59:19.202173] INFO: Updating synoptic monitors
[2021-02-01 15:59:19.202173] INFO: Finished updating synoptic monitors
[2021-02-01 15:59:19.203149] MAJOR: Error executing write queue command _edit_all_configurations for state COMPONENT_SWITCHER_EDIT:
current config  not in list of all configs {'triton_udr4_low_temp', 'ice_dilution', 'triton_udr4_high_temp', 'mercury_heliox', 'trit
on_udr3_high_temp', 'triton_udr3_low_temp', 'Beast_itc503', 'triton_king_low_temp', 'Beast_itc502', 'triton_king_high_temp'}.
Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\\block_server.py", line 564, in consume_write_queue
    cmd(*arg) if arg is not None else cmd()
  File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\component_switcher\component_switcher.py", line 132, in _edit_
all_configurations
    raise ValueError(f"current config {current_config_name} not in list of all configs {config_names}.")
ValueError: current config  not in list of all configs {'triton_udr4_low_temp', 'ice_dilution', 'triton_udr4_high_temp', 'mercury_he
liox', 'triton_udr3_high_temp', 'triton_udr3_low_temp', 'Beast_itc503', 'triton_king_low_temp', 'Beast_itc502', 'triton_king_high_te
mp'}.
```

To reproduce: 

- create config in gui 
- create synoptic for this config
- set synoptic to be the default in "edit current configuration"
- restart blockserver

**Comment by rerpha** [comment]
Also get the same error when saving some synoptics using the synoptic->edit->save as button, weirdly enough it saves to file but when creating the synoptic pv it falls over. a restart of the blockserver fixes this and then shows it in the UI but then you get the same error as mentioned above.

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/346
- https://github.com/ISISComputingGroup/IBEX/compare/master...Ticket-6162-Fix-blockserver-synoptic_manager-python2/3-str/bytes-bug?quick_pull=1
