### ISSUE TITLE
 MuSR: 3He Refrigerator Implement Cryogenic Control Logic

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6240]
As a MuSR scientist, I would like to be able to control the 3He Refrigerator.

Relies on logic being documented and approved from https://github.com/ISISComputingGroup/IBEX/issues/6239.

Acceptance criteria:

- [ ] Approved logic is implemented in the IOC

Notes:

- The 3He refrigerator is a Heliox/ITC503 based system
- LabVIEW VIs are at C:\LabVIEW Modules\Oxford Software\Muon Heliox

**Comment by JamesKingWork** [comment]
An estimate of time should be found on https://github.com/ISISComputingGroup/IBEX/issues/6239.

**Comment by JamesKingWork** [comment]
Confirmed with cryogenics and MuSR scientists that this is purely ITC503 and doesn't use ITC502s and ITC601s as the LabVIEW suggests

**Comment by JamesKingWork** [comment]
Do not implement autorecondensing as part of this ticket.

**Comment by rerpha** [comment]
Sticking this in impeded now as we're waiting for more info from cryogenics and for #6239 to be completed.

**Comment by JamesKingWork** [comment]
I am happy that we have enough of the cryogenic logic and communications correct that we can start implementing this

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/113
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/605
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/444
- https://github.com/ISISComputingGroup/EPICS-hlx503/pull/3

Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6344

**Comment by JamesKingWork** [comment]
To review:

- View docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ITC503-Heliox (the recondense section is the most important here)
- Ensure implemented logic and tests match logic described in the document
- Ensure OPI matches new logic and PVs

**Comment by rerpha** [comment]
Just taken off the under review label so someone else can review if they get round to it before I have some time to.

**Comment by rerpha** [comment]
I still get those PID errors when running the IOC tests in devsim, though im not that worried as it only seems to happen on my machine and last time we tried to reproduce it on another machine it didnt happen. 
I do however get some test errors in the IOC test framework - the recsim ones fall over, here is the first one that fails: 
```
C:\Instrument\Apps\EPICS\support\IocTestFramework\master>%PYTHON3% run_tests.py -t hlx503 -tm RECSIM -f
Testing module tests.hlx503 in Rec sim mode.
Check that IOC is not running
Starting IOC (HLX503_01)

Running tests...
----------------------------------------------------------------------
ss.F
======================================================================
FAIL [27.401s]: test_WHEN_cancelled_in_any_step_THEN_temp_not_set_AND_cancelled_1_1 (tests.hlx503.HLX503Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hlx503.py", line 274, in test_WHEN_cancelled_in_any_step_THEN_temp_not_set_AND_cancelled
    self.skip_parts(parts_skipped)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hlx503.py", line 410, in skip_parts
    self.ca.assert_that_pv_is("RE:PART", f"PART {i+1+part_offset}")
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 270, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 249, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1836:HLX503_01:RE:PART' to have value 'PART 1' (type: 'str').
Final PV value was 'PART 2' (type: 'str')

----------------------------------------------------------------------
Ran 4 tests in 85.088s

FAILED (failures=1, skipped=2)
```

There is nothing that alarming in the logs except for this line which appears a few times before iocinit, though it could be a red herring:
```
ReadASCII: File Open Failed: C:/Instrument/Apps/EPICS/support/hlx503/master/configurations/hlx503/: Permission denied
```

Will run through IOC cryo logic now

**Comment by JamesKingWork** [comment]
As musr are no longer requiring the HLX503 this cycle (they will use SECI), this ticket is no longer required for the release

**Comment by JamesKingWork** [comment]
When reworking, make sure to run the LabVIEW Vi against the emulator

**Comment by JamesKingWork** [comment]
Handed over to @rerpha

**Comment by rerpha** [comment]
note to self, I will need to sort out the tests to adapt to the fact that part 2 no longer exists

**Comment by rerpha** [comment]
recondensing seems to work now and WISH look to have managed one, but going to get some feedback before putting this in review to see if there are any niggles

**Comment by FreddieAkeroyd** [comment]
@rerpha have we had any feedback, is this ready for review?

**Comment by rerpha** [comment]
> @rerpha have we had any feedback, is this ready for review?

I need to revisit it, recondensing wasn't working very well so need to book some time in the shutdown to test against the device again.
