### ISSUE TITLE
Keithley 2700: Ordering issue with clearing buffer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6295]
As a developer I would like to be sure the Keithley 2700 correctly reads from the device after clearing the buffer. Currently you can see from the emulator that the IOC does the following:
1. Asks the next location on buffer
2. Clears the buffer
3. Asks the next location on buffer
4. Reads from the buffer assuming value in 1) rather than in 3)

```
021-03-09 17:16:25,197 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:NEXT?' using command TRAC:NEXT\?$
2021-03-09 17:16:25,197 INFO lewis.Keithley2700StreamInterface: Next buffer location: 16
2021-03-09 17:16:25,199 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:DATA:SEL? 14,2' using command TRAC:DATA:SEL\?\ ([+-]?\d+),([+-]?\d+)$
2021-03-09 17:16:25,199 INFO lewis.Keithley2700StreamInterface: Returned readings: +1084,6.164654970169067,+102,+1400,6.265652656555176,+103
2021-03-09 17:16:25,227 INFO lewis.SimulatedKeithley2700: Inserting mock data into buffer: ['+1583,6.367274522781372,+104']
2021-03-09 17:16:25,266 INFO lewis.SimulatedKeithley2700: Setting simulate readings to False
2021-03-09 17:16:25,386 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:CLE' using command TRAC:CLE$
2021-03-09 17:16:25,386 INFO lewis.SimulatedKeithley2700: === Cleared Buffer ===
2021-03-09 17:16:25,394 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:NEXT?' using command TRAC:NEXT\?$
2021-03-09 17:16:25,394 INFO lewis.Keithley2700StreamInterface: Next buffer location: 0
2021-03-09 17:16:25,395 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:DATA:SEL? 16,984' using command TRAC:DATA:SEL\?\ ([+-]?\d+),([+-]?\d+)$
2021-03-09 17:16:25,395 ERROR lewis.Keithley2700StreamInterface: An error occurred at requestb'TRAC:DATA:SEL? 16,984': IndexError('list index out of range')
2021-03-09 17:16:25,396 ERROR lewis.Keithley2700StreamInterface: Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\lewis\adapters\stream.py", line 122, in found_terminator
    reply = cmd.process_request(request)
  File "C:\Instrument\Apps\Python3\lib\site-packages\lewis\adapters\stream.py", line 398, in process_request
    return self.map_return_value(self.func(*args))
  File "C:\Instrument\Apps\epics\support\DeviceEmulator\master\lewis_emulators\keithley_2700\interfaces\stream_interface.py", line 238, in get_readings
    chunks.append("{},{},{}".format(self._device.buffer[buffer_location].reading,
IndexError: list index out of range
```

## Acceptance Criteria
* Fix the IOC to use the correct buffer length value
* Write tests to catch this
* Confirm that it still works on actual device

**Comment by FreddieAkeroyd** [comment]
Is there an issue even without a clear? It seems to get 16 here but use 14
```
021-03-09 17:16:25,197 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:NEXT?' using command TRAC:NEXT\?$
2021-03-09 17:16:25,197 INFO lewis.Keithley2700StreamInterface: Next buffer location: 16
2021-03-09 17:16:25,199 INFO lewis.Keithley2700StreamInterface.StreamHandler: Processing request b'TRAC:DATA:SEL? 14,2' using command TRAC:DATA:SEL\?\ ([+-]?\d+),([+-]?\d+)$
```

**Comment by DominicOram** [comment]
Sorry, yes, this issue is always there but only becomes a significant problem on a clear

**Comment by FreddieAkeroyd** [comment]
It looks like it reads and updates `INDEX:START` which is then subsequently read by record redirection within the stream device protocol file. It might be the read is triggered before  `INDEX:START` has updated, or there may be an issue with the record redirection. Might be worth a look as this week might be a good one to catch Dirk if you find anything?

**Comment by FreddieAkeroyd** [comment]
From a comment in the db file, if next buffer location is 0 then the ioc should read the remainder of the buffer, so it is reading buffer size less last starting point, so  984 elements starting at index 16. It looks like the emulator resets its buffer size to 0 on a clear, so not allowing the ioc to do this, so it would look like this test failure is actually an emulator issue and nothing wider in epics/stream device. I am not sure if the emulator truncating the buffer size on a clear is correct, it certainly shouldn't do it until the next new data point is added or else the ioc does not have chance to read. The hardware may allow you to read the full buffer at any time, but i'm not sure or that.    

However, having looked at this I have a few other questions. The ioc runs in auto-clear mode, so the buffer is cleared before any measurement is taken. So it then seems unlikely that the entire buffer of 1000 points would ever have valid data, but the ioc would try and read all this if next buffer was 0. I guess it is unlikely it will ever see next buffer as zero as the device will probably set it to zero and then almost immediately write new data. But it does sound like a potential race condition?

I also noticed that the aSub `$(P)BUFF:READ:PARSE:READINGS` and
`$(P)BUFF:READ:PARSE:TIME` define an NOA of 100 but take input from the read buffer which is a waveform of size  $(BUFFER_SIZE) (usually 1000). Should NOA also be $(BUFFER_SIZE) or else data might get thrown away? The manual actually recommends reading at most 100 values at a time over RS232, but if that was desired then the logic in $(P)COUNT:CALC and elsewhere will need to be updated.

Also is   `i=i+1`  right in 
https://github.com/ISISComputingGroup/EPICS-KeithleyDVM/blob/3115fec67e761c4e1113b8a413f6eef4b8d7799a/Keithley_2700Sup/parse_buffer_readings.c#L114
Wouldn’t you want to either fall though to `i=i+channel_values_count` (in case there are other valid channels) or return (assuming as soon as you see an invalid channel you are reading invalid data from then on)

I notice the ioc enables enables buffer “autoclear” and “always” buffer control mode. The “always” mode makes the buffer circular, for which reading the remainder of the buffer would certainly be appropriate. The examples seem to use “next” rather than “always” mode when autoclear is enabled. When “always” is enabled it might seem more natural to disable autoclear, but I’m not sure if having it enabled is causing an issue. Runnign with a circular buffer and no autoclear would certainly be a way to run and avoid race conditions.
