### ISSUE TITLE
MuSR: background script failing to plot values

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6347]
As a MuSR scientist, I would like my background plot to work. Currently it is not plotting any values.

I have tried restarting the IOC and the scripting window, and force refreshing the plot.

Acceptance criteria:

- [ ] Reason for failure is discovered and fixed

**Comment by rerpha** [comment]
Wonder if this is linked to #5974  ?

**Comment by DominicOram** [comment]
`BG_SCRIPT` is logging:
```
[2021-03-26 01:04:31] Update plot failed with shape mismatch: objects cannot be broadcast to a single shape

[2021-03-26 01:04:33] ERROR:tornado.application:Uncaught exception GET /1/ws (127.0.0.1)

[2021-03-26 01:04:33] HTTPServerRequest(protocol='http', host='127.0.0.1:8989', method='GET', uri='/1/ws', version='HTTP/1.1', remote_ip='127.0.0.1')

[2021-03-26 01:04:33] Traceback (most recent call last):

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\tornado\websocket.py", line 647, in _run_callback

[2021-03-26 01:04:33]     result = callback(*args, **kwargs)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\matplotlib_backend\ibex_web_backend.py", line 67, in wrapper

[2021-03-26 01:04:33]     return func(*a, **kw)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg.py", line 149, in on_message

[2021-03-26 01:04:33]     manager.handle_json(message)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 440, in handle_json

[2021-03-26 01:04:33]     self.canvas.handle_event(content)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 240, in handle_event

[2021-03-26 01:04:33]     return handler(event)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 256, in handle_draw

[2021-03-26 01:04:33]     self.draw()

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 151, in draw

[2021-03-26 01:04:33]     super().draw()

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\backends\backend_agg.py", line 393, in draw

[2021-03-26 01:04:33]     self.figure.draw(self.renderer)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper

[2021-03-26 01:04:33]     return draw(artist, renderer, *args, **kwargs)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\figure.py", line 1735, in draw

[2021-03-26 01:04:33]     mimage._draw_list_compositing_images(

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\image.py", line 137, in _draw_list_compositing_images

[2021-03-26 01:04:33]     a.draw(renderer)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper

[2021-03-26 01:04:33]     return draw(artist, renderer, *args, **kwargs)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\axes\_base.py", line 2630, in draw

[2021-03-26 01:04:33]     mimage._draw_list_compositing_images(renderer, self, artists)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\image.py", line 137, in _draw_list_compositing_images

[2021-03-26 01:04:33]     a.draw(renderer)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper

[2021-03-26 01:04:33]     return draw(artist, renderer, *args, **kwargs)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\lines.py", line 759, in draw

[2021-03-26 01:04:33]     self.recache()

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\matplotlib\lines.py", line 679, in recache

[2021-03-26 01:04:33]     self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)

[2021-03-26 01:04:33]   File "<__array_function__ internals>", line 5, in broadcast_arrays

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\numpy\lib\stride_tricks.py", line 258, in broadcast_arrays

[2021-03-26 01:04:33]     shape = _broadcast_shape(*args)

[2021-03-26 01:04:33]   File "C:\Instrument\Apps\Python3\lib\site-packages\numpy\lib\stride_tricks.py", line 189, in _broadcast_shape

[2021-03-26 01:04:33]     b = np.broadcast(*args[:32])

[2021-03-26 01:04:33] ValueError: shape mismatch: objects cannot be broadcast to a single shape

[2021-03-26 01:04:33] Update plot failed with shape mismatch: objects cannot be broadcast to a single shape

[2021-03-26 01:04:35] Update plot failed with shape mismatch: objects cannot be broadcast to a single shape

[2021-03-26 01:04:37] Update plot failed with shape mismatch: objects cannot be broadcast to a single shape

```

**Comment by rerpha** [comment]
The block that is causing this is Temp_Cryostat, disabling it and restarting the bgscript ioc and it starts plotting again. I'm not sure why the cryostat one causes it, but it looks like that error should come from an array value being passed to where a scalar is expected.

**Comment by DominicOram** [comment]
The root issue here is that when the data was being saved to CSV `None` was being saved as an empty string then that line was loaded as a reduced list. Jack's comment fixed it because it forced the corrupt csv file to be reloaded
