### ISSUE TITLE
Scans: Fix TopHatFit

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6453]
As a scientist I would like to fit my data using the TopHatFit in the scans library. Currently this fails with the exception below.

(I believe this is identical to #4424, which I thought was fixed as part of a separate issue, but was wrong)

#### Acceptance Criteria
Understand the source of the error below and fix it so TopHatFit can be used.

```
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-49-0f1d7d7ad3f8>", line 1, in <module>
    fitres=scan(b.Ftheta,-0.2,0.2,15,frames=100,mon=2,det=280,pixel_range=2,fit=TopHat)
  File "C:\Instrument\scripts\instrument\polref\scans.py", line 93, in scan
    return super().scan(motion, start=start, stop=stop, count=count, frames=frames, det=det,
  File "C:\Instrument\scripts\general\scans\defaults.py", line 195, in scan
    return scn.fit(**kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 236, in fit
    result = self.plot(action=fit.fit_plot_action(), **kwargs)
  File "C:\Instrument\scripts\general\scans\scans.py", line 200, in plot
    action_remainder = action(xs, ys,
  File "C:\Instrument\scripts\general\scans\fit.py", line 123, in action
    chi_sq = self.fit_quality(x, values, errs, params)
  File "C:\Instrument\scripts\general\scans\fit.py", line 57, in fit_quality
    return np.mean(((self.get_y(x, params) - y) / err)**2)
  File "C:\Instrument\scripts\general\scans\fit.py", line 291, in get_y
    return self._model(x, *fit[0])
  File "C:\Instrument\scripts\general\scans\fit.py", line 467, in _model
    ys[np.abs(xs - cen) < width / 2] = height
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by ThomasLohnert** [comment]
Scientists said they think this issue stems from datapoints with 0 counts having 0 error, giving them a massive weight and skewing the fit.

**Comment by DominicOram** [comment]
I tried reproducing this with a few of their old saved scans but I couldn't. I'm not sure it is a divide by 0 error, it sounds more like the shape of the array they're trying to fit is wrong.

**Comment by RaiBishal** [comment]
Had a brief look, it could be caused because we are trying to index into a normal array using NumPy array.

**Comment by DominicOram** [comment]
As part of this fix please write a system test that covers it

**Comment by ThomasLohnert** [comment]
Check this is still an issue
