### ISSUE TITLE
GUI: console log blank [TimeBox: 2 days]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6573]
As a developer I would like a way of diagnosing GUI issues on a beamline. Currently after some time the built GUI's logs go blank, in both the Help->Console Log screen and the associated file.

## Acceptance Criteria
* GUI logs do not go blank over time

**Comment by RaiBishal** [comment]
Test it if it is testable.

**Comment by mihai-stfc** [comment]
The issue seems to be that the runtime log file is not being written to after rollover.

After the `isis.log` in `C:/Users/<id>/runtime-ibex.product/logs/` reaches 1024 KB and is rotated (triggers the max size policy from the `logger\config\LoggingConfiguration.java`), the logger fails to write to the new `isis.log` and so the file remains empty, even though it appears to be continuously "updated".

![MicrosoftTeams-image](https://user-images.githubusercontent.com/69153228/124282590-e7e80880-db42-11eb-862e-2042ade17f3d.png)

This is why the GUI console log goes blank - it's reading the contents of an empty file.

By setting `.setIgnoreExceptions(false)` in the `RollingFileAppender.newBuilder()` inside `LoggingConfiguration.java`,  a lot of `AppenderLoggingException: Error writing to stream` errors caused by `IOException: Stream Closed` can be seen:

```
org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream /C:/Users/bgd37885/runtime-ibex.product/logs//isis.log
	at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
	at org.apache.logging.log4j.core.appender.FileManager.writeToDestination(FileManager.java:273)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:240)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:282)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:291)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:543)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:460)
	at org.apache.logging.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2198)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2152)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2135)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:740)
	at uk.ac.stfc.isis.ibex.logger.LoggerUtils.logErrorWithStackTrace(LoggerUtils.java:60)
	at uk.ac.stfc.isis.ibex.nicos.comms.RepeatingJob.run(RepeatingJob.java:65)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Stream Closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
	... 27 more
```
Full log: [log.txt](https://github.com/ISISComputingGroup/IBEX/files/6754979/log.txt)

Some possible general causes for why this could be happening (may or may not apply to us):
* there is a problem in the rollover logic
* in the application one thread has shut down the logging subsystem while other threads are still logging
* the file appender is closed, but the disruptor has not delivered all the messages that are meant to be in that file appender
* the log reader does not close the file correctly
* the logging configuration is reloaded multiple times, and having the same configuration instance twice (or more) could mess up the ref count, making it reach 0 prematurely

Some links regarding this issue:
* https://issues.apache.org/jira/browse/LOG4J2-636
* https://issues.apache.org/jira/browse/LOG4J2-392

### Update:
The issue was thankfully much simpler than those listed above. It was just `RollingFileAppender` being unhappy with the file path it was being provided, specifically the leading slash (`/C:/Users/<id>/runtime-ibex.product/logs//isis.log`). 
Updated `getLogDir()` inside `logger/preferences/PreferenceConstants.java` to remove any leading slashes from the `Platform.getInstanceLocation().getURL().getPath()`

Link to solution: https://issues.apache.org/jira/browse/LOG4J2-1182?focusedCommentId=16964822&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16964822

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1322
