### ISSUE TITLE
Blockserver: saving config as component does not work 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6835]
## Where?
The blockserver - see attached logs

## How?
Editing configs on IMAT

## Reproducible?
Yes

### To Reproduce
- Create a config with two IOCs in
- Save it 
- Now edit that config, delete one of the IOCs
- Save as -> save as component
- Now check the components list 
- The new component is not there 

## Acceptance criteria 
- [ ] A system/unit test is written to cover the fix 
- [ ] Problem is fixed
- [ ] We create a patch release if this is a gamestopper

```
[Mon Oct 18 17:13:12 2021] [2021-10-18 17:13:12.016916] MAJOR: Problem occurred saving configuration: Traceback (most recent call last):

[Mon Oct 18 17:13:12 2021]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\\block_server.py", line 489, in save_inactive_config

[Mon Oct 18 17:13:12 2021]     inactive.save_inactive(as_comp=True)

[Mon Oct 18 17:13:12 2021]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\inactive_config_holder.py", line 43, in save_inactive

[Mon Oct 18 17:13:12 2021]     self.save_configuration(name, as_comp)

[Mon Oct 18 17:13:12 2021]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 442, in save_configuration

[Mon Oct 18 17:13:12 2021]     self._set_as_component(as_component)

[Mon Oct 18 17:13:12 2021]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 472, in _set_as_component

[Mon Oct 18 17:13:12 2021]     for key in self._config.groups:

[Mon Oct 18 17:13:12 2021] RuntimeError: OrderedDict mutated during iteration

[Mon Oct 18 17:13:12 2021] 

```

**Comment by rerpha** [comment]
Actually, i couldn't reproduce this locally, may have been a one off
