### ISSUE TITLE
EMU: Logging on Windows 10 causes issue when rotating files

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6907]
## Where?

https://github.com/ISISComputingGroup/genie_python/blob/master/Lib/site-packages/genie_python/genie_logging.py

## How?

It looks like the RotatingFileHandlers have historically struggled with windows e.g. https://bugs.python.org/issue4749. We change to use this logging framework recently. Logs are struggling to roll over at midnight causing lots of tracebacks in the genie python console of the form:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 394, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Instrument\\Var\\logs\\genie_python\\genie-2021-11-18-Thu.log' -> 'C:\\Instrument\\Var\\logs\\genie_python\\genie-2021-11-18-Thu.log.2021-11-18'
Call stack:
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 620, in <module>
    pydevconsole.start_server(pydev_localhost.get_localhost(), int(port), int(client_port))
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 449, in start_server
    process_exec_queue(interpreter)
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 306, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_console_utils.py", line 288, in add_exec
    more = self.do_add_exec(code_fragment)
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_ipython_console.py", line 44, in do_add_exec
    res = bool(self.interpreter.add_exec(code_fragment.text))
  File "C:\volumes\APPS\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_ipython_console_011.py", line 484, in add_exec
    self.ipython.run_cell(line, store_history=True)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-8b57c052a1ce>", line 1, in <module>
    r.end()
  File "C:\Instrument\Apps\Python3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_api_setup.py", line 359, in log_command_and_handle_exception
    __api.logger.log_command(_func_name_unlikely_to_be_reused.__name__, log_args, command_exception,
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_logging.py", line 120, in log_command
    self.logger.debug(self._get_message_with_mode(f"{function_name} {arguments}"))
Message: "end {'kwargs': {}, 'args': {'verbose': False, 'quiet': False, 'immediate': False}}"
Arguments: ()
```

## Reproducible?
Yes (but only with patience)

### To Reproduce
- Leave genie python and the background script logging overnight

## Acceptance criteria 
- [ ] Genie python no longer fails to roll over logs

**Comment by JamesKingWork** [comment]
I have deployed a test solution on EMU using the code from: https://github.com/ISISComputingGroup/genie_python/pull/354. It seems to be running ok, but we will know in the next few days.

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/genie_python/pull/354
RN: https://github.com/ISISComputingGroup/IBEX/pull/6909

**Comment by JamesKingWork** [comment]
Seems to have not come back since the weekend
