### ISSUE TITLE
POLREF: Genie python console logger crash

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6911]
POLREF reported an issue where the genie_python console got filled with exceptions whenever the logger tried to write something saying that the file is already in use (example below). No other genie_python processes were active at the time. 

This was observed on Monday 22/11/2021, the log file it was trying to write to was for the preceding Thursday. POLREF said they were doing long counts over the weekend, it looks like somewhere along the line it failed to roll over the date for the logger, not sure if this is a symptom or a cause. 

Fixed the immediate issue on POLREF by restarting the console, resetting the log file target destination, but we should investigate why it broke in the first place.

### Acceptance Criteria
- [ ] Cause of logger breaking is understood and fixed
- [ ] Write a test if possible

### Extra Information
Example stack trace:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 394, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Instrument\\Var\\logs\\genie_python\\genie-2021-11-18-Thu.log' -> 'C:\\Instrument\\Var\\logs\\genie_python\\genie-2021-11-18-Thu.log.2021-11-18'
Call stack:
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 620, in <module>
    pydevconsole.start_server(pydev_localhost.get_localhost(), int(port), int(client_port))
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 449, in start_server
    process_exec_queue(interpreter)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevconsole.py", line 306, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_console_utils.py", line 288, in add_exec
    more = self.do_add_exec(code_fragment)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_ipython_console.py", line 44, in do_add_exec
    res = bool(self.interpreter.add_exec(code_fragment.text))
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_bundle\pydev_ipython_console_011.py", line 484, in add_exec
    self.ipython.run_cell(line, store_history=True)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
    result = self._run_cell(
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
    return runner(coro)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-4aec36a00b78>", line 1, in <module>
    run_polref_script()
  File "U:\TEST\Mar2022\quiet_counts.py", line 32, in run_polref_script
    g.end()
  File "C:\Instrument\Apps\Python3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_api_setup.py", line 351, in log_command_and_handle_exception
    return_value = _func_name_unlikely_to_be_reused(*args, **kwargs)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie.py", line 689, in end
    _genie_api.dae.end_run(verbose=verbose, quiet=quiet, immediate=immediate)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\utilities.py", line 319, in _wrapper
    return func(self, *args, **kwargs)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_dae.py", line 383, in end_run
    self._set_pv_value(self._get_dae_pv_name("endrun"), 1, wait=True)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_dae.py", line 199, in _set_pv_value
    self.api.set_pv_value(name, value, wait)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_epics_api.py", line 280, in set_pv_value
    self.logger.log_info_msg("set_pv_value %s %s" % (name, str(value)))
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_logging.py", line 112, in log_info_msg
    self.logger.info(self._get_message_with_mode(message))
Message: 'set_pv_value IN:POLREF:DAE:ENDRUN 1'
Arguments: ()
```

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by ThomasLohnert** [comment]
Nevermind, already fixed by https://github.com/ISISComputingGroup/IBEX/issues/6907. Closing.
