### ISSUE TITLE
Investigate refl test motor issues

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6950]
Refl tests commonly fail with
```
Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS-FreddieSystemTests\support\IocTestFramework\master\tests\refl.py", line 795, in test_GIVEN_component_with_multiple_out_of_beam_positions_is_out_of_beam_WHEN_beam_intercept_moves_above_threshold_THEN_driver_moves_to_correct_out_of_beam_position
    self.ca.assert_that_pv_is("PARAM:S3INBEAM:CHANGING", "NO", timeout=40)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 271, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 250, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Exception date time: 2022-01-03 02:02:03.869377
Expected PV, 'TE:SPARE70:REFL_01:PARAM:S3INBEAM:CHANGING' to have value 'NO' (type: 'str').
Final PV value was 'YES' (type: 'str')
```
 
## Acceptance criteria

understand why

**Comment by FreddieAkeroyd** [comment]
```
[2022-01-03 14:45:35] motorSimAxis::move axis 1 from 0 to 2000 (absolute) speed min/max 0/2.23406 acceleration 2.23406  [2022-01-03 14:45:35] motorSimAxis::move axis 1 excluding acceleration/backlash this would take approximately 895.232 seconds
[2022-01-03 14:45:35] motorSimAxis::process axis 1 has started moving: motor=0.0114171 encoder=0.0285429 [2022-01-03 14:46:15] motorSimAxis::stop axis 1 acceleration 2.23406 [2022-01-03 14:46:15] motorSimAxis::setVelocity axis 1 velocity 0 acceleration 2.23406 [2022-01-03 14:46:16] motorSimAxis::process axis 1 has stopped moving after 40.944 seconds: motor=89.4437 encoder=223.609 
```
Earlier in the log i see
``` 
[2022-01-03 14:45:27] 03-Jan-22 14:45:26 ndhspare70 ibexbuilder TE:SPARE70:MOT:MTR0102.VELO new=0.00558514 old=0.5
```
So VELO is changed from 0.5 to .0005 – I am not sure if this is part of the test Setup or from a previous ioc test that changed VELO and didn’t put it back. But the test is failing as the motor velocity is too low and it times out before motion completes.

**Comment by ThomasLohnert** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-refl/pull/40
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/525
https://github.com/ISISComputingGroup/IBEX/pull/7074

**Comment by ThomasLohnert** [comment]
This test was failing as velocities would not always get initialised properly by the IOC test framework (I believe because the tests would often finish mid-move and the autosave file would then not reflect the reality when run next time).

I have changed the reflectometry server so it now should pick up changes to the axis velocities at runtime, and changed the ioc test framework to reset those as part of the set up method.
