### ISSUE TITLE
genie_python:  should not give error when graylog server is unavailable 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7059]
As a scientist I do not want to see errors in my script window if the graylog server is not available. Currently i see:
```
--- Logging error --- 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 632, in emit
    self.send(s)
  File "C:\Instrument\Apps\Python3\lib\site-packages\graypy\handler.py", line 611, in send
    super(GELFUDPHandler, self).send(s)
  File "C:\Instrument\Apps\Python3\lib\logging\handlers.py", line 690, in send
    self.sock.sendto(s, self.address)
socket.gaierror: [Errno 11004] getaddrinfo failed
Call stack:
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\pydevconsole.py", line 620, in <module>
    pydevconsole.start_server(pydev_localhost.get_localhost(), int(port), int(client_port))
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\pydevconsole.py", line 449, in start_server
    process_exec_queue(interpreter)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\pydevconsole.py", line 306, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\_pydev_bundle\pydev_console_utils.py", line 288, in add_exec
    more = self.do_add_exec(code_fragment)
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\_pydev_bundle\pydev_ipython_console.py", line 44, in do_add_exec
    res = bool(self.interpreter.add_exec(code_fragment.text))
  File "C:\Instrument\Apps\Client_E4\plugins\org.python.pydev.core_8.3.0.202109301146\pysrc\_pydev_bundle\pydev_ipython_console_011.py", line 484, in add_exec
    self.ipython.run_cell(line, store_history=True)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-721d04bc4a38>", line 1, in <module>
    set_instrument('IN:POLREF:')
  File "C:\Instrument\Apps\Python3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_api_setup.py", line 359, in log_command_and_handle_exception
    __api.logger.log_command(_func_name_unlikely_to_be_reused.__name__, log_args, command_exception,
  File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\genie_logging.py", line 145, in log_command
    logger.debug(self._get_message_with_mode(f"{function_name} {arguments}"))
Message: "set_instrument {'kwargs': {}, 'args': {'pv_prefix': 'IN:POLREF:', 'import_instrument_init': True}}"
Arguments: ()
```

### To Reproduce
- start genie when `genie_logging.py  LoggingConfigurer   graypy   host`  is a machine name that cannot be resolved by DNS  

## Acceptance criteria 
- the system either fails silently, or prints a single warning on first use, but not a traceback on every command

**Comment by rerpha** [comment]
note that it seemed to be fine if the server was down but the dns lookup failed.

**Comment by FreddieAkeroyd** [comment]
proposing as couldn't remember if fixed?

**Comment by rerpha** [comment]
In case we need this for the next release: 

I really dislike this solution but it does work: https://github.com/ISISComputingGroup/genie_python/pull/361

I tried inheriting GELFUDPHandler to no success but I think that would be better if possible.

**Comment by rerpha** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7184
