### ISSUE TITLE
wiki_check: Fix so that external web pages don't error for no apparent reason

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7061]
As someone who supports IBEX I want my wiki checks to not error regularly with exception within exception for external websites, so that I can actually see the legitimately broken links.

## Acceptance Criteria
- [ ] The urls to ignore list is reduced to those which are actually required (this may involve fixing broken links that were ignored previously)
- [ ] 3 wiki_checks pass without seeing the "triple exception" failure on an external website

## Notes
- The full error is in the first comment, it is characterised by an error occurring and then getting the statement `During handling of the above exception, another exception occurred` at least once (typically twice)
- This may be as simple as increasing the timeout

**Comment by KathrynBaker** [comment]
```
Error Message
HTTPSConnectionPool(host='www.ortec-online.com', port=443): Read timed out. (read timeout=5)
Stacktrace
Traceback (most recent call last):
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.ortec-online.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\tests\page_tests.py", line 286, in test_GIVEN_a_page_IF_it_contains_urls_WHEN_url_loaded_THEN_response_is_http_ok
    fail = future.result()
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP\genie_python_3\BUILD-1622\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\tests\page_tests.py", line 258, in check_link
    failure = try_to_connect(link, session)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\tests\page_tests.py", line 174, in try_to_connect
    response = session.head(url, timeout=5)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\requests\sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Jenkins\workspace\IBEX_Wiki_Check\venv\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.ortec-online.com', port=443): Read timed out. (read timeout=5)
```

**Comment by KathrynBaker** [comment]
Picking up as a Friday ticket

**Comment by KathrynBaker** [comment]
A number of links have been fixed, I cannot guarantee that I haven't missed any, but the exception added should highlight those timeout errors into the list of things to fix, rather than being errors as above, the URLs to ignore list may need further expansion again over time, but we can consider increasing the timeout if we see enough connection timeout errors in the future on the console.

**Comment by JackEAllen** [comment]
Review completed and changes merged in. I did leave [a few comments](https://github.com/ISISComputingGroup/ibex_wiki_checker/pull/18#pullrequestreview-911538727) about suggested future work however.
