### ISSUE TITLE
cryosms: fix compiler error (and some warning)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7294]
The cryosms driver is failing to build on linux with the following warnings and errors
```
I"../../../../../../libraries/master/boost/include/"  -I/usr/include/tirpc  -c ../CRYOSMSDriver.cpp
In file included from ../CRYOSMSDriver.cpp:37:0:
../QueuedStateMachine.h:202:8: warning: extra tokens at end of #endif directive [enabled by default]
 #endif !QUEUEDSTATEMACHINE_H
        ^
In file included from ../CRYOSMSDriver.cpp:42:0:
../CRYOSMSDriver.h: In constructor ‘CRYOSMSDriver::CRYOSMSDriver(const char*, std::string, std::map<std::basic_string<char>, std::basic_string<char> >)’:
../CRYOSMSDriver.h:69:55: warning: ‘CRYOSMSDriver::qsm’ will be initialized after [-Wreorder]
  boost::msm::back::state_machine<cryosmsStateMachine> qsm;
                                                       ^
../CRYOSMSDriver.h:49:7: warning:   ‘bool CRYOSMSDriver::started’ [-Wreorder]
  bool started;
       ^
../CRYOSMSDriver.cpp:71:1: warning:   when initialized here [-Wreorder]
 CRYOSMSDriver::CRYOSMSDriver(const char *portName, std::string devPrefix, std::map<std::string, std::string> argMap)
 ^
In file included from ../CRYOSMSDriver.cpp:42:0:
../CRYOSMSDriver.h:82:14: warning: ‘CRYOSMSDriver::devicePrefix’ will be initialized after [-Wreorder]
  std::string devicePrefix;
              ^
../CRYOSMSDriver.h:47:7: warning:   ‘bool CRYOSMSDriver::writeDisabled’ [-Wreorder]
  bool writeDisabled;
       ^
../CRYOSMSDriver.cpp:71:1: warning:   when initialized here [-Wreorder]
 CRYOSMSDriver::CRYOSMSDriver(const char *portName, std::string devPrefix, std::map<std::string, std::string> argMap)
 ^
In file included from ../CRYOSMSDriver.cpp:42:0:
../CRYOSMSDriver.h:65:7: warning: ‘CRYOSMSDriver::abortQueue’ will be initialized after [-Wreorder]
  bool abortQueue;
       ^
../CRYOSMSDriver.h:44:36: warning:   ‘std::map<std::basic_string<char>, std::basic_string<char> > CRYOSMSDriver::envVarMap’ [-Wreorder]
  std::map<std::string,std::string> envVarMap;
                                    ^
../CRYOSMSDriver.cpp:71:1: warning:   when initialized here [-Wreorder]
 CRYOSMSDriver::CRYOSMSDriver(const char *portName, std::string devPrefix, std::map<std::string, std::string> argMap)
 ^
../CRYOSMSDriver.cpp:80:131: warning: ‘asynPortDriver::asynPortDriver(const char*, int, int, int, int, int, int, int, int)’ is deprecated (declared at /isis/data/jenkins/workspace/EPICS_IOC_RHEL6/support/asyn/master/include/asynPortDriver.h:52) [-Wdeprecated-declarations]
   0), qsm(this), started(false), devicePrefix(devPrefix), writeDisabled(FALSE), atTarget(true), abortQueue(true), envVarMap(argMap)
                                                                                                                                   ^
../CRYOSMSDriver.cpp: In member function ‘asynStatus CRYOSMSDriver::checkHeaterOut()’:
../CRYOSMSDriver.cpp:62:93: error: cannot pass objects of non-trivially-copyable type ‘std::map<std::basic_string<char>, std::basic_string<char> >::mapped_type {aka class std::basic_string<char>}’ through ‘...’
 errlogSevPrintf(errlogMajor, "Error returned when calling %s with arguments %s", #func, arg1);\
                                                                                             ^
../CRYOSMSDriver.cpp:338:3: note: in expansion of macro ‘RETURN_IF_ASYNERROR2’
   RETURN_IF_ASYNERROR2(getDb, envVarMap.at("HEATER_OUT"), heatOut);
   ^
../CRYOSMSDriver.cpp:62:93: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘std::map<std::basic_string<char>, std::basic_string<char> >::mapped_type {aka std::basic_string<char>}’ [-Wformat=]
 errlogSevPrintf(errlogMajor, "Error returned when calling %s with arguments %s", #func, arg1);\
                                                                                             ^
../CRYOSMSDriver.cpp:338:3: note: in expansion of macro ‘RETURN_IF_ASYNERROR2’
   RETURN_IF_ASYNERROR2(getDb, envVarMap.at("HEATER_OUT"), heatOut);
   ^
../CRYOSMSDriver.cpp: In member function ‘asynStatus CRYOSMSDriver::putDbAndWait(const string&, const void*, double)’:
../CRYOSMSDriver.cpp:648:9: warning: unused variable ‘was_processed’ [-Wunused-variable]
     int was_processed = procNotify.wasProcessed; // was record processed as result of write e.g. due to it being a PP field
         ^
../CRYOSMSDriver.cpp: In member function ‘asynStatus CRYOSMSDriver::readFile(std::string)’:
../CRYOSMSDriver.cpp:677:6: warning: unused variable ‘rowNum’ [-Wunused-variable]
  int rowNum = 0;
      ^
../CRYOSMSDriver.cpp: In member function ‘double CRYOSMSDriver::unitConversion(double, std::string, std::string)’:
../CRYOSMSDriver.cpp:740:106: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
     errlogSevPrintf(errlogMajor, "Error: Units not converted for %f, %s to %s", value, startUnit, endUnit);
                                                                                                          ^
../CRYOSMSDriver.cpp:740:106: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
../CRYOSMSDriver.cpp:740:106: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘std::string {aka std::basic_string<char>}’ [-Wformat=]
../CRYOSMSDriver.cpp:740:106: warning: format ‘%s’ expects argument of type ‘char*’, but argument 5 has type ‘std::string {aka std::basic_string<char>}’ [-Wformat=]
../CRYOSMSDriver.cpp: In member function ‘asynStatus CRYOSMSDriver::setupPersistOn()’:
../CRYOSMSDriver.cpp:55:92: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘double’ [-Wformat=]
 errlogSevPrintf(errlogMajor, "Error returned when calling %s with arguments %s", #func, arg);\
                                                                                            ^
../CRYOSMSDriver.cpp:1032:2: note: in expansion of macro ‘RETURN_IF_ASYNERROR1’
  RETURN_IF_ASYNERROR1(setupFastRamp, persistCurr);
  ^
../CRYOSMSDriver.cpp: In function ‘int CRYOSMSConfigure(const iocshArgBuf*)’:
../CRYOSMSDriver.cpp:1278:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < sizeof(envVarsNames) / sizeof(const char*); ++i)
                                                                ^
../CRYOSMSDriver.cpp: At global scope:
../CRYOSMSDriver.cpp:67:20: warning: ‘driverName’ defined but not used [-Wunused-variable]
 static const char *driverName = "CRYOSMSDriver"; ///< Name of driver for use in message printing 
                    ^
```
reorder warning may or may not be an issue e.g. https://stackoverflow.com/questions/1828037/whats-the-point-of-g-wreorder

**Comment by LilithCole** [comment]
reorder not an issue as none are interdependent, will fix anyway though as it's trivial to do so whilst I'm doing the rest

**Comment by LilithCole** [comment]
https://github.com/ISISComputingGroup/EPICS-Cryosms/pull/19

**Comment by FreddieAkeroyd** [comment]
@LilithCole I get all my system tests failing with
```
Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS-DEBUG2\support\IocTestFramework\master\tests\cryosms.py", line 87, in setUp
    self.ca.assert_that_pv_is("INIT", "Startup complete",  timeout=60)
  File "C:\Instrument\Apps\EPICS-DEBUG2\support\IocTestFramework\master\utils\channel_access.py", line 271, in assert_th
at_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS-DEBUG2\support\IocTestFramework\master\utils\channel_access.py", line 250, in assert_th
at_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Exception date time: 2022-08-20 21:01:40.317525
Expected PV, 'TE:NDW2127:CRYOSMS_01:INIT' to have value 'Startup complete' (type: 'str').
Final PV value was 'Startup incomplete' (type: 'str')
```
There is only one error in the log early on
```
TE:NDW2127:CRYOSMS_01:HEATER:VOLT:_SP: No reply within 1000 ms to "S H 3.670000<0d><0a>"
```
It may be my setup so I'm going to merge and see what system tests, in particular the debug one,  say.

**Comment by FreddieAkeroyd** [comment]
Forget above, looks like it needs `\\` or '/'
