### ISSUE TITLE
T-Jump System Driver

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7350]
As someone using the T-Jump in IBEX, I want to be able to view the key parts of the system at once, and to abstract the parts that can vary to keep the system simple to use.

## Acceptance Criteria
- [ ] The Phase 1 T-Jump System IOC has been created (Software 2.3)
- [ ] The Phase 1 T-Jump System OPI has been created (System Design 2.1.5, Software 2.4)

## Notes
- The information for the acceptance criteria can be expanded by looking at the documents at https://stfc365.sharepoint.com/sites/ISISProject-813/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FISISProject%2D813%2FShared%20Documents%2FGeneral%2FTechnical%20documentation%2F01%20Design%2FSoftware%20Work%20Package&viewid=f91da496%2D72ac%2D4e58%2D90fe%2Dfceba8e86f54

**Comment by LilithCole** [comment]
I'm getting the following consistent test failures:
```FAIL [21.866s]: test_WHEN_temperature_set_on_block_1_THEN_temperature_updates_on_controller_0__CALIBRATION_FILE_1x1_txt_CALIBRATION_FOLDER_tjmpap_master_calibrations_CALIBRATION_BASE_DIR_C_Instrument_Apps_EPICS_support_1_0_ (tests.tjmpap.TjmpapTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Instrument\Apps\EPICS\support\tjmpap\master\system_tests\tests\tjmpap.py", line 121, in test_WHEN_temperature_set_on_block_1_THEN_temperature_updates_on_controller
    self.ca_euro.assert_that_pv_is("TEMP:SP:RBV", 5.0 / multiplier)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 271, in assert_that_pv_is    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 250, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Exception date time: 2022-10-21 10:35:15.185653
Expected PV, 'TE:NDLT1172:EUROTHRM_01:A01:TEMP:SP:RBV' to have value '5.0' (type: 'float').
Final PV value was '0.0' (type: 'float')

======================================================================
FAIL [29.930s]: test_WHEN_temperature_set_on_block_1_THEN_temperature_updates_on_controller_1__CALIBRATION_FILE_1x2_txt_CALIBRATION_FOLDER_tjmpap_master_calibrations_CALIBRATION_BASE_DIR_C_Instrument_Apps_EPICS_support_2_0_ (tests.tjmpap.TjmpapTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Instrument\Apps\EPICS\support\tjmpap\master\system_tests\tests\tjmpap.py", line 121, in test_WHEN_temperature_set_on_block_1_THEN_temperature_updates_on_controller
    self.ca_euro.assert_that_pv_is("TEMP:SP:RBV", 5.0 / multiplier)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 271, in assert_that_pv_is    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 250, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Exception date time: 2022-10-21 10:35:45.125128
Expected PV, 'TE:NDLT1172:EUROTHRM_01:A01:TEMP:SP:RBV' to have value '2.5' (type: 'float').
Final PV value was '0.0' (type: 'float')

======================================================================
FAIL [5.787s]: test_WHEN_temperature_set_on_readback_controller_via_backdoor_THEN_temperature_updates_correctly (tests.tjmpap.TjmpapTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\tjmpap\master\system_tests\tests\tjmpap.py", line 139, in test_WHEN_temperature_set_on_readback_controller_via_backdoor_THEN_temperature_updates_correctly
    self.ca.assert_that_pv_is_number("SAMPLE:TEMP", 33.0, tolerance=0.01)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 382, in assert_that_pv_is_number
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 250, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Exception date time: 2022-10-21 10:37:00.580922
Expected PV 'TE:NDLT1172:TJMPAP_01:SAMPLE:TEMP' value to be equal to '33.0' (type: 'float') (tolerance: '0.01' (type: 'float'))
Final PV value was '0.0' (type: 'float')
```

**Comment by NikolaRoev** [comment]
Have ran the tests multiple times and tested the functionality in question manually, and was not able to reproduce the issue. Could this be affected by a configuration that I am missing?
