### ISSUE TITLE
ARACCESS: MySQL connection pool exhaustion

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7590]
## Where?

It looks like ARACCESS on enginx-stress-1 is exhausting the MySQL connection pool because it's not closing results properly.

```
[2023-01-19 13:38:28] Exception ignored in: <generator object SQLAbstraction.query_returning_cursor at 0x000002B4E5C2B4A0>
[2023-01-19 13:38:28] Traceback (most recent call last):
[2023-01-19 13:38:28]   File "C:\Instrument\Apps\Python3\lib\site-packages\genie_python\mysql_abstraction_layer.py", line 215, in query_returning_cursor
[2023-01-19 13:38:28]     curs.close()
[2023-01-19 13:38:28]   File "C:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\cursor_cext.py", line 414, in close
[2023-01-19 13:38:28]     self._cnx.handle_unread_result()
[2023-01-19 13:38:28]   File "C:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\connection_cext.py", line 862, in handle_unread_result
[2023-01-19 13:38:28]     raise InternalError("Unread result found")
[2023-01-19 13:38:28] mysql.connector.errors.InternalError: Unread result found
```

```
[2023-01-23 18:12:34] [2023-01-23 18:12:34.208445] MAJOR: Failed to write header in log file C:\logs\INSTRONA_01\INSTRONA_01_2023-01-19T13_26_08.dat for start time 2023-01-23 18:10:51.700000. 
Error is: 'Unable to get connection from pool: Failed getting connection; pool exhausted'
```

## Acceptance criteria 
- [ ] ARACCESS does not exhaust MySQL connection pool

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by pheest** [comment]
handle_unread_result in mysql/connection.py raises an 'Unread result found' exception - when closing a cursor - if not all available results have been read.
This will cause the connection close call in mysql_abstration_layer.py to be skipped, resulting in a leak of connection handles.

**Comment by pheest** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/374
https://github.com/ISISComputingGroup/IBEX/pull/7621

**Comment by pheest** [comment]
Tests to verify correct connection closure have been added ad new file test_mysql_abstraction_layer.py.

**Comment by rerpha** [comment]
Should we patch to enginx-stress-1?
