### ISSUE TITLE
dbsvr: reduce error logging

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7656]
mysql was not running and dbsvr was rapidly fillign the disk with errors

```
Fri Mar  3 23:59:58 2023] 

[Fri Mar  3 23:59:59 2023] [2023-03-03 23:59:59.319486] MAJOR: Problem connecting to experimental details database: Traceback (most recent call last):

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\connection_cext.py", line 263, in _open_connection

[Fri Mar  3 23:59:59 2023]     self._cmysql.connect(**cnx_kwargs)

[Fri Mar  3 23:59:59 2023] _mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on '127.0.0.1:3306' (10061)

[Fri Mar  3 23:59:59 2023] 

[Fri Mar  3 23:59:59 2023] The above exception was the direct cause of the following exception:

[Fri Mar  3 23:59:59 2023] 

[Fri Mar  3 23:59:59 2023] Traceback (most recent call last):

[Fri Mar  3 23:59:59 2023]   File "A:\Apps\EPICS\ISIS\inst_servers\master\DatabaseServer\database_server.py", line 354, in <module>

[Fri Mar  3 23:59:59 2023]     exp_data = ExpData(MACROS["$(MYPVPREFIX)"], ExpDataSource())

[Fri Mar  3 23:59:59 2023]   File "A:\Apps\EPICS\ISIS\inst_servers\master\DatabaseServer\exp_data.py", line 47, in __init__

[Fri Mar  3 23:59:59 2023]     self._db = SQLAbstraction('exp_data', "exp_data", "$exp_data")

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\genie_python\mysql_abstraction_layer.py", line 119, in __init__

[Fri Mar  3 23:59:59 2023]     self._start_connection_pool()

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\genie_python\mysql_abstraction_layer.py", line 138, in _start_connection_pool

[Fri Mar  3 23:59:59 2023]     conn = mysql.connector.connect(user=self._user, password=self._password, host=self._host, database=self._dbid,

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\pooling.py", line 273, in connect

[Fri Mar  3 23:59:59 2023]     return _get_pooled_connection(**kwargs)

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\pooling.py", line 87, in _get_pooled_connection

[Fri Mar  3 23:59:59 2023]     _CONNECTION_POOLS[pool_name] = MySQLConnectionPool(**kwargs)

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\pooling.py", line 408, in __init__

[Fri Mar  3 23:59:59 2023]     self.add_connection()

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\pooling.py", line 514, in add_connection

[Fri Mar  3 23:59:59 2023]     cnx = connect(**self._cnx_config)

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\pooling.py", line 286, in connect

[Fri Mar  3 23:59:59 2023]     return CMySQLConnection(*args, **kwargs)

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\connection_cext.py", line 101, in __init__

[Fri Mar  3 23:59:59 2023]     self.connect(**kwargs)

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\abstracts.py", line 1095, in connect

[Fri Mar  3 23:59:59 2023]     self._open_connection()

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\mysql\connector\connection_cext.py", line 268, in _open_connection

[Fri Mar  3 23:59:59 2023]     raise get_mysql_exception(

[Fri Mar  3 23:59:59 2023] mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (10061)

[Fri Mar  3 23:59:59 2023] 

[Fri Mar  3 23:59:59 2023] Traceback (most recent call last):

[Fri Mar  3 23:59:59 2023]   File "c:\Instrument\Apps\Python3\lib\site-packages\pcaspy\driver.py", line 631, in getValue

[Fri Mar  3 23:59:59 2023]     newValue = driver.read(self.info.reason)
```

**Comment by KathrynBaker** [comment]
Filling up on the cryomag system
