### ISSUE TITLE
Run control: handle scientific notation

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7823]
On LET on the 23/5/23 at ~13:36 (see blockserver logs) the blockserver became unresponsive and refused to change configuration due to a value being used in run control in scientific notation rather than decimals. (`1e-06`)  

The commit that caused this is here: 
http://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=commitdiff;h=5c72669c2f76809ee11fea8d8ae594cb70226d94

Blockserver logs: 

```
[Tue May 23 13:40:22 2023] [2023-05-23 13:40:22.287290] INFO: Start loading config 'LET_Base'...
[Tue May 23 13:40:22 2023] [2023-05-23 13:40:22.298290] MINOR: Error in loading component: Element '{[http://epics.isis.rl.ac.uk/schema/blocks/1.0}rc_lowlimit':](http://epics.isis.rl.ac.uk/schema/blocks/1.0%7Drc_lowlimit%27:) '1e-06' is not a valid value of the atomic type 'xs:decimal'., line 451
[Tue May 23 13:40:22 2023] [2023-05-23 13:40:22.307290] INFO: Traceback (most recent call last):
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\schema_checker.py", line 68, in check_xml_data_matches_schema
[Tue May 23 13:40:22 2023]     schema.assertValid(doc)
[Tue May 23 13:40:22 2023]   File "src\lxml\etree.pyx", line 3643, in lxml.etree._Validator.assertValid
[Tue May 23 13:40:22 2023] lxml.etree.DocumentInvalid: Element '{[http://epics.isis.rl.ac.uk/schema/blocks/1.0}rc_lowlimit':](http://epics.isis.rl.ac.uk/schema/blocks/1.0%7Drc_lowlimit%27:) '1e-06' is not a valid value of the atomic type 'xs:decimal'., line 451
[Tue May 23 13:40:22 2023]
[Tue May 23 13:40:22 2023] During handling of the above exception, another exception occurred:
[Tue May 23 13:40:22 2023]
[Tue May 23 13:40:22 2023] Traceback (most recent call last):
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", line 151, in _import_configs
[Tue May 23 13:40:22 2023]     config = self.load_config(comp_name, True)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\core\config_list_manager.py", line 181, in load_config
[Tue May 23 13:40:22 2023]     config.load_inactive(name, is_component)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\core\inactive_config_holder.py", line 53, in load_inactive
[Tue May 23 13:40:22 2023]     config = self.load_configuration(name, is_component, False)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\core\config_holder.py", line 426, in load_configuration
[Tue May 23 13:40:22 2023]     comp = self._filemanager.load_config(name, self._macros, True)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 83, in load_config
[Tue May 23 13:40:22 2023]     self._check_against_schema(ElementTree.tostring(root, encoding='utf8'), FILENAME_BLOCKS)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\file_manager.py", line 163, in _check_against_schema
[Tue May 23 13:40:22 2023]     ConfigurationSchemaChecker.check_xml_data_matches_schema(schema_path, xml)
[Tue May 23 13:40:22 2023]   File "A:\EPICS\ISIS\inst_servers\master\BlockServer\fileIO\schema_checker.py", line 70, in check_xml_data_matches_schema
[Tue May 23 13:40:22 2023]     raise ConfigurationInvalidUnderSchema(str(err))
[Tue May 23 13:40:22 2023] BlockServer.fileIO.schema_checker.ConfigurationInvalidUnderSchema: Element '{[http://epics.isis.rl.ac.uk/schema/blocks/1.0}rc_lowlimit':](http://epics.isis.rl.ac.uk/schema/blocks/1.0%7Drc_lowlimit%27:) '1e-06' is not a valid value of the atomic type 'xs:decimal'., line 451
```
We should ideally fix the blockserver to accept scientific notation (as we do for everywhere else!) which looks like it'll involve modifying the XML parsing for `blocks.xml` or if this isn't possible then don't let a user save run control settings as scientific notation from the GUI level. Given that it's not hard to parse scientific notation, and we allow it everywhere else, I am in favour of the former option.

I have just had a quick look and XML [forbids the use of scientific notation](https://docstore.mik.ua/orelly/xml/schema/ch16_01.htm#ch16-77036) in the `xs:decimal` type , however `xs:float` does allow it.

### Acceptance criteria
- [ ] A user putting in something in scientific notation does not crash the blockserver and make it unusable until we come along and manually edit the .xml file that is causing it to crash

**Comment by rerpha** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/380
release notes: https://github.com/ISISComputingGroup/IBEX/pull/8086
